import test from 'node:test';import assert from 'node:assert/strict';
import {parseAgmArticleEvidence,agmRecoverySurface} from '../src/agm-article-evidence.js';
import {agmArticleLabel} from '../src/agm-article-label.js';
import {getSource} from '../src/registry.js';import {hash} from '../src/policy.js';
import {candidateFrom,factualLabel} from '../src/metadata.js';import {store,pepper} from './helpers.js';
import {recheckFacts} from '../src/facts-recheck.js';import {reviewDetail} from '../src/operator-review.js';
import {administer} from '../src/admin.js';import {recoverySurface,recoveryCacheKey} from '../src/facts-readiness.js';
import {runPendingRechecks} from '../src/pending-lifecycle.js';
const now=Date.parse('2026-10-08T12:00:00Z'),date='2026-10-01T10:00:00.000Z',robot='User-agent: *\nAllow: /',base='https://acousticguitarmagazine.jp',source=getSource('agm');
const row=(section='interview')=>({source_id:'agm',review_status:'pending',source_url:base+'/'+(section==='news'?'':section+'/')+'2026-1001-fixture/',published_at:date,product_facts:null});
function html(r,title,body,extra=''){return `<link rel="canonical" href="${r.source_url}"><meta property="og:title" content="${title}"><meta property="article:published_time" content="${date}"><div class="post-title"><h2>${title}</h2></div>${r.source_url.includes('/2026-')&&!r.source_url.match(/\/(interview|gears|lesson|column|beginners)\//)?`<h1>${title}</h1>`:''}<main class="post-item"><article>${body}</article></main>${extra}`;}
const parse=(r,t,b,e)=>parseAgmArticleEvidence(html(r,t,b,e),source,r);
for(const [section,title,body,part] of [
 ['beginners','コード進行の基礎','<p>コード進行の基礎を解説します。</p>','コード進行'],
 ['lesson','合成曲「朝の歌」のコード進行','<p>コード進行を解説します。</p><h2>「朝の歌」について</h2>','「朝の歌」'],
 ['gears','SOUND CHECK 合成機材','<p>試奏した内容を紹介します。</p><h2>SYNTH GUITARS／AB-42</h2>','SYNTH GUITARS AB-42'],
 ['interview','合成奏者が語る弾き語り','<p>合成奏者が弾き語りについて語ります。</p>','合成奏者'],
 ['column','音楽制作を考える','<p>音楽制作の考え方を解説します。</p>','自宅での音楽制作'],
 ['news','合成奏者が新アルバムをリリース','<p>シンガー・ソングライターの合成奏者がアルバム『朝の空』をリリースする。</p>','朝の空']
])test('explicit article recovery '+section,()=>{const r=row(section),f=parse(r,title,body);assert.equal(f.publishedAt,date);assert.ok(agmArticleLabel(f.productFacts,f.eventType).includes(part));assert.notEqual(agmArticleLabel(f.productFacts,f.eventType),title);assert.ok(!JSON.stringify(f).includes('<p>'));assert.equal(f.productFacts.articleUrl,r.source_url);});
test('insufficient or unrelated/hidden evidence cannot supply facts; size and canonical fail closed',()=>{const r=row();for(const b of ['<p>特定できない話題。</p>','<aside><p>合成奏者が弾き語りを語る。</p></aside>','<div class="related-block"><p>合成奏者が弾き語りを語る。</p></div>','<p hidden>合成奏者が弾き語りを語る。</p>'])assert.throws(()=>parse(r,'合成奏者が語る新たな話題',b),/facts_not_recovered/);assert.throws(()=>parseAgmArticleEvidence('x'.repeat(1000001),source,r),/too_large/);assert.throws(()=>parseAgmArticleEvidence(html(r,'合成奏者が語る弾き語り','<p>合成奏者の弾き語り。</p>').replace('rel="canonical"','rel="other"'),source,r));});
test('date is never URL/release/modified date; missing page date keeps existing RSS date only',()=>{const r=row(),h=html(r,'合成奏者が語る弾き語り','<p>合成奏者の弾き語り。</p>');assert.throws(()=>parseAgmArticleEvidence(h.replace(date,'2026-10-02T10:00:00.000Z'),source,r),/facts_date_changed/);assert.equal(parseAgmArticleEvidence(h.replace(/<meta property="article:published_time"[^>]+>/,''),source,r).publishedAt,date);assert.throws(()=>parseAgmArticleEvidence(h,source,{...r,published_at:null}),/facts_date_changed/);});
test('title priority, multiple guitars, review/advertorial remain editorial, never launch',()=>{const r=row('gears'),f=parse(r,'合成奏者の愛用ギター','<p>合成奏者が使うギター。【PR】</p><h2>ALPHA／A-1</h2><h2>BETA／B-2</h2>');assert.equal(f.productFacts.models.length,2);assert.equal(f.productFacts.editorialNotice,'advertorial');assert.equal(f.eventType,'agm_editorial');assert.match(factualLabel(f.productFacts,f.eventType),/2種類の愛用ギター/);const i=parse(row(),'合成奏者が語る弾き語り','<p>合成奏者はフィンガーピッキングにも言及。</p>');assert.equal(i.productFacts.topic,'singing');});
test('permission required and per-article cache key; metadata shortage can schedule recovery',()=>{const r=row();assert.ok(recoverySurface(r,source));assert.equal(agmRecoverySurface(r,{...source,explicitAutomationPermission:false}),null);const a=recoveryCacheKey({...r,id:'a'},source,recoverySurface(r,source)),b=recoveryCacheKey({...r,id:'b'},source,recoverySurface(r,source));assert.notEqual(a,b);});
async function setup(){const s=await store(),a={...source,enabled:true,productionEnabled:true,robotsHash:await hash(robot)},r=row();await administer(s,{action:'publish-on',reason:'review_complete'},now,[a]);await s.recordHealth({sourceId:'agm',status:'healthy',reasonCode:'ok',checkedAt:now,successfulAt:now});const {item}=await candidateFrom({url:r.source_url,title:'合成奏者が語る未知のテーマ',metadataCategories:['合成奏者'],date,agmSection:'interview'},a,{isAllowed:()=>true},now,pepper);await s.put(item);return {s,a,r,item};}
test('real recovery path: two bounded requests, cached repeat, pending READY, no body/image or teacher records, rediscovery preserves facts',async()=>{const {s,a,r,item}=await setup(),calls=[];const fetcher=async url=>{calls.push(url);return new Response(url===a.robotsUrl?robot:html(r,'合成奏者が語る弾き語り','<p>合成奏者の弾き語り。DO_NOT_STORE_BODY</p><img src="https://example.org/image.jpg">'),{headers:{'Content-Type':'text/html'}});};const d=await reviewDetail(s,item.id,now,[a],pepper),input={id:d.id,revision:d.revision,snapshot:d.snapshot,requestId:crypto.randomUUID()};const out=await recheckFacts(s,input,now,[a],pepper,{type:'system_repair',id:'test'},{fetcher,sleep:async()=>{}});assert.equal(out.validation.valid,true);assert.equal(calls.length,2);const saved=(await s.candidates())[0];assert.equal(saved.review_status,'pending');assert.ok(!JSON.stringify(saved).includes('DO_NOT_STORE_BODY')&&!JSON.stringify(saved).includes('image.jpg'));assert.equal((await s.db.prepare('SELECT COUNT(*) n FROM news_decision_ledger').first()).n,0);assert.equal((await s.db.prepare('SELECT COUNT(*) n FROM news_operator_feedback').first()).n,0);await s.put(item);assert.deepEqual((await s.candidates())[0],saved);assert.equal((await recheckFacts(s,input,now,[a],pepper,{type:'system_repair',id:'test'},{fetcher:()=>{throw Error('no refetch');}})).replayed,true);});
test('autonomous recheck invokes article recovery and preserves source one-per-day budget',async()=>{const {s,a,r,item}=await setup(),calls=[];const out=await runPendingRechecks(s,now,[a],pepper,{fetcher:async u=>{calls.push(u);return new Response(u===a.robotsUrl?robot:html(r,'合成奏者が語る弾き語り','<p>合成奏者の弾き語り。</p>'),{headers:{'Content-Type':'text/html'}});},sleep:async()=>{}});assert.equal(out.recovered,1);assert.equal(out.newlyReady,1);assert.equal(calls.length,2);assert.equal((await s.candidates())[0].review_status,'pending');assert.equal((await s.db.prepare('SELECT COUNT(*) n FROM news_decision_ledger').first()).n,0);});
test('News discovery can reuse an already fetched article without a new request',async()=>{const r=row('news'),title='合成奏者が新アルバムをリリース',body='<p>シンガー・ソングライターの合成奏者がアルバム『朝の空』をリリースする。</p>',a={...source,enabled:true,productionEnabled:true};const recovered=parse(r,title,body);const {item}=await candidateFrom({url:r.source_url,title,date,agmSection:'news',articleRecovery:recovered},a,{isAllowed:()=>true},now,pepper);assert.equal(item.productFacts.action,'music_release');assert.equal(item.publicationDecision,'PUBLISH_REVIEW');assert.match(item.label,/朝の空/);const bad=await candidateFrom({url:r.source_url,title,date,agmSection:'news',articleRecovery:{...recovered,publishedAt:'2026-10-02T10:00:00.000Z'}},a,{isAllowed:()=>true},now,pepper);assert.equal(bad.item.productFacts,null);});
