import test from 'node:test';import assert from 'node:assert/strict';
import {AGM_SECTIONS,AGM_SURFACES,agmArticleUrl,agmNewsListing,agmArticleMetadata} from '../src/agm-sections.js';
import {collectSource} from '../src/collector.js';import {candidateFrom,factualLabel} from '../src/metadata.js';
import {getSource,evidenceGate} from '../src/registry.js';import {hash} from '../src/policy.js';
import {publicationValidation} from '../src/decision-policy.js';import {publishAutomatic} from '../src/automatic.js';
import {administer} from '../src/admin.js';import {store,pepper} from './helpers.js';
const now=Date.parse('2026-10-08T12:00:00Z'),base='https://acousticguitarmagazine.jp',robot='User-agent: *\nAllow: /',allow={isAllowed:()=>true};
const active=async()=>({...getSource('agm'),enabled:true,productionEnabled:true,robotsHash:await hash(robot)});
const url=(s,n=0)=>`${base}/${s==='news'?'':s+'/'}2026-1001-example-${n}/`;
const title=s=>s==='interview'?'合成奏者が語るソロギター':s==='gears'?'合成奏者の愛用アコギ':s==='news'?'Martin D-28 新製品を発表':'アコギのadd9を詳しく解説する記事';
const entry=(s,extra={})=>({url:url(s),title:title(s),date:'2026-10-01T10:00:00Z',metadataCategories:['合成奏者'],agmSection:s,...extra});
const card=(n=0)=>`<div class="post-wrap"><a class="post-obj" href="${url('news',n)}"><div class="post-obj-title"><p>${title('news')}</p></div></a></div>`;
const article=(u,date='2026-10-01T10:00:00Z')=>`<link rel="canonical" href="${u}"><h1>${title('news')}</h1><script type="application/ld+json">${JSON.stringify({'@graph':[{'@type':'Article','@id':u+'#article',datePublished:date,dateModified:'2026-10-08T12:00:00Z'}]})}</script><div>DO NOT STORE BODY</div><img src="https://example.com/not-fetched.jpg">`;
const feed=s=>`<rss><channel><item><title>${title(s)}</title><link>${url(s)}</link><pubDate>Thu, 01 Oct 2026 10:00:00 GMT</pubDate><category>合成奏者</category><description>DO NOT STORE BODY</description></item></channel></rss>`;
const fixtureFetch=calls=>async u=>{calls.push(u);const surf=AGM_SURFACES.find(s=>s.url===u);return new Response(u.endsWith('robots.txt')?robot:surf?.type==='rss'?feed(surf.section):surf?.type==='html'?Array.from({length:9},(_,i)=>card(i)).join(''):article(u),{headers:{'content-type':surf?.type==='rss'?'application/rss+xml':u.endsWith('robots.txt')?'text/plain':'text/html'}});};
test('permission evidence is current, exact attribution, fixed six sections, daily interval',()=>{const s=getSource('agm');assert.equal(evidenceGate(s,now),null);assert.equal(s.permissionRef,'agm-permission-2026-10-08');assert.equal(s.explicitAutomationPermission,true);assert.equal(s.name,'ACOUSTIC GUITAR MAGAZINE WEB');assert.equal(s.crawlIntervalHours,24);assert.deepEqual(AGM_SECTIONS,['beginners','lesson','gears','interview','news','column']);assert.equal(AGM_SURFACES.filter(s=>s.type==='rss').length,5);assert.equal(s.discoveryUrl,AGM_SURFACES[3].url);});
for(const s of AGM_SECTIONS)test(s+' becomes pending without publisher expressions or images',async()=>{const source=await active(),e=entry(s),{item}=await candidateFrom(e,source,allow,now,pepper);assert.ok(item);assert.equal(item.publicationDecision,'PUBLISH_REVIEW');assert.equal(item.sourceName,'ACOUSTIC GUITAR MAGAZINE WEB');assert.equal(item.publishedAt,'2026-10-01T10:00:00.000Z');assert.ok(!JSON.stringify(item).includes(e.title));assert.ok(!('body' in item)&&!('images' in item));});
test('unknown editorial topic is partial facts for review, never invented',async()=>{const {item}=await candidateFrom(entry('column',{title:'合成奏者の今週の話題'}),await active(),allow,now,pepper);assert.equal(item.productFacts.articleType,'column');assert.equal(item.productFacts.topic,undefined);assert.equal(factualLabel(item.productFacts,item.eventType),null);assert.equal(item.decisionReason,'label_required');});
test('datePublished wins over updated and URL; conflicting or absent date stays unknown',()=>{const u=url('news');assert.equal(agmArticleMetadata(article(u),u).date,'2026-10-01T10:00:00.000Z');assert.equal(agmArticleMetadata(article(u,'not-a-date'),u).date,'');assert.equal(agmArticleMetadata(article(u)+`<meta property="article:published_time" content="2026-10-02T10:00:00Z">`,u).date,'');assert.equal(agmArticleMetadata(`<link rel="canonical" href="${u}"><h1>ギター情報</h1>`,u).date,'');});
test('canonical mismatch, optout and changed listing fail closed',()=>{assert.throws(()=>agmArticleMetadata(article(url('news')),url('news',1)));assert.throws(()=>agmNewsListing('<meta name="robots" content="noindex">'+card()));assert.throws(()=>agmNewsListing('<a href="'+url('news')+'">unscoped link</a>'));});
test('only fixed article scopes; ignore pagination and sidebar; listing capped at nine',()=>{for(const bad of [base+'/tag/guitar/',base+'/news/page/2/',base+'/wp-json/',base+'/2026-1001-x/?secret=x','https://evil.example/2026-1001-x/'])assert.equal(agmArticleUrl(bad,'news'),null);assert.equal(agmNewsListing(Array.from({length:15},(_,i)=>card(i)).join('')+'<aside>'+card(20)+'</aside>').length,9);});
for(const date of ['', '2026-12-01T00:00:00Z','2026-01-01T00:00:00Z'])test('date gate '+date,async()=>{const r=await candidateFrom(entry('lesson',{date}),await active(),allow,now,pepper);if(!date){assert.equal(r.item.publishedAt,null);assert.equal(r.item.decisionReason,'missing_date');}else assert.equal(r.reason,'date_outside_window');});
test('robots/optout and promotional exclusions remain',async()=>{const source=await active();assert.equal((await candidateFrom(entry('lesson'),source,{isAllowed:()=>false},now,pepper)).decision,'REJECT');assert.equal((await candidateFrom(entry('gears',{title:'アコギ 送料無料クーポン'}),source,allow,now,pepper)).decision,'REJECT');});
test('six-section collection is bounded, preserves existing rows and teaching records; repeated day skipped',async()=>{
 const s=await store(),source=await active(),calls=[],delays=[];
 for(const section of ['interview','gears','news']){const {item}=await candidateFrom(entry(section),source,allow,now,pepper);await s.put(item);}
 s.db.raw.exec("UPDATE candidate_items SET review_status='approved',source_id=CASE WHEN source_url LIKE '%interview%' THEN 'agm' ELSE 'manual-agm-test' END,label='既存の独自見出し'");
 const before=await s.candidates();const report=await collectSource('agm',s,{mode:'production',registry:[source],now,pepper,clock:()=>now,sleep:async ms=>delays.push(ms),fetcher:fixtureFetch(calls)});
 assert.equal(report.outcome,'collected');assert.equal(report.sections.length,6);assert.equal(report.requests,16);assert.equal(report.requestCounts.article,9);assert.equal(report.candidates,14);assert.equal(report.duplicates,3);assert.equal(report.pending,11);assert.equal(report.rejected,0);assert.equal(calls.length,16);assert.ok(delays.every(ms=>ms>=1000));assert.ok(!calls.some(u=>u.includes('/page/')||u.includes('jpg')));
 const rows=await s.candidates();for(const row of before)assert.deepEqual(rows.find(x=>x.id===row.id),row);
 assert.ok(rows.filter(r=>!before.some(b=>b.id===r.id)).every(r=>r.review_status==='pending'));
 assert.equal(s.db.raw.prepare('SELECT count(*) n FROM news_decision_ledger').get().n,0);assert.equal(s.db.raw.prepare('SELECT count(*) n FROM news_shadow_evaluations').get().n,0);
 assert.ok(!JSON.stringify(rows).includes('DO NOT STORE BODY'));
 const repeat=await collectSource('agm',s,{mode:'production',registry:[source],now:now+1000,pepper,fetcher:fixtureFetch(calls)});assert.equal(repeat.outcome,'backoff');assert.equal(calls.length,16);
});
test('source STOP and missing pepper make no publisher requests',async()=>{for(const stopped of [true,false]){const s=await store(),source=await active();if(stopped)await administer(s,{action:'source-disable',target:'agm',reason:'operator_stop'},now,[source]);const calls=[];const r=await collectSource('agm',s,{mode:'production',registry:[source],now,pepper:stopped?pepper:undefined,sleep:async()=>{},fetcher:fixtureFetch(calls)});assert.equal(r.outcome,stopped?'source_disabled':'headline_pepper_required');assert.equal(calls.length,0);}});
test('ready editorial supports real validation but permission never auto approves; provenance cannot move source',async()=>{const s=await store(),source=await active();await administer(s,{action:'publish-on',reason:'review_complete'},now);const {item}=await candidateFrom(entry('beginners'),source,allow,now,pepper);await s.put({...item,publicationDecision:'AUTO_PUBLISHABLE'});await s.recordHealth({sourceId:'agm',status:'healthy',reasonCode:'ok',checkedAt:now,successfulAt:now});let row=(await s.candidates())[0];assert.equal((await publicationValidation(s,row,now,[source],pepper)).valid,true);assert.equal(await publishAutomatic(s,source,[source],now,pepper),0);assert.equal((await publicationValidation(s,{...row,source_id:'amass'},now,[source],pepper)).errors.includes('facts_provenance_invalid'),true);assert.equal((await publicationValidation(s,{...row,source_url:url('beginners',2)},now,[source],pepper)).errors.includes('facts_provenance_invalid'),true);});

test('AGM News canonical Article headline works without an h1; unrelated JSON-LD cannot supply it',()=>{const u=url('news'),html=`<link rel="canonical" href="${u}"><script type="application/ld+json">${JSON.stringify({'@graph':[{'@type':'Article','@id':u+'#article',headline:'アコギの新情報',datePublished:'2026-10-08T08:00:00+00:00'},{'@type':'WebSite',headline:'無関係'}]})}</script>`;assert.equal(agmArticleMetadata(html,u).title,'アコギの新情報');assert.equal(agmArticleMetadata(html,u).date,'2026-10-08T08:00:00.000Z');assert.throws(()=>agmArticleMetadata(html.replace(u+'#article',u+'#wrong'),u));});

test('topic/award/brand tags are never mistaken for named interviewees',async()=>{
 for(const [section,title,tags] of [['column','ソロ・ギターの奏法解説',['ソロ・ギター']],['interview','グラミー賞受賞者が語るアコギ',['グラミー']],['gears','SEILEN／MODEL｜NEW GEAR SOUND CHECK',['SEILEN']]]){
  const {item}=await candidateFrom(entry(section,{title,metadataCategories:tags}),await active(),allow,now,pepper);assert.equal(item.productFacts.person,undefined);
 }
});

test('expanded collection requires its exact publisher permission and daily limit',()=>{const s=getSource('agm');for(const change of [{permissionRef:null},{permissionRef:'other-grant'},{explicitAutomationPermission:false},{automationPolicy:'documented_silence'},{crawlIntervalHours:12}])assert.equal(evidenceGate({...s,...change},now),'permission_required');});
