import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync}from'node:fs';import{DatabaseSync}from'node:sqlite';
import{store,database,pepper,source,options,response,robots}from'./helpers.js';
import{manualCandidate,ingestManual}from'../src/manual-ingestion.js';import{ARTICLE_CHECKS,REQUIRED_CHECKS}from'../src/review.js';import{handleNewsRequest}from'../src/worker.js';import{administer,operatorPlan}from'../src/admin.js';import{eventEndsAt}from'../src/event.js';import{candidateFrom,ikebeListingFacts,validatedProductFacts}from'../src/metadata.js';import{getSource}from'../src/registry.js';import{duplicateOf}from'../src/dedupe.js';import{collectSource}from'../src/collector.js';import{qualitySnapshot,qualityRegressionGate,candidateTicker,itemQuality}from'../src/quality-gate.js';import{labelInformationScore,compareTicker}from'../../../apps/cruise-port/news-quality.js';import{saleLabel}from'../src/sale.js';import{publishAutomatic}from'../src/automatic.js';import{replayPendingFacts}from'../src/pending-replay.js';
const now=Date.parse('2026-10-01T00:00:00Z');
const artist=(extra={})=>({kind:'artist_live',sourceId:'manual-ikebe',officialUrl:'https://www.ikebe-gakki.com/blog/synthetic-quality-event/',publishedAt:'2026-09-28',artist:'合成ギタリスト',eventType:'exhibition',eventName:'使用機材展示',eventDate:'2026-10-13',endDate:'2026-11-01',venue:'合成会場',relevanceReason:'guitar_event',checks:{...Object.fromEntries(REQUIRED_CHECKS.map(k=>[k,true])),guitarEvidenceChecked:true},articleChecks:{...Object.fromEntries(Object.entries(ARTICLE_CHECKS).map(([k,v])=>[k,v[0]])),relevance:'guitar'},...extra});
const api=async(s,at=now,path='/v1/news?limit=50',cache=null,registry=[])=>{const r=await handleNewsRequest(new Request('https://news.example'+path),{NEWS_DB:s.db,NEWS_API_MODE:'production'},at,{registry,cache});assert.equal(r.status,200);return r.json();};
const published=async()=>{const s=await store();await administer(s,{action:'publish-on',reason:'review_complete'},now);return s;};
test('event deadline exact JST end and single-day/interview semantics',()=>{const end=Date.parse('2026-11-02T00:00:00+09:00')-1;assert.equal(eventEndsAt({kind:'artist_live',endDate:'2026-11-01'}),end);assert.equal(eventEndsAt({kind:'artist_live',eventDate:'2026-11-01'}),end);assert.equal(eventEndsAt({kind:'artist_live',eventType:'interview',eventDate:'2026-11-01'}),null);assert.ok(Number.isNaN(eventEndsAt({kind:'artist_live',endDate:'2026-02-30'})));});
test('event visible before/exact end, hidden after in list/category/ticker, retained in D1',async()=>{const s=await published(),i=await manualCandidate(artist(),now);await ingestManual(s,i,now);for(const path of ['/v1/news?limit=50','/v1/news?category=live_guitar','/v1/news/ticker']){const at=path.endsWith('ticker')?now:i.eventEndsAt;assert.equal((await api(s,at,path)).items.length,1);assert.equal((await api(s,i.eventEndsAt+1,path)).items.length,0);}assert.equal((await api(s,i.eventEndsAt-1)).items.length,1);assert.equal((await s.candidates()).length,1);});
test('event page cache deadline includes preceding expired item; cursor and offset pagination',async()=>{const s=await published();for(let n=0;n<3;n++){const i=await manualCandidate(artist({officialUrl:`https://www.ikebe-gakki.com/blog/synthetic-event-${n}/`,artist:'合成ギタリスト'+n,publishedAt:`2026-09-${28-n}`,endDate:n===0?'2026-10-01':'2026-11-01',eventDate:'2026-10-01'}),now);await ingestManual(s,i,now);}const end=eventEndsAt({kind:'artist_live',endDate:'2026-10-01'});const map=new Map(),cache={match:async k=>map.get(k.url)?.clone(),put:async(k,v)=>map.set(k.url,v.clone())};const before=await api(s,end-1000,'/v1/news?limit=1&offset=1',cache);const after=await api(s,end+1,'/v1/news?limit=1&offset=1',cache);assert.notEqual(before.items[0].id,after.items[0].id);assert.equal((await api(s,end,'/v1/news?limit=50')).items.length,3);const first=await api(s,end+1,'/v1/news?limit=1');const next=await api(s,end+1,'/v1/news?limit=1&cursor='+encodeURIComponent(first.nextCursor));assert.equal(next.items.length,1);assert.notEqual(first.items[0].id,next.items[0].id);assert.equal(next.nextCursor,null);});
test('additive migration restores old Sleep approved rows without clearing collection stop or retention',()=>{const db=new DatabaseSync(':memory:'),dir=new URL('../migrations/',import.meta.url);for(const name of readdirSync(dir).sort().filter(n=>!n.startsWith('0010')))db.exec(readFileSync(new URL(name,dir),'utf8'));db.exec("INSERT INTO source_state(source_id,disabled,takedown) VALUES('sleepfreaks',1,0),('natalie',1,1)");db.exec(readFileSync(new URL('0010_core_quality.sql',dir),'utf8'));assert.deepEqual({...db.prepare("SELECT disabled,publication_blocked FROM source_state WHERE source_id='sleepfreaks'").get()},{disabled:1,publication_blocked:0});assert.equal(db.prepare("SELECT publication_blocked FROM source_state WHERE source_id='natalie'").get().publication_blocked,1);db.close();});
const ready=id=>({...getSource(id),enabled:true,productionEnabled:true});
const ikebe=(title,url='https://www.ikebe-gakki-pb.com/new_product/999991/')=>({title,eventTitle:title,url,date:'2026-09-30T00:00:00+09:00',listingSection:'product_news',listingCategory:'electric_guitar_bass'});
for(const title of ['Fender AB-123 エレキギター 新製品発表','MXR EF-123 エフェクター 新製品発表','VOX AM-123 ギターアンプ 新製品発表','Gibson GC-123 ギターケース 新製品発表'])test('Ikebe explicit factual extraction / AUTO '+title,async()=>{const a=ready('ikebe'),s=await published(),{item}=await candidateFrom(ikebe(title),a,{isAllowed:()=>true},now,pepper);assert.equal(item.productFacts.identifierBasis,'explicit_listing_facts');assert.equal(validatedProductFacts(item.productFacts),true);assert.equal(item.publicationDecision,'AUTO_PUBLISHABLE');await s.put(item);await s.recordHealth({sourceId:a.id,status:'healthy',reasonCode:'ok',checkedAt:now,successfulAt:now});assert.equal(await publishAutomatic(s,a,[a],now,pepper),1);});
for(const title of ['合成 AB-123 ギター 新製品発表','Fender 無名ギター 新製品発表','Fender USB3 ギター 新製品発表','Fender 特別モデル AB-123 ギター 新製品発表'])test('Ikebe no invented brand/model '+title,()=>{assert.equal(ikebeListingFacts(ikebe(title),ready('ikebe')),null);});
test('Ikebe unknown context and planned release stay REVIEW; stored null replay never guesses/reopens',async()=>{const s=await published(),a=ready('ikebe');for(const [n,title]of ['Fender AB-123 ギター 発売予定','Fender 無名ギター 新製品発表'].entries()){const {item}=await candidateFrom(ikebe(title,`https://www.ikebe-gakki-pb.com/new_product/${999992+n}/`),a,{isAllowed:()=>true},now,pepper);assert.equal(item.publicationDecision,'PUBLISH_REVIEW');await s.put(item);}const replay=await replayPendingFacts(s,a,[a],now,pepper);assert.equal(replay.results.filter(i=>i.promoted).length,0);await s.db.prepare("UPDATE candidate_items SET review_status='rejected'").run();assert.equal((await replayPendingFacts(s,a,[a],now,pepper)).results.length,0);});
const ikRow=(url='https://www.ikmultimedia.com/news/?item_id=100',extra={})=>({id:'id'+url,sourceId:'ik',sourceUrl:url,publishedAt:'2026-09-03T00:00:00Z',eventType:'release',productFacts:{brand:'IK Multimedia',product:'TONEX Board',category:'amps_effects',version:null,identifierBasis:'official_manufacturer_model',manufacturerSource:'ik'},...extra});
test('IK canonical tracking variant and adjacent IDs dedupe same-day truthful facts',()=>{assert.equal(duplicateOf(ikRow(),ikRow('https://www.ikmultimedia.com/news/?utm_source=x&item_id=100')),true);assert.equal(duplicateOf(ikRow(),ikRow('https://www.ikmultimedia.com/news/?item_id=101',{eventType:'other'})),true);});
test('IK distinct product, different day, update/launch and underspecified pack preserved',()=>{const a=ikRow();for(const changes of [{publishedAt:'2026-09-04T00:00:00Z'},{eventType:'update'},{productFacts:{...a.productFacts,product:'TONEX ONE'}},{productFacts:{...a.productFacts,scopeUncertain:true}}])assert.equal(duplicateOf(a,ikRow('https://www.ikmultimedia.com/news/?item_id=101',changes)),false);});
test('IK storage blocks semantically duplicate pending before publication, keeps rejected decision',async()=>{const s=await published(),a=ready('ik');const input=(id,title)=>({title,eventTitle:title,url:'https://www.ikmultimedia.com/news/?item_id='+id,date:'2026-09-03T00:00:00Z',listingSection:'ik_press'});const first=(await candidateFrom(input(999901,'TONEX Board released'),a,{isAllowed:()=>true},now,pepper)).item;const second=(await candidateFrom(input(999902,'TONEX Board announced'),a,{isAllowed:()=>true},now,pepper)).item;assert.equal(await s.put(first),true);assert.equal(await s.put(second),false);await s.db.prepare("UPDATE candidate_items SET review_status='rejected'").run();assert.equal(await s.put(second),false);assert.equal((await s.candidates()).length,1);});
async function approvedSleep(){const s=await published(),a={...source,productionEnabled:true};const {item}=await candidateFrom({title:'BOSS GX-1 発表',url:'https://sleepfreaks-dtm.com/dtm-materials/test-core/',date:'2026-09-30T00:00:00Z'},a,{isAllowed:()=>true},now,pepper);await s.put(item);await s.db.prepare("UPDATE candidate_items SET review_status='approved'").run();return {s,a,item};}
for(const kind of ['403','timeout','503','layout'])test('collection '+kind+' stops fetch only, preserves approved and no second attempt',async()=>{const{s,a}=await approvedSleep();const opt=options({now,mode:'production',registry:[a],fetcher:async u=>{if(kind==='timeout')throw new DOMException('test','TimeoutError');if(kind==='403'||kind==='503')return response('',Number(kind));return u.endsWith('robots.txt')?response(robots):response('not XML',200,{'content-type':'text/plain'});}});await collectSource(a.id,s,opt);assert.equal((await s.state(a.id)).disabled,true);assert.equal((await s.state(a.id)).publicationBlocked,false);assert.equal((await api(s,now,'/v1/news?limit=50',null,[a])).items.length,1);assert.equal((await collectSource(a.id,s,opt)).requests,0);});
test('explicit publication kill/takedown hide; unblock cannot resume stopped collection',async()=>{const{s,a}=await approvedSleep();await administer(s,{action:'source-collection-stop',target:a.id,reason:'operator_stop'},now,[a]);assert.equal((await api(s,now,'/v1/news',null,[a])).items.length,1);await administer(s,{action:'source-publication-block',target:a.id,reason:'quality_review'},now,[a]);assert.equal((await api(s,now,'/v1/news',null,[a])).items.length,0);await administer(s,{action:'source-publication-unblock',target:a.id,reason:'review_complete'},now,[a]);assert.equal((await s.state(a.id)).disabled,true);assert.equal((await api(s,now,'/v1/news',null,[a])).items.length,1);await administer(s,{action:'source-disable',target:a.id,reason:'owner_request'},now,[a]);assert.equal((await api(s,now,'/v1/news',null,[a])).items.length,0);});
test('shared ticker vocabulary ranks fresh HIGH exhibition before older ordinary product, no LOW lead',()=>{const list=Array.from({length:6},(_,n)=>({id:String(n),label:'Fender、AB-123を発表',sourceUrl:'https://example.invalid/'+n,sourceName:'合成',category:'electric_guitar_bass',publishedAt:new Date(now-(5+n/10)*86400000).toISOString()}));const event={...list[0],id:'event',label:'松本孝弘、使用ギター・機材展示',publishedAt:new Date(now-86400000).toISOString(),category:'live_guitar'};list.push(event,{...event,id:'low',label:'合成、ギター演奏に関する話題'});assert.equal(candidateTicker(list,now)[0].id,'event');assert.equal(itemQuality(event),'HIGH VALUE');assert.equal(labelInformationScore(event.label),4);assert.equal(qualitySnapshot(list,{ticker:candidateTicker(list,now),now}).tickerOmissions.length,0);assert.equal(list.sort((a,b)=>compareTicker(a,b,now))[0].id,'event');});
for(const [reason,change]of Object.entries({freshUseful24h_loss:c=>c.freshUseful24h=0,freshUseful7d_loss:c=>c.freshUseful7d=0,expired_event_visible:c=>c.expiredEvents=['bad'],visible_duplicates_increased:c=>c.visibleDuplicates++,fresh_high_value_ticker_omission:c=>c.tickerOmissions=['event'],approved_mass_visibility_loss:c=>c.visibleIds=[],source_mass_visibility_loss:c=>c.sourceCounts={}}))test('regression gate '+reason,()=>{const b=qualitySnapshot(Array.from({length:5},(_,n)=>({id:String(n),label:'ギター新製品を発表',sourceUrl:'https://example.invalid/'+n,sourceName:'Sleep',category:'acoustic_guitar',publishedAt:new Date(now-1000).toISOString()})),{now});const c=structuredClone(b);change(c);assert.ok(qualityRegressionGate(b,c).reasons.includes(reason));});
test('Sale safe percentage and allowlisted brand facts reflected without hype',()=>{const facts={kind:'sale',category:'sale',seller:'合成',event:'期間限定の値下げ',brand:null,brands:['Fender'],equipment:['ギター'],endDate:'2026-10-11',percentOff:25};assert.match(saleLabel(facts),/25%値下げ/);assert.match(saleLabel(facts),/Fender/);assert.equal(saleLabel({...facts,brands:['invented']}),null);assert.equal(saleLabel({...facts,percentOff:101}),null);});

test('stored proven Ikebe facts replay prepares AUTO only; rejected item never reopens',async()=>{const s=await published(),a=ready('ikebe');const {item}=await candidateFrom(ikebe('Fender AB-123 エレキギター 新製品発表'),a,{isAllowed:()=>true},now,pepper);await s.put({...item,publicationDecision:'PUBLISH_REVIEW'});assert.equal((await replayPendingFacts(s,a,[a],now,pepper)).results[0].promoted,true);assert.equal((await s.candidates())[0].publication_decision,'AUTO_PUBLISHABLE');});
test('product alert emits when an automatic stop would hide mass approved items',async()=>{const s=await published();await s.db.prepare("INSERT INTO source_state(source_id,disabled,publication_blocked) VALUES('sleepfreaks',1,1)").run();for(let n=0;n<3;n++)await s.db.prepare("INSERT INTO candidate_items(id,source_id,source_name,source_url,normalized_url,label,category,topic_key,collected_at,review_status,review_reason,expires_at) VALUES(?,'sleepfreaks','Sleep',?,?,?,'dtm_software',?,?,'approved','test',?)").bind('synthetic-alert-'+n,'https://example.invalid/'+n,'https://example.invalid/'+n,'LUNA新製品'+n,'alert'+n,new Date(now).toISOString(),now+86400000).run();await s.alertSourceDisabled('sleepfreaks',now);assert.equal((await s.db.prepare("SELECT COUNT(*) n FROM source_health_alerts WHERE reason_code='approved_mass_visibility_loss'").first()).n,1);});

test('operator CLI collection-only plan preserves global API; publication kills remain fail closed',async()=>{const{s,a}=await approvedSleep();for(const statement of operatorPlan({action:'source-collection-stop',target:a.id,reason:'operator_stop'},now,[a]))await s.db.prepare(statement.sql).bind(...statement.args).run();assert.equal((await s.controls()).api_enabled,1);assert.equal((await api(s,now,'/v1/news',null,[a])).items.length,1);assert.equal((await s.state(a.id)).disabled,true);assert.ok(operatorPlan({action:'source-publication-block',target:a.id,reason:'owner_request'},now,[a])[0].sql.includes('api_enabled=0'));});

test('IK translated pack and old incomplete facts never collapse into a base product launch',async()=>{const a=ready('ik');const {item}=await candidateFrom({title:'ReSingの追加ボイスパックを発売',url:'https://www.ikmultimedia.com/news/?item_id=999999',date:'2026-09-03T00:00:00Z',listingSection:'ik_press'},a,{isAllowed:()=>true},now,pepper);assert.equal(item.publicationDecision,'PUBLISH_REVIEW');assert.equal(item.productFacts.scopeUncertain,true);assert.equal(duplicateOf(item,ikRow('https://www.ikmultimedia.com/news/?item_id=100',{productFacts:{...item.productFacts,scopeUncertain:false}})),false);assert.equal(duplicateOf(ikRow(),ikRow('https://www.ikmultimedia.com/news/?item_id=101',{decisionReason:'label_required'})),false);});
