import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {setup,put,source,now} from './operator-case.js';
import {pepper,store as enableStore} from './helpers.js';
import {decisionInput,fixtureActor} from './operator-fixtures.js';
import {recheckFacts} from '../src/facts-recheck.js';
import {parseEventArticle} from '../src/high-value.js';
import {reviewDetail,operatorDecision} from '../src/operator-review.js';
import {getSource} from '../src/registry.js';
import {hash} from '../src/policy.js';
import {localDatabase} from '../scripts/local-db.mjs';
import {administer} from '../src/admin.js';
const robot='User-agent: *\nAllow: /';
const url='https://www.shimamura.co.jp/update/dtm-recording/2026/10/90254/';
const html=title=>`<h1>製品ニュース 記事一覧</h1><a href="${url}"><h2>${title}</h2><time>2026/10/01</time><span class="btn-cat-recording">DTM レコーディング</span></a>`;
async function setupCase(s){s??=await setup();const a={...source,robotsHash:await hash(robot)},id=await hash(url);const item=await put(s,'90254',{id,sourceUrl:url,normalizedUrl:url,publishedAt:'2026-09-30T15:00:00.000Z',productFacts:null,eventType:'other'});return {s,a,item};}
async function inputFor(s,id){const {requestId,snapshot,revision}=await decisionInput(s,{id});return {id,requestId,snapshot,revision};}
const fetcher=(text=html('SHURE MV6 新製品発表'),hook)=>async (url,options)=>{assert.equal(options.redirect,'manual');assert.equal(options.credentials,'omit');if(url.endsWith('robots.txt'))return new Response(robot);if(hook)await hook();return new Response(text,{headers:{'Content-Type':'text/html'}});};
const opts=f=>({fetcher:f,sleep:async()=>{}});
const count=(s,t)=>s.db.prepare(`SELECT COUNT(*) n FROM ${t}`).first();
async function run(c,i,options){return recheckFacts(c.s,i,now,[c.a],pepper,fixtureActor,options||opts(fetcher()));}

test('missing facts are visible; verified product recovery is pending, provenanced, CAS and not a decision',async()=>{const c=await setupCase(),i=await inputFor(c.s,c.item.id),d=await reviewDetail(c.s,c.item.id,now,[c.a],pepper);assert(d.factsReview.missing.length>0);const r=await run(c,i);assert(r.recovered);assert(r.validation.valid);const row=(await c.s.candidates())[0];assert.equal(row.review_status,'pending');assert.equal(row.review_revision,1);assert.equal(row.publication_decision,'PUBLISH_REVIEW');const p=JSON.parse(row.facts_provenance);assert(p.every(p=>p.sourceId===c.a.id&&p.sourceUrl===c.a.discoveryUrl&&p.verifiedAt===now&&p.parserVersion&&p.factField));assert(!JSON.stringify(row).includes('新製品発表'));for(const table of ['news_decision_ledger','news_operator_feedback'])assert.equal((await count(c.s,table)).n,0);const replay=await run(c,i,opts(()=>{throw Error('must not fetch');}));assert(replay.replayed);await assert.rejects(run(c,{...i,requestId:crypto.randomUUID()}),/candidate_changed/);});
test('recovered facts still require a final human decision; ordinary safe decision writes one ledger',async()=>{const c=await setupCase();await run(c,await inputFor(c.s,c.item.id));const d=await reviewDetail(c.s,c.item.id,now,[c.a],pepper);const input={id:d.id,requestId:crypto.randomUUID(),snapshot:d.snapshot,revision:d.revision,action:'approve',reason:'useful_product',label:d.validation.publishableLabel,category:d.category,publishedAt:d.publishedAt,checks:{factsChecked:true,relevanceChecked:true,duplicateChecked:true,independentLabelChecked:true}};await operatorDecision(c.s,input,now,[c.a],pepper,{type:'human_operator',id:'access:fixture-only'});assert.equal((await count(c.s,'news_decision_ledger')).n,1);assert.equal((await c.s.db.prepare('SELECT actor_type FROM news_decision_ledger').first()).actor_type,'human_operator');});
test('partial/unsupported extraction cannot invent an identifier or enable approval',async()=>{const c=await setupCase();const r=await run(c,await inputFor(c.s,c.item.id),opts(fetcher(html('新製品の録音マイクを発表'))));assert(!r.recovered);assert(!r.validation.valid);assert.equal((await c.s.candidates())[0].product_facts,null);});
for(const [name,upstream]of [['parser failure',fetcher('<html><script>SHURE MV6 新製品</script></html>')],['unavailable',async()=>new Response('',{status:503})],['timeout',async()=>{throw new DOMException('timeout','TimeoutError');}],['malicious redirect',async()=>new Response('',{status:302,headers:{Location:'http://127.0.0.1/'}})],['oversized response',async()=>new Response('',{headers:{'Content-Length':'9999999'}})],['optout',fetcher('<meta name="robots" content="noindex">'+html('SHURE MV6 新製品'))]])test(name+' preserves candidate and ledger',async()=>{const c=await setupCase(),before=(await c.s.candidates())[0];const operation=run(c,await inputFor(c.s,c.item.id),opts(upstream));if(['unavailable','optout'].includes(name))await assert.rejects(operation,/facts_source_gate/);else{const result=await operation;assert(!result.recovered);assert(!result.validation.valid);assert.equal((await c.s.state(c.a.id)).disabled,false);}assert.deepEqual((await c.s.candidates())[0],before);assert.equal((await count(c.s,'news_decision_ledger')).n,0);});
test('invalid/disabled sources and unknown client fields never fetch',async()=>{const c=await setupCase(),i=await inputFor(c.s,c.item.id);await assert.rejects(run(c,{...i,url:'https://evil.test/'}),/facts_request_invalid/);await assert.rejects(recheckFacts(c.s,i,now,[{...c.a,enabled:false}],pepper,fixtureActor,opts(()=>{throw Error('must not fetch');})),/facts_source_gate/);await c.s.db.prepare('INSERT INTO source_state(source_id,disabled) VALUES(?,1)').bind(c.a.id).run();await assert.rejects(run(c,i),/facts_source_gate/);});
test('concurrent decision wins; recovery cannot revive or overwrite it',async()=>{const c=await setupCase(),i=await inputFor(c.s,c.item.id);await assert.rejects(run(c,i,opts(fetcher(html('SHURE MV6 新製品'),async()=>{await operatorDecision(c.s,{...i,action:'reject',reason:'operator_review'},now,[c.a],pepper,fixtureActor);}))),/candidate_changed/);assert.equal((await c.s.candidates())[0].review_status,'rejected');assert.equal((await count(c.s,'news_facts_rechecks')).n,0);});
test('concurrent content edit invalidates full row snapshot even without revision change',async()=>{const c=await setupCase(),i=await inputFor(c.s,c.item.id);await assert.rejects(run(c,i,opts(fetcher(html('SHURE MV6 新製品'),async()=>{await c.s.db.prepare('UPDATE candidate_items SET label=? WHERE id=?').bind('Concurrent independent label',i.id).run();}))),/candidate_changed/);assert.equal((await c.s.candidates())[0].label,'Concurrent independent label');});
test('source cache is shared by candidates; repeated recheck does not multiply publisher requests',async()=>{const c=await setupCase();let requests=0;const f=fetcher();await run(c,await inputFor(c.s,c.item.id),opts(async(...args)=>{requests++;return f(...args);}));assert.equal(requests,2);const item=await put(c.s,'90253',{productFacts:null,eventType:'other'});const result=await run(c,await inputFor(c.s,item.id),opts(()=>{throw Error('must use cached surface');}));assert.equal(result.outcome,'facts_not_on_current_surface');assert.equal(requests,2);});
test('duplicate remains blocked; no fetch or fact rewrite',async()=>{const c=await setupCase();await c.s.db.prepare("UPDATE candidate_items SET category='amps_effects',product_facts=?,event_type=? WHERE id=?").bind(JSON.stringify({brand:'LAVA MUSIC',product:'LAVA STUDIO',version:null,category:'amps_effects'}),'new_product',c.item.id).run();const other=await put(c.s,'another',{productFacts:{brand:'LAVA MUSIC',product:'LAVA STUDIO',version:null,category:'amps_effects'},category:'amps_effects',eventType:'new_product'});await c.s.db.prepare("UPDATE candidate_items SET review_status='approved' WHERE id=?").bind(other.id).run();const before=(await c.s.candidates()).find(r=>r.id===c.item.id);const r=await run(c,await inputFor(c.s,c.item.id),opts(()=>{throw Error('no publisher request');}));assert.equal(r.outcome,'facts_duplicate_preserved');assert(!r.recovered);assert.deepEqual((await c.s.candidates()).find(r=>r.id===c.item.id),before);});
const eventUrl='https://www.ikebe-gakki.com/blog/synthetic-event/';
const eventHtml=(artist='阿部学',date='2026年10月21日')=>`<h1>${artist} ギターワークショップ</h1><h3>開催日時</h3><p>${date}</p><h3>会場</h3><p>イケシブPOPUP SPACE （渋谷）</p><h3>講師</h3><h2>${artist}</h2><p>Do not retain this body.</p>`;
test('event parser uses explicit labeled sections; no URL date, tags, other people or hidden fields',()=>{const a=getSource('ikebe-event'),f=parseEventArticle(eventHtml(),a,eventUrl);assert.equal(f.artist,'阿部学');assert.equal(f.eventDate,'2026-10-21');assert.equal(f.venue,'イケシブ');const incomplete=parseEventArticle(eventHtml('西山隆行',''),a,eventUrl);assert(!incomplete.eventDate);assert.equal(incomplete.artist,'西山隆行');assert.throws(()=>parseEventArticle('<h1>ギター ワークショップ</h1><script><h3>開催日時</h3>2026年10月21日</script><meta name="robots" content="noarchive">',a,eventUrl),/facts_optout/);assert(!JSON.stringify(f).includes('body'));});
for(const [artist,ready]of [['阿部学',true],['西山隆行',false]])test(`event verified facts ${artist}: existing publication scope preserved`,async()=>{const c=await setupCase(),a={...getSource('ikebe-event'),enabled:true,productionEnabled:true,robotsHash:await hash(robot)},id=await hash(eventUrl);await c.s.recordHealth({sourceId:a.id,status:'healthy',reasonCode:'ok',checkedAt:now,successfulAt:now});await c.s.db.prepare("UPDATE candidate_items SET id=?,source_id=?,source_url=?,normalized_url=?,category='live_guitar',event_type='guitar_event' WHERE id=?").bind(id,a.id,eventUrl,eventUrl,c.item.id).run();const r=await recheckFacts(c.s,await inputFor(c.s,id),now,[a],pepper,fixtureActor,opts(fetcher(eventHtml(artist))));assert(r.recovered);assert.equal(r.validation.valid,ready);assert.equal((await c.s.candidates())[0].review_status,'pending');});
test('retry payload substitution is rejected, transaction failure leaves candidate unchanged',async()=>{const c=await setupCase(),i=await inputFor(c.s,c.item.id);await run(c,i);await assert.rejects(run(c,{...i,revision:1}),/idempotency_payload_changed/);const d=await setupCase(),before=(await d.s.candidates())[0];await d.s.db.prepare("CREATE TRIGGER facts_fixture_fail BEFORE INSERT ON news_admin_audit WHEN NEW.action='facts-recheck' BEGIN SELECT RAISE(ABORT,'fixture'); END").run();await assert.rejects(run(d,await inputFor(d.s,d.item.id)),/facts_transaction_failed/);assert.deepEqual((await d.s.candidates())[0],before);assert.equal((await count(d.s,'news_facts_rechecks')).n,0);});
test('actual local workerd/D1 facts trigger/CAS, retry and stale decision regression',async()=>{const dir=await mkdtemp(join(tmpdir(),'news-facts-d1-'));let runtime;try{runtime=await localDatabase(dir);const s=await enableStore(runtime.db);await administer(s,{action:'publish-on',reason:'review_complete'},now,[source]);await s.recordHealth({sourceId:source.id,status:'healthy',reasonCode:'ok',checkedAt:now,successfulAt:now});const c=await setupCase(s),i=await inputFor(s,c.item.id),r=await run(c,i);assert(r.recovered);assert((await run(c,i)).replayed);assert.equal((await count(s,'news_decision_ledger')).n,0);await assert.rejects(operatorDecision(s,{...i,action:'reject',reason:'operator_review'},now,[c.a],pepper,fixtureActor),/candidate_changed/);}finally{await runtime?.mf.dispose();await rm(dir,{recursive:true,force:true});}});

test('untrusted recovery URL cannot escape source host or contact local addresses',async()=>{const c=await setupCase();c.a={...c.a,robotsUrl:'http://127.0.0.1/private'};let contacted=0;const before=(await c.s.candidates())[0];const result=await run(c,await inputFor(c.s,c.item.id),opts(()=>{contacted++;throw Error('forbidden');}));assert.equal(contacted,0);assert.equal(result.outcome,'facts_source_invalid');assert.deepEqual((await c.s.candidates())[0],before);});
