import test from 'node:test';import assert from 'node:assert/strict';
import {now,source,setup,put,approveInput} from './operator-case.js';
import {pepper,env} from './helpers.js';import {decisionInput,fixtureActor} from './operator-fixtures.js';
import {operatorDecision,candidateSnapshot} from '../src/operator-review.js';
import {publicationValidation} from '../src/decision-policy.js';import {publishAutomatic} from '../src/automatic.js';
import {similarDecisions} from '../src/operator-insights.js';import {shadowMetrics,saveShadowEvaluation} from '../src/operator-shadow.js';
import {handleNewsRequest} from '../src/worker.js';
const human={type:'human_operator',id:'access:fixture-human'};
const decide=(s,i,t=now)=>operatorDecision(s,i,t,[source],pepper,human);
async function published(s){const item=await put(s,'firmware',{eventType:'firmware'});await operatorDecision(s,await approveInput(s,item),now,[source],pepper,fixtureActor);return item;}
const take=(s,item)=>decisionInput(s,{id:item.id,action:'reject',reason:'minor_update',takedown:true});
test('published firmware takedown is one atomic human reject, retained facts/history, cache revision, no retrospective Shadow and replay',async()=>{const s=await setup(),item=await published(s);const before=await s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(item.id).first(),revision=(await s.controls()).revision;const input=await take(s,item),result=await decide(s,input);assert.deepEqual(await decide(s,input),result);const after=(await s.candidates())[0];assert.equal(after.review_status,'rejected');assert.equal(after.product_facts,before.product_facts);assert.equal(after.source_url,before.source_url);assert.equal(after.review_revision,before.review_revision+1);assert.equal((await s.controls()).revision,revision+1);assert(await s.db.prepare('SELECT * FROM news_takedowns WHERE item_id=?').bind(item.id).first());const ledger=(await s.db.prepare("SELECT * FROM news_decision_ledger WHERE actor_type='human_operator'").all()).results;assert.equal(ledger.length,1);const f=JSON.parse(ledger[0].decision_features_json);assert.equal(f.policySignal.articleNature,'routine_minor');assert.equal(f.insightsProfile.type,'firmware');assert.equal(f.shadowEvaluation,undefined);assert.equal((await shadowMetrics(s,now)).unmatchedHumanDecisions,1);for(const path of ['/v1/news','/v1/news/ticker']){const body=await(await handleNewsRequest(new Request('http://localhost'+path),env(s.db),now,{registry:[source],cache:null})).json();assert(!body.items.some(r=>r.id===item.id));}});
test('takedown requires explicit human reject and exact current snapshot; concurrent requests yield one winner',async()=>{const s=await setup(),item=await published(s),input=await take(s,item);for(const bad of [{...input,takedown:false},{...input,action:'approve'},{...input,snapshot:'0'.repeat(64)}])await assert.rejects(decide(s,bad),/operator_decision_invalid|candidate_changed/);await assert.rejects(operatorDecision(s,input,now,[source],pepper,fixtureActor),/operator_decision_invalid/);await assert.rejects(decide(s,{...input,takedown:undefined}),/already_decided/);const outcomes=await Promise.allSettled([decide(s,input),decide(s,{...input,requestId:crypto.randomUUID()})]);assert.equal(outcomes.filter(r=>r.status==='fulfilled').length,1);});
test('takedown child failure rolls back candidate, tombstone, Ledger, audit and control revision',async()=>{const s=await setup(),item=await published(s);const before=JSON.stringify(await s.candidates()),revision=(await s.controls()).revision;s.db.raw.exec("CREATE TRIGGER reject_failure BEFORE INSERT ON news_operator_feedback BEGIN SELECT RAISE(ABORT,'synthetic_failure'); END;");await assert.rejects(decide(s,await take(s,item)),/decision_transaction_failed/);assert.equal(JSON.stringify(await s.candidates()),before);assert.equal((await s.controls()).revision,revision);assert.equal((await s.db.prepare('SELECT COUNT(*) n FROM news_takedowns').first()).n,0);assert.equal((await s.db.prepare('SELECT COUNT(*) n FROM news_decision_ledger').first()).n,1);});
test('firmware minor/major/ambiguous candidates never auto-publish or auto-reject; significant firmware remains human approvable',async()=>{for(const nature of ['routine','major-new-feature','critical-fix','safety','major-compatibility','ambiguous']){const s=await setup(),item=await put(s,nature,{eventType:'firmware',publicationDecision:'AUTO_PUBLISHABLE',label:'SHURE、MV6のファームウェア更新'});assert.equal(await publishAutomatic(s,source,[source],now,pepper),0);assert.equal((await s.candidates())[0].review_status,'pending');assert.equal((await publicationValidation(s,(await s.candidates())[0],now,[source],pepper)).valid,true);if(nature==='major-new-feature')assert.equal((await decide(s,await approveInput(s,item))).action,'approve');}});
test('minor firmware teacher is usable similarity evidence but one example cannot activate recommendation or reject unrelated products',async()=>{const s=await setup(),item=await published(s);await decide(s,await take(s,item));const other=await put(s,'next',{eventType:'firmware',productFacts:{...item.productFacts,product:'MV7'}}),row=(await s.candidates()).find(r=>r.id===other.id),validation=await publicationValidation(s,row,now,[source],pepper),result=await similarDecisions(s,row,validation,now);assert.equal(result.rejectCount,1);assert.equal(result.similarityLevel,'WEAK_SIMILAR');assert.equal(result.recommendation,'NO_RECOMMENDATION');assert.equal(row.review_status,'pending');});
test('existing current pre-takedown Shadow is reused without inserting a post hoc evaluation',async()=>{const s=await setup(),item=await put(s,'observed',{eventType:'firmware'});const row=(await s.candidates())[0];await saveShadowEvaluation(s,{id:item.id,revision:row.review_revision,snapshot:await candidateSnapshot(row)},now,[source],pepper);s.db.raw.exec("UPDATE candidate_items SET review_status='approved'");const current=(await s.candidates())[0];const {prepareShadowEvaluation}=await import('../src/operator-shadow.js');const evaluation=await prepareShadowEvaluation(s,current,await publicationValidation(s,current,now,[source],pepper),now);await s.db.prepare('INSERT INTO news_shadow_evaluations VALUES(?,?,?,?,?,?,?,?,?,?)').bind(evaluation.evaluationId,current.id,current.review_revision,evaluation.candidateSnapshot,now,evaluation.policyVersion,evaluation.ruleVersion,evaluation.recommendation,JSON.stringify(evaluation.profile),JSON.stringify(evaluation)).run();const count=(await s.db.prepare('SELECT COUNT(*) n FROM news_shadow_evaluations').first()).n;await decide(s,await take(s,item),now+1);assert.equal((await s.db.prepare('SELECT COUNT(*) n FROM news_shadow_evaluations').first()).n,count);assert.equal((await shadowMetrics(s,now+1)).evaluatedHumanDecisions,1);});
