import test from 'node:test';import assert from 'node:assert/strict';
import {parseIkebeProductEvidence,ikebeProductSurface,IKEBE_PRODUCT_PARSER} from '../src/ikebe-product-evidence.js';
import {getSource} from '../src/registry.js';import {factualLabel,productFacts} from '../src/metadata.js';
import {recoverySurface,recoveryCacheKey} from '../src/facts-readiness.js';
import {setup,put,now} from './operator-case.js';import {pepper} from './helpers.js';import {decisionInput,fixtureActor} from './operator-fixtures.js';
import {recheckFacts} from '../src/facts-recheck.js';import {reviewDetail} from '../src/operator-review.js';import {runPendingRechecks} from '../src/pending-lifecycle.js';import {hash} from '../src/policy.js';
const source=getSource('ikebe'),robot='User-agent: *\nAllow: /';
const fulltone={brand:'Fulltone',models:['Silver Limited Edition OCD V2','Silver Limited Edition OCD GE'],tag:'effector',title:'OCD、日本限定モデル発売！',lead:'OCD。本モデルは日本限定企画モデルとして登場します。限定生産です。',type:'オーバードライブ／ディストーションペダルです。'};
const monster={brand:'MONSTER CABLE',models:['MONSTER POWER 8000','MONSTER POWER 8001'],tag:'recording-pa',title:'MONSTER CABLEより電源タップが新登場！',lead:'MONSTER CABLEより電源タップが新登場！',type:'電源プロテクターです。'};
const row=id=>({id:'fixture-'+id,source_id:'ikebe',source_url:`https://www.ikebe-gakki-pb.com/new_product/${id}/`,review_status:'pending',published_at:'2026-09-30T15:00:00.000Z'});
const html=(o,id=172640)=>`<link rel="canonical" href="${row(id).source_url}"><header><h1>Site</h1></header><article id="main"><div class="blog_title"><h1>${o.title}</h1><time class="sub_info_date" datetime="2026-10-01">2026年10月01日公開</time><ul><li class="cate-${o.tag}"><a>${o.tag}</a></li><li><a href="${source.discoveryUrl}tag/${o.brand.toLowerCase().replaceAll(' ','-')}/">${o.brand}</a></li></ul></div><div class="main_wrap">${o.models.map((m,i)=>`<h1 class="wp-block-heading">${o.brand}<br>${m}</h1><span>販売価格</span>${i===0?`<p class="wp-block-paragraph">${o.lead}</p>`:''}<p class="wp-block-paragraph">${o.type}</p>`).join('')}</div><aside><h1 class="wp-block-heading">Other<br>Related 9999</h1><p>発売</p></aside></article>`;
const parse=(o=fulltone,text=html(o))=>parseIkebeProductEvidence(text,source,row(172640));
test('Fulltone two models, Japan-limited release and independent precise label',()=>{const i=parse();assert.deepEqual(i.productFacts.models,fulltone.models);assert.equal(i.productFacts.editionMarket,'Japan');assert.equal(i.productFacts.productEvent.action,'limited_edition');assert.equal(i.productFacts.productType,'effect_pedal');assert.equal(i.eventType,'release');assert.match(factualLabel(i.productFacts,i.eventType),/Fulltone、.*OCD V2.*OCD GE」の日本限定モデルを発売$/);assert(!JSON.stringify(i).includes(fulltone.lead));});
test('MONSTER two explicit model fields and power-distribution launch',()=>{const i=parse(monster);assert.deepEqual(i.productFacts.models,monster.models);assert.equal(i.productFacts.brand,'MONSTER CABLE');assert.equal(i.productFacts.productType,'power_distribution');assert.equal(i.productFacts.category,'recording_audio');assert.equal(i.eventType,'new_product');assert.equal(i.productFacts.productEvent,undefined);});
test('generic unknown manufacturer and model family, no product whitelist',()=>{const o={brand:'Craft Lab',models:['Orbit RX700','Orbit RX701'],tag:'effector',title:'Craft Labより新製品ペダルが登場！',lead:'Craft Lab Orbit RX700 / RX701が新登場。',type:'エフェクターです。'};assert.deepEqual(parse(o).productFacts.models,o.models);assert.equal(parse(o).productFacts.brand,o.brand);});
for(const title of ['Fulltoneブランドのご案内','Fulltoneのペダルを比較レビュー','Fulltone OCD再入荷情報','Fulltone OCDをセール特価で発売','Fulltone OCD発売済み製品の紹介します','Fulltone OCDの交換ケースを新発売','Fulltone OCDを発売予定','Fulltone OCDは発売しない','Fulltone OCDを発売するかもしれません'])test('reject non-launch/context: '+title,()=>assert.throws(()=>parse({...fulltone,title}),/facts_scope_uncertain/));
test('prose mention, related list, missing identity and model-number enumeration fail closed',()=>{
 for(const text of [html(fulltone).replaceAll('class="wp-block-heading"','class="related"'),html(fulltone).replaceAll('Fulltone<br>','Unknown<br>'),html(fulltone).replace('Silver Limited Edition OCD V2','V2, 100, 8001'),html(fulltone).replaceAll('<br>',' '),html(fulltone).replace('class="main_wrap"','class="main_wrap" hidden')])assert.throws(()=>parse(fulltone,text),/facts_/);
 assert.throws(()=>parse({...fulltone,models:['Alpha 100','Other 200']}),/facts_identity_changed/);
 assert.throws(()=>parse({...fulltone,models:['Limited Edition AA100','Limited Edition BB200']}),/facts_identity_changed/);
});
test('ambiguous manufacturers/types, hidden or unrelated event cannot corroborate launch',()=>{
 assert.throws(()=>parse(fulltone,html(fulltone).replace('Fulltone<br>Silver Limited Edition OCD GE','Other<br>Silver Limited Edition OCD GE')),/facts_identity_changed/);
 for(const lead of ['以前OCDを発売しました。','他社のOCDが新登場。','OCDが登場しない。','OCDの仕様です。'])assert.throws(()=>parse({...fulltone,lead}),/facts_scope_uncertain/);
 assert.throws(()=>parse(fulltone,html(fulltone).replace('class="wp-block-paragraph"','class="wp-block-paragraph" hidden')),/facts_scope_uncertain/);
 assert.throws(()=>parse({...monster,type:'仕様です。',title:'MONSTER CABLE新製品',lead:'MONSTER CABLEが新登場。'}),/facts_scope_uncertain/);
});
test('nested related product text cannot supply type or event evidence',()=>{const o={...fulltone,lead:'OCDの仕様です。',type:'仕様です。'};const nested='<div class="related"><p class="wp-block-paragraph">Fulltone OCD日本限定モデルが新発売。エフェクターです。</p></div>';assert.throws(()=>parse(o,html(o).replace('</div><aside>',nested+'</div><aside>')),/facts_scope_uncertain/);});
test('strict canonical article URL, published date, opt-out and bounded response',()=>{
 for(const u of ['http://www.ikebe-gakki-pb.com/new_product/172640/','https://evil.test/new_product/172640/','https://www.ikebe-gakki-pb.com/new_product/172640/?x=1','https://www.ikebe-gakki-pb.com/new_product/category/effector/'])assert.equal(ikebeProductSurface({...row(172640),source_url:u},source),null);
 assert.equal(ikebeProductSurface({...row(172640),review_status:'approved'},source),null);
 assert.throws(()=>parse(fulltone,html(fulltone).replace('datetime="2026-10-01"','datetime="2026-10-02"')),/facts_date_changed/);
 assert.throws(()=>parse(fulltone,html(fulltone).replace('new_product/172640/','new_product/172649/')),/facts_source_invalid/);
 assert.throws(()=>parse(fulltone,'<meta name="robots" content="noarchive">'+html(fulltone)),/facts_optout/);
 assert.throws(()=>parse(fulltone,'x'.repeat(512001)),/facts_response_too_large/);
});
test('existing Ikebe identity and precise target recovery unchanged',()=>{assert.equal(recoverySurface({...row(172475)},source).parser,'target-evidence-3');assert.equal(productFacts('Yamaha RS20MM').product,'RS20MM');assert.equal(factualLabel({brand:'BOSS',product:'EX-4',category:'amps_effects',version:null},'new_product'),'BOSS、EX-4を発表');});
async function prepare(o=fulltone,id=172640){const s=await setup(),a={...source,enabled:true,productionEnabled:true,robotsHash:await hash(robot)},r=row(id),item=await put(s,'generic-'+id,{id:await hash(r.source_url),sourceId:'ikebe',sourceName:a.name,sourceUrl:r.source_url,normalizedUrl:r.source_url,publishedAt:r.published_at,productFacts:null,category:o===monster?'recording_audio':'amps_effects',eventType:'other'});await s.recordHealth({sourceId:'ikebe',status:'healthy',reasonCode:'ok',checkedAt:now,successfulAt:now});const before=await s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(item.id).first();let calls=0;return {s,a,item,before,options:{sleep:async()=>{},fetcher:async u=>{calls++;assert([a.robotsUrl,r.source_url].includes(u));return new Response(u===a.robotsUrl?robot:html(o,id),{headers:{'Content-Type':'text/html'}});}},calls:()=>calls};}
async function recover(c){const {requestId,snapshot,revision}=await decisionInput(c.s,{id:c.item.id});return recheckFacts(c.s,{id:c.item.id,requestId,snapshot,revision},now,[c.a],pepper,fixtureActor,c.options);}
for(const [name,o,id]of [['Fulltone',fulltone,172640],['MONSTER',monster,172649]])test(name+' recovery is READY but pending, same dates, no decision or teacher writes',async()=>{const c=await prepare(o,id),r=await recover(c);assert(r.recovered);assert(r.validation.valid);const d=await reviewDetail(c.s,c.item.id,now,[c.a],pepper);assert.equal(d.factsReview.recoveryClass,'READY_FOR_HUMAN_DECISION');const after=await c.s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(c.item.id).first();for(const k of ['published_at','expires_at','source_url','title_fingerprint','review_status','publication_decision'])assert.equal(after[k],c.before[k]);assert.equal(c.calls(),2);assert(JSON.parse(after.facts_provenance).every(p=>p.parserVersion===IKEBE_PRODUCT_PARSER&&p.sourceUrl===after.source_url));for(const t of ['news_decision_ledger','news_operator_feedback'])assert.equal((await c.s.db.prepare(`SELECT COUNT(*) n FROM ${t}`).first()).n,0);});
test('multi-model recovery retains duplicate block against a published individual model',async()=>{const c=await prepare(),other=await put(c.s,'existing',{productFacts:{brand:'Fulltone',product:fulltone.models[0],version:null,category:'amps_effects'},category:'amps_effects',eventType:'release'});await c.s.db.prepare("UPDATE candidate_items SET review_status='approved' WHERE id=?").bind(other.id).run();const r=await recover(c);assert(r.recovered);assert(r.validation.errors.includes('duplicate'));assert.equal((await reviewDetail(c.s,c.item.id,now,[c.a],pepper)).factsReview.recoveryClass,'DUPLICATE_BLOCKED');});
test('article cache is per candidate and cannot borrow neighboring product evidence',()=>{const a=recoverySurface(row(172640),source),b=recoverySurface(row(172649),source);assert.notEqual(recoveryCacheKey(row(172640),source,a),recoveryCacheKey(row(172649),source,b));});
test('autonomous recheck uses same primary extraction and keeps final human decision',async()=>{const c=await prepare(),r=await runPendingRechecks(c.s,now,[c.a],pepper,c.options);assert.equal(r.recovered,1);assert.equal(r.newlyReady,1);assert.equal(r.items[0].result,'RECOVERED_READY');assert.equal((await c.s.db.prepare('SELECT review_status FROM candidate_items WHERE id=?').bind(c.item.id).first()).review_status,'pending');assert.equal((await c.s.db.prepare('SELECT COUNT(*) n FROM news_decision_ledger').first()).n,0);});
test('letter-number model family and explicit bass-category distortion pedal stay factual',()=>{const o={brand:'Craft Lab',models:['HC-1 pro','HC-2B pro','HC-3B pro'],tag:'bass',title:'Craft Labから歪みペダル3機種が登場！',lead:'新しいペダルが登場！',type:'HC-1 proは歪みペダルです。'};const f=parse(o).productFacts;assert.equal(f.category,'amps_effects');assert.equal(f.models.length,3);assert.throws(()=>parse({...o,title:'Craft Labから新製品が登場！',type:'HC-1 proの仕様です。'}));});
test('numberless explicitly labeled product name and published/updated date separation',()=>{const o={...monster,models:['Power Control']},h=html(o).replace('</time>','</time><time class="sub_info_date" datetime="2026-10-04">2026年10月04日更新</time>');assert.equal(parse(o,h).publishedAt,'2026-09-30T15:00:00.000Z');assert.throws(()=>parse(o,h.replace('2026年10月04日更新','2026年10月04日公開')),/facts_parser_failure/);});
