import test from 'node:test';import assert from 'node:assert/strict';
import {manualCandidate,ingestManual} from '../src/manual-ingestion.js';import {MANUAL_SOURCES,manualEvidenceGate} from '../src/manual-sources.js';
import {qualitySnapshot,qualityRegressionGate,candidateTicker} from '../src/quality-gate.js';import{canonicalResearchUrl,guardedResearchArtifact,writeResearchArtifact}from'../scripts/research-retention.mjs';
import {store,pepper} from './helpers.js';import{administer}from'../src/admin.js';import{handleNewsRequest}from'../src/worker.js';import {ARTICLE_CHECKS,REQUIRED_CHECKS}from'../src/review.js';import{runtimeSources}from'../src/runtime.js';import{candidateFrom}from'../src/metadata.js';import{mkdtemp,readFile,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';
const now=Date.parse('2026-10-01T00:00:00Z');
const checks=()=>Object.fromEntries([...REQUIRED_CHECKS,'guitarEvidenceChecked'].map(k=>[k,true]));
const article=()=>({...Object.fromEntries(Object.entries(ARTICLE_CHECKS).map(([k,v])=>[k,v[0]])),relevance:'guitar'});
const sale=()=>({kind:'sale',sourceId:'manual-apu',officialUrl:'https://apu.software/',publishedAt:'2026-09-22',seller:'APU Software',saleType:'期間限定の値下げ',startDate:'2026-09-22',endDate:'2026-10-11',equipment:['DTM製品'],brands:[],benefit:'price_reduction',scope:'broad',percentOff:25,checks:checks(),articleChecks:article()});
const artist=()=>({kind:'artist_live',sourceId:'manual-ikebe',officialUrl:'https://www.ikebe-gakki.com/blog/synthetic-guitar-event/',publishedAt:'2026-09-28',artist:'合成ギタリスト',eventType:'concert',eventName:'合成ギター演奏会',eventDate:'2026-10-13',venue:'合成会場',relevanceReason:'guitarist',checks:checks(),articleChecks:article()});
const dbStore=async()=>{const s=await store();await administer(s,{action:'publish-on',reason:'review_complete'},now);return s;};
const api=(s,time=now,path='/v1/news')=>handleNewsRequest(new Request('https://news.example'+path),{NEWS_DB:s.db,NEWS_API_MODE:'production'},time,{registry:[],cache:null});
test('manual Sale: structured facts pass existing classifier and independent label; no publisher title',async()=>{const i=await manualCandidate(sale(),now);assert.equal(i.category,'sale');assert.match(i.label,/10月11日/);assert.equal(i.productFacts.percentOff,25);assert.equal(i.saleEndsAt,Date.parse('2026-10-11T23:59:59.999+09:00'));assert.ok(!JSON.stringify(i).includes('headline'));});
for(const [name,changes]of Object.entries({coupon:{benefit:'coupon_only'},points:{benefit:'points_only'},shipping:{benefit:'shipping_only'},singleSKU:{scope:'single_sku'},shop:{scope:'shop'},unclear:{benefit:'unclear'},expired:{endDate:'2026-09-30'},invalidDate:{endDate:'2026-02-30'},future:{publishedAt:'2026-10-02'},missingEnd:{endDate:undefined},emptyScope:{equipment:[]},arbitraryBrand:{brands:['Injected copy']},unknownSeller:{seller:'Unknown'},unknownType:{saleType:'激安セール'},unknownBenefit:{percentOff:0}}))test('manual Sale rejects '+name,async()=>{await assert.rejects(manualCandidate({...sale(),...changes},now));});
for(const field of ['headline','title','body','excerpt','images','html'])test('manual prohibits retained '+field,async()=>{await assert.rejects(manualCandidate({...sale(),[field]:'forbidden'},now),/manual_field_forbidden/);});
test('manual field checks, canonical host, social and query injection fail closed',async()=>{for(const url of ['https://evil.example/','https://apu.software/?title=copy','https://apu.software/limiter/','https://x.com/intent/tweet'])await assert.rejects(manualCandidate({...sale(),officialUrl:url},now));await assert.rejects(manualCandidate({...sale(),checks:{...checks(),factsChecked:false}},now));await assert.rejects(manualCandidate({...sale(),articleChecks:{...article(),primarySource:'no_primary_found'}},now));});
test('manual Artist supports precise concert, interview, exhibition, relevance reason',async()=>{for(const eventType of ['concert','interview','exhibition']){const i=await manualCandidate({...artist(),eventType},now);assert.equal(i.category,eventType==='interview'?'artist_guitar':'live_guitar');assert.equal(i.productFacts.relevanceReason,'guitarist');assert.doesNotMatch(i.label,/に関する話題/);}});
test('manual Artist rejects generic/unknown event or relevance boolean',async()=>{for(const changes of [{eventType:'unknown'},{relevanceReason:true},{eventName:'ギターに関する話題'},{eventDate:'2026-02-30'},{venue:''}])await assert.rejects(manualCandidate({...artist(),...changes},now));});
test('manual sources cannot become automatic sources or borrow PB authorization',()=>{assert.equal(runtimeSources({NEWS_SOURCE_IDS:'["manual-ikebe"]'},undefined,now).some(s=>s.enabled),false);for(const s of MANUAL_SOURCES){assert.equal(s.automaticEnabled,false);assert.equal(manualEvidenceGate(s,now),null);assert.ok(manualEvidenceGate({...s},now));assert.ok(manualEvidenceGate(s,now+91*86400000));}});
test('manual create visible via real adapter; duplicate leaves same approved row and one audit',async()=>{const s=await dbStore(),i=await manualCandidate(sale(),now);assert.equal((await ingestManual(s,i,now)).inserted,true);assert.equal((await ingestManual(s,i,now+1)).inserted,false);const rows=await s.candidates();assert.equal(rows.length,1);assert.equal(rows[0].origin,'operator_manual_add');assert.equal(s.db.raw.prepare("SELECT count(*) n FROM news_admin_audit WHERE action='manual-add'").get().n,1);assert.equal((await(await api(s)).json()).items.length,1);});
test('manual Sale exact inclusive expiry is hidden from list/category/ticker ',async()=>{const s=await dbStore(),i=await manualCandidate({...sale(),endDate:'2026-10-01',endTime:'10:00'},now);await ingestManual(s,i,now);for(const path of ['/v1/news','/v1/news?category=sale','/v1/news/ticker']){assert.equal((await(await api(s,i.saleEndsAt,path)).json()).items.length,1);assert.equal((await(await api(s,i.saleEndsAt+1,path)).json()).items.length,0);}});
test('manual honors publication/collection OFF, source disable, takedown and immutable validation',async()=>{for(const action of ['publish-off','collection-off','source-disable']){const s=await dbStore(),i=await manualCandidate(sale(),now);await administer(s,{action,target:action==='source-disable'?i.sourceId:'global',reason:'operator_stop'},now,[{id:i.sourceId}]);assert.equal((await ingestManual(s,i,now)).inserted,false);}const s=await dbStore(),i=await manualCandidate(sale(),now);await s.db.prepare('INSERT INTO news_takedowns VALUES(?,?)').bind(i.id,now+86400000).run();assert.equal((await ingestManual(s,i,now)).inserted,false);i.label='unvalidated';await assert.rejects(ingestManual(s,i,now),/not_validated/);});
test('manual source STOP hides already published row; public mutation never exists',async()=>{const s=await dbStore(),i=await manualCandidate(sale(),now);await ingestManual(s,i,now);await s.db.prepare('INSERT INTO source_state(source_id,disabled) VALUES(?,1)').bind(i.sourceId).run();assert.equal((await(await api(s)).json()).items.length,0);assert.equal((await handleNewsRequest(new Request('https://news.example/manual-add',{method:'POST'}),{NEWS_DB:s.db,NEWS_API_MODE:'production'},now)).status,405);});
test('generic Artist cannot auto-publish; named guitarist alone requires event review',async()=>{const s=runtimeSources({NEWS_SOURCE_IDS:'["amass"]'},undefined,now).find(s=>s.id==='amass');const {item}=await candidateFrom({title:'リック・ニールセン、ギターの合成情報',date:'2026-09-30',url:'https://amass.jp/900000/'},s,{isAllowed:()=>true},now,pepper);assert.equal(item.publicationDecision,'PUBLISH_REVIEW');});
test('quality gate permits useful added category and preserves old labels',async()=>{const i=await manualCandidate(sale(),now),b=qualitySnapshot([],{now}),c=qualitySnapshot([i],{now});assert.equal(qualityRegressionGate(b,c).pass,true);assert.ok(c.categoriesCovered.includes('sale'));});
for(const [reason,mutate]of Object.entries({high_value_decreased:c=>c.counts['HIGH VALUE']--,useful_category_decreased:c=>c.categoriesCovered=[],noise_increased:c=>c.counts.NOISE++,generic_labels_increased:c=>c.genericLabels++,ticker_lead_low_value:c=>c.tickerTop5=[{quality:'LOW VALUE'}],review_burden_surge:c=>c.reviewBurden=30}))test('quality gate blocks '+reason,async()=>{const i=await manualCandidate(sale(),now),b=qualitySnapshot([i],{reviewBurden:10,now}),c=structuredClone(b);mutate(c);assert.ok(qualityRegressionGate(b,c).reasons.includes(reason));});
test('research URL strips query by default, allowlists numeric identity; social is forbidden',()=>{assert.equal(canonicalResearchUrl('https://example.com/news?id=3&utm_source=x#x'),'https://example.com/news');assert.equal(canonicalResearchUrl('https://example.com/news?id=3&utm_source=x',{queryKeys:['id']}),'https://example.com/news?id=3');for(const u of ['https://x.com/intent/tweet?text=copy','https://www.facebook.com/sharer.php?u=x','https://example.com/?title=copy','https://example.com/share/news'])assert.throws(()=>canonicalResearchUrl(u));});
test('research unknown/raw fields and normalized or near original copy fail before writing',async()=>{const title='Synthetic guitar collection released in autumn';for(const facts of [{policyFinding:title},{policyFinding:'SYNTHETIC GUITAR COLLECTION RELEASED IN AUTUMN!'},{policyFinding:'Synthetic guitar collection released in autumn today'}])assert.throws(()=>guardedResearchArtifact([{facts}],{originalTitles:[title]}),/headline_match/);assert.throws(()=>guardedResearchArtifact([{headline:title}]));const dir=await mkdtemp(join(tmpdir(),'news-guard-'));try{const path=join(dir,'evidence.json');await assert.rejects(writeResearchArtifact(path,[{facts:{policyFinding:title}}],{originalTitles:[title]}));await assert.rejects(readFile(path));assert.equal(await writeResearchArtifact(path,[{canonicalUrl:'https://example.com/',facts:{artist:'合成人物'},reasonCodes:['facts_verified']}],{originalTitles:[title]}),1);}finally{await rm(dir,{recursive:true});}});

test('research facts cannot hide nested raw content or original keys',()=>{for(const record of [{facts:{artist:{body:'hidden'}}},{counts:{'Synthetic original headline':1}},{status:700},{reasonCodes:'not-an-array'}])assert.throws(()=>guardedResearchArtifact([record]));});

test('manual evidence accepts the Oct1 JST morning before Oct1 UTC begins',async()=>{const morning=Date.parse('2026-09-30T21:00:00Z');assert.equal(manualEvidenceGate(MANUAL_SOURCES[1],morning),null);assert.equal((await manualCandidate(sale(),morning)).category,'sale');});

test('research normalized headline in a count key also fails before retaining',()=>{assert.throws(()=>guardedResearchArtifact([{counts:{syntheticguitarannouncement:1}}],{originalTitles:['Synthetic Guitar Announcement']}),/headline_match/);assert.throws(()=>guardedResearchArtifact([{timestamp:false}]));});
