import test from 'node:test';import assert from 'node:assert/strict';
import {getSource} from '../src/registry.js';import {parseShimamuraProductEvidence} from '../src/shimamura-product-evidence.js';import {parseIkebeProductEvidence} from '../src/ikebe-product-evidence.js';import {factualLabel} from '../src/metadata.js';
import {setup,put,now} from './operator-case.js';import {pepper} from './helpers.js';import {hash} from '../src/policy.js';import {reviewDetail} from '../src/operator-review.js';import {runPendingRechecks} from '../src/pending-lifecycle.js';
const shima=getSource('shimamura'),ikebe=getSource('ikebe'),date='2026-10-01T15:00:00.000Z';
const row=id=>({id:'a'.repeat(64),source_id:id,source_url:id==='shimamura'?'https://www.shimamura.co.jp/update/dtm-recording/2026/10/100001/':'https://www.ikebe-gakki-pb.com/new_product/100001/',published_at:date,review_status:'pending'});
// Reduced synthetic structures, not saved publisher bodies/headlines/images.
const sh=(brand='インターネット',family='VOCALOID7',variant='Megpoid')=>`<link rel="canonical" href="${row('shimamura').source_url}"><div class="mb-80"><h1>${family} ${variant} | 音声合成ソフトの新製品</h1></div><p>公開：<time datetime="2026-10-02"></time></p><div class="p-content"><p class="wp-block-paragraph">${brand}がボイスバンク「${family} Voicebank AI ${variant}」と「${family} Starter Pack AI ${variant}」を発売します。</p><h2>${family} Voicebank AI ${variant}</h2><p class="wp-block-paragraph">「${family} Voicebank AI ${variant}」は歌声を制作するソフトです。「${family} Starter Pack AI ${variant}」も用意されます。</p><div id="release-date"><h2>発売日</h2><p>2026年11月11日(水)</p></div></div>`;
const ik=(brand='Fryette',model='VALVULATOR MINI')=>`<link rel="canonical" href="${row('ikebe').source_url}"><article id="main"><div class="blog_title"><h1>演奏環境を整える新たな選択肢！${brand}の設計思想から生まれた高電圧真空管バッファー登場</h1><time class="sub_info_date" datetime="2026-10-02">2026年10月02日公開</time><li class="cate-effector"></li><a href="https://www.ikebe-gakki-pb.com/new_product/tag/synthetic/">${brand}</a></div><div class="main_wrap"><h2 class="wp-block-heading">${brand}<br>${model}</h2><p class="wp-block-paragraph">演奏環境を整える新たな選択肢を提供する</p><p class="wp-block-paragraph">${brand}の設計思想から生まれた高電圧真空管バッファー</p><p class="wp-block-paragraph">${model}はギター用の真空管バッファーです。</p><p class="wp-block-paragraph">ギターとアンプ、ペダルボードの間へ接続します。</p></div></article>`;
test('VOCALOID voicebank and starter pack: explicit Japanese manufacturer, two models, future release distinct from publication',()=>{const o=parseShimamuraProductEvidence(sh(),shima,row('shimamura'));assert.equal(o.productFacts.brand,'インターネット');assert.equal(o.productFacts.models.length,2);assert.equal(o.productFacts.productType,'voicebank');assert.equal(o.productFacts.category,'dtm_software');assert.equal(o.productFacts.releaseEvent.date,'2026-11-11');assert.equal(o.publishedAt,date);assert.match(factualLabel(o.productFacts,o.eventType),/音声合成ソフト.*11月11日に発売予定/);});
test('Japanese manufacturer / voicebank extraction is not tied to one brand or model',()=>{const o=parseShimamuraProductEvidence(sh('合成工房','SINGER9','Harmony'),shima,row('shimamura'));assert.equal(o.productFacts.brand,'合成工房');assert.deepEqual(o.productFacts.models,['SINGER9 Voicebank AI Harmony','SINGER9 Starter Pack AI Harmony']);});
test('Japanese identity needs explicit manufacturer subject, distinctive title and independent model corroboration',()=>{const h=sh();for(const bad of [h.replace('インターネットが','メーカー不明の'),h.replace('「VOCALOID7 Starter Pack AI Megpoid」も用意されます。','関連商品「VOCALOID7 Starter Pack AI Megpoid」も用意されます。'),h.replace('「VOCALOID7 Starter Pack AI Megpoid」も用意されます。','旧製品「VOCALOID7 Starter Pack AI Megpoid」も用意されます。'),h.replace('VOCALOID7 Megpoid |','別製品のご案内 |'),h.replace('「VOCALOID7 Starter Pack AI Megpoid」も用意されます。','仕様を確認してください。'),h.replace('<h2>VOCALOID7 Voicebank AI Megpoid</h2>','<h2>Other Voice</h2>').replace('「VOCALOID7 Voicebank AI Megpoid」は','「Other Voice」は')])assert.throws(()=>parseShimamuraProductEvidence(bad,shima,row('shimamura')),/facts_/);});
test('Fryette buffer is not a guitar amp inferred from its signal chain',()=>{const o=parseIkebeProductEvidence(ik(),ikebe,row('ikebe'));assert.equal(o.productFacts.productType,'signal_buffer');assert.equal(o.productFacts.category,'amps_effects');assert.equal(o.eventType,'new_product');assert.match(factualLabel(o.productFacts,o.eventType),/Fryette、バッファー「VALVULATOR MINI」を発表/);assert.equal(o.productFacts.releaseEvent,undefined);});
test('buffer and split descriptive lead recovery are generic',()=>{const o=parseIkebeProductEvidence(ik('Craft Lab','TUBE BUFFER 900'),ikebe,row('ikebe'));assert.equal(o.productFacts.brand,'Craft Lab');assert.equal(o.productFacts.product,'TUBE BUFFER 900');});
test('descriptive buffer requires matching manufacturer lead and model-bound type, not accessories or related lists',()=>{const h=ik();for(const bad of [h.replace('Fryetteの設計思想から生まれた高電圧真空管バッファー</p>','別製品の説明です。</p>'),h.replace('VALVULATOR MINIはギター用の真空管バッファーです。','Other 100は真空管バッファーです。'),h.replace('VALVULATOR MINIはギター用の真空管バッファーです。','VALVULATOR MINIの付属品は真空管バッファーです。'),h.replace('バッファー登場</h1>','バッファー再入荷</h1>'),h.replace('バッファー登場</h1>','バッファー比較レビュー</h1>'),h.replace('バッファー登場</h1>','バッファーセール</h1>'),h.replace('class="main_wrap"','class="main_wrap" hidden')])assert.throws(()=>parseIkebeProductEvidence(bad,ikebe,row('ikebe')),/facts_/);});
for(const [name,source,html]of [['voicebank',shima,sh()],['buffer',ikebe,ik()]])test('autonomous '+name+' recovery reaches READY without approval or human teacher writes',async()=>{const s=await setup(),r=row(source.id),robot='User-agent: *\nAllow: /',a={...source,enabled:true,productionEnabled:true,robotsHash:await hash(robot)};await s.recordHealth({sourceId:a.id,status:'healthy',reasonCode:'ok',checkedAt:now,successfulAt:now});await put(s,name,{id:r.id,sourceId:a.id,sourceName:a.name,sourceUrl:r.source_url,normalizedUrl:r.source_url,publishedAt:date,productFacts:null,eventType:'other'});await s.db.prepare('INSERT INTO source_state(source_id,last_discovery_at,robots_hash) VALUES(?,?,?)').bind(a.id,now,a.robotsHash).run();const report=await runPendingRechecks(s,now,[a],pepper,{sleep:async()=>{},fetcher:async u=>new Response(u===a.robotsUrl?robot:html,{headers:{'Content-Type':u===a.robotsUrl?'text/plain':'text/html'}})});assert.equal(report.newlyReady,1,JSON.stringify(report));const d=await reviewDetail(s,r.id,now,[a],pepper);assert.equal(d.validation.valid,true);assert.equal(d.factsReview.reviewability,'READY_FOR_HUMAN_DECISION');assert.equal(d.status,'pending');for(const t of ['news_decision_ledger','news_operator_feedback'])assert.equal((await s.db.prepare('SELECT COUNT(*) n FROM '+t).first()).n,0);assert.equal((await s.db.prepare('SELECT * FROM news_pending_lifecycle WHERE candidate_id=?').bind(r.id).first()).recheck_status,'RECOVERED_READY');});
