// Synthetic evidence only. No publisher text, passcodes, images or saved HTML.
import test from 'node:test';import assert from 'node:assert/strict';
import {parseOfficialIdentity,sourceIdentityContext,resolveOfficialIdentity,identityAuthority,validOfficialIdentity,recoverOfficialIdentity} from '../src/official-identity.js';
import {parseShimamuraProductEvidence} from '../src/shimamura-product-evidence.js';
import {getSource} from '../src/registry.js';import {hash} from '../src/policy.js';import {factualLabel} from '../src/metadata.js';import {validHeadlineEvidence} from '../src/headline-evidence.js';
import {setup,put,now} from './operator-case.js';import {pepper} from './helpers.js';import {candidateSnapshot,reviewDetail} from '../src/operator-review.js';import {recheckFacts} from '../src/facts-recheck.js';import {preparePendingResolution,applyPendingResolution} from '../src/pending-resolution.js';
const officialUrl='https://h-resolution.com/product/synthetic-ax20/',sourceUrl='https://www.shimamura.co.jp/update/dtm-recording/2026/10/100002/',source=getSource('shimamura');
const row={id:'c'.repeat(64),source_id:'shimamura',source_url:sourceUrl,published_at:'2026-10-01T15:00:00.000Z',review_status:'pending'};
const official=(product='AX20',brand='MOTU',extra='')=>`<link rel="canonical" href="${officialUrl}"><script type="application/ld+json">${JSON.stringify({'@type':'Product',name:product,brand:{name:brand},url:officialUrl})}</script><section><div><h1>${product}</h1><h2>${product}</h2><h3>USBオーディオインターフェース</h3><p>2026年10月下旬発売予定</p>${extra}</div></section>`;
const primary=(lead='MOTがオーディオインターフェース「AX2O」を発売します。',body='MOTU AX20はUSBオーディオインターフェースです。',extra='')=>`<link rel="canonical" href="${sourceUrl}"><div class="mb-80"><h1>MOTU「AX2O」を発表</h1></div><p>公開：<time datetime="2026-10-02"></time></p><div class="p-content"><p class="wp-block-paragraph">${lead}</p><p class="wp-block-paragraph">${body}</p><p class="wp-block-paragraph">AX20は録音用の新製品です。</p>${extra}</div>`;
const evidence=(html=official())=>({...parseOfficialIdentity(html,officialUrl,now),responseHash:'a'.repeat(64)});
const resolution=(html=primary(),proof=[evidence()])=>resolveOfficialIdentity(sourceIdentityContext(html),proof,sourceUrl);
test('title/model/brand typo resolves only from exact registered official identity and repeated subject-body matches',()=>{const h=primary(),e=resolution(h),out=parseShimamuraProductEvidence(h,source,row,{officialIdentity:e});assert.equal(out.productFacts.brand,'MOTU');assert.equal(out.productFacts.product,'AX20');assert.equal(out.productFacts.productType,'audio_interface');assert.deepEqual(e.previousValues,{brands:['MOT'],models:['AX2O']});assert(validOfficialIdentity(e,sourceUrl,'MOTU','AX20'));assert.equal(out.publishedAt,row.published_at);assert.equal(factualLabel(out.productFacts,out.eventType),'MOTU、オーディオインターフェース「AX20」を10月下旬に発売予定');assert(!JSON.stringify(out).includes('USBオーディオインターフェースです'));assert(!JSON.stringify(out).includes('h1'));});
test('no official evidence, conflicting official identities or wrong source binding stays held',()=>{assert.throws(()=>resolution(primary(),[]),/facts_official_identity_missing/);assert.throws(()=>resolution(primary(),[evidence(),{...evidence(),product:'AX21'}]),/facts_official_identity_conflict/);assert.throws(()=>parseShimamuraProductEvidence(primary(),source,row,{officialIdentity:{...resolution(),sourceUrl:sourceUrl+'bad'}}),/facts_identity_changed/);assert.throws(()=>parseShimamuraProductEvidence(primary(),source,row),/facts_identity_changed/);});
test('registered manufacturer, distributor, then official press priority does not mask conflicts',()=>{const e=evidence(),a={...e,authorityType:'official_manufacturer_product'},b={...e,authorityType:'official_manufacturer_press'};assert.equal(resolution(primary(),[b,e,a]).authorityType,'official_manufacturer_product');assert.throws(()=>resolution(primary(),[e,{...a,brand:'Other'}]),/facts_official_identity_conflict/);});
test('generic model identity has no target-product rule',()=>{for(const m of ['BX-700','Field Pro 30','C42']){const h=primary('MOTがオーディオインターフェース「Typo X」を発売します。',`MOTU ${m}はUSBオーディオインターフェースです。`).replace('AX20は録音',m+'は録音'),e=resolution(h,[evidence(official(m))]);assert.equal(parseShimamuraProductEvidence(h,source,row,{officialIdentity:e}).productFacts.product,m);}});
for(const [name,h]of [
 ['brand alone',primary(undefined,'MOTUはメーカーです。')],
 ['related product',primary(undefined,'別の新製品です。','<aside><p class="wp-block-paragraph">MOTU AX20はUSB機材です。</p></aside>')],
 ['hidden body',primary(undefined,'<span hidden>MOTU AX20はUSB機材です。</span>')],
 ['accessory',primary(undefined,'MOTU AX20対応機種向けの付属品です。')],
 ['comparison',primary(undefined,'MOTU AX20の比較レビューです。')],
 ['restock',primary('MOTが「AX2O」を再入荷します。')],
 ['sale',primary('MOTが「AX2O」のセールを発表します。')],
 ['old product',primary(undefined,'以前のMOTU AX20はUSB機材です。')],
 ['multi model ambiguity',primary('MOTが「AX2O」と「Other20」を発売します。')]
])test('official identity never borrows '+name,()=>assert.throws(()=>resolution(h),/facts_/));
test('official structured identity requires registered canonical product surface, visible exact name and brand',()=>{for(const url of ['http://h-resolution.com/product/a/','https://h-resolution.com.evil.test/product/a/','https://127.0.0.1/product/a/','https://h-resolution.com/product/a/?q=x','https://h-resolution.com/product/a/#x','https://h-resolution.com/news/a/','https://user@h-resolution.com/product/a/'])assert.equal(identityAuthority(url),null);for(const h of [official().replace('MOTU','Other'),official().replace('<h1>AX20</h1>','<h1>Other AX20</h1>'),official().replace('<h1>AX20</h1>','<h1 hidden>AX20</h1>'),official().replace('rel="canonical"','rel="alternate"'),'<meta name="robots" content="noarchive">'+official()])assert.throws(()=>evidence(h),/facts_/);});
test('release period is explicit, never an inferred exact day or offer price',()=>{const e=evidence(official('AX20','MOTU','<p>価格100円、在庫あり</p>'));assert.deepEqual(e.releasePeriod,{year:2026,month:10,part:'late'});assert.equal(e.date,undefined);for(const period of [{year:2026,month:13,part:'late'},{year:2026,month:10,part:'tomorrow'},{year:2026,month:10,part:'late',date:1}])assert(!validHeadlineEvidence({releaseEvent:{action:'scheduled_release',basis:'verified_primary_article',period}}));assert(!validHeadlineEvidence({releaseEvent:{action:'scheduled_release',basis:'verified_primary_article',period:e.releasePeriod,date:'2026-10-20'}}));});
async function recoveryCase({duplicate=false,valid=false}={}){const s=await setup(),robot='User-agent: *\nAllow: /',a={...source,enabled:true,productionEnabled:true,robotsHash:await hash(robot)};await put(s,'official-test',{id:row.id,sourceUrl,normalizedUrl:sourceUrl,publishedAt:row.published_at,productFacts:valid?{brand:'SHURE',product:'MV6',category:'recording_audio',version:null,identifierBasis:'explicit_model_code'}:null,eventType:valid?'new_product':'other'});await s.db.prepare('INSERT INTO source_state(last_discovery_at,source_id) VALUES(?,?) ON CONFLICT(source_id) DO UPDATE SET last_discovery_at=excluded.last_discovery_at').bind(now,'shimamura').run();if(duplicate){const other=await put(s,'approved-other',{productFacts:{brand:'MOTU',product:'AX20',models:['AX20'],version:null,category:'recording_audio'},category:'recording_audio'});await s.db.prepare("UPDATE candidate_items SET review_status='approved' WHERE id=?").bind(other.id).run();}
 const officialProof=evidence();await s.db.prepare("INSERT INTO news_facts_sources(source_id,lease_token,lease_until,checked_at,outcome,items_json) VALUES(?, 'fixture',0,?,'verified_official_identity',?)").bind('official-identity:https://h-resolution.com',now,JSON.stringify([officialProof])).run();await s.db.prepare("INSERT INTO news_facts_sources(source_id,lease_token,lease_until,checked_at,outcome,items_json) VALUES(?,'fixture',0,?,'reviewed_hint',?)").bind('official-identity-hint:'+row.id,now,JSON.stringify([{candidateId:row.id,sourceUrl,officialUrl}])).run();const saved=await s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(row.id).first();let calls=0;
 const run=async()=>recheckFacts(s,{id:row.id,revision:saved.review_revision,snapshot:await candidateSnapshot(saved),requestId:crypto.randomUUID()},now,[a],pepper,{type:'system_recheck',id:'identity-test'},{sleep:async()=>{},fetcher:async u=>{calls++;assert([a.robotsUrl,sourceUrl].includes(u));return new Response(u===a.robotsUrl?robot:primary(),{headers:{'Content-Type':'text/html'}});}});
 return {s,a,saved,run,calls:()=>calls};}
test('autonomous recovery persists bounded official provenance, stays pending, and is not a human teacher',async()=>{const c=await recoveryCase(),r=await c.run();assert(r.recovered,JSON.stringify(r));assert(r.validation.valid,JSON.stringify(r));assert.equal(c.calls(),2);const d=await reviewDetail(c.s,row.id,now,[c.a],pepper);assert.equal(d.factsReview.reviewability,'READY_FOR_HUMAN_DECISION');assert.equal(d.facts.officialIdentity.resolved_by,'official_identity_recovery');const after=await c.s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(row.id).first();assert.equal(after.review_status,'pending');assert.equal(after.published_at,c.saved.published_at);assert.equal(after.title_fingerprint,c.saved.title_fingerprint);assert(JSON.parse(after.facts_provenance).some(p=>p.factField==='officialIdentity'));for(const t of ['news_decision_ledger','news_operator_feedback'])assert.equal((await c.s.db.prepare('SELECT COUNT(*) n FROM '+t).first()).n,0);});
test('official recovery preserves duplicate validation and objective system termination',async()=>{const c=await recoveryCase({duplicate:true}),r=await c.run();assert(r.recovered,JSON.stringify(r));assert(r.validation.errors.includes('duplicate'));const saved=await c.s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(row.id).first(),plan=await preparePendingResolution(c.s,{id:row.id,snapshot:await candidateSnapshot(saved),requestId:crypto.randomUUID()},now,[c.a],pepper);assert.equal(plan.actor,'system_policy');assert.equal(plan.reason,'duplicate');await applyPendingResolution(c.s,plan);const after=await c.s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(row.id).first();assert.equal(after.review_reason,'duplicate');assert.equal(after.reviewed_by,'system_policy');assert.equal((await c.s.db.prepare('SELECT * FROM news_pending_lifecycle WHERE candidate_id=?').bind(row.id).first()).next_recheck_at,null);assert.equal((await c.s.db.prepare("SELECT COUNT(*) n FROM candidate_items WHERE review_status='approved'").first()).n,1);for(const t of ['news_decision_ledger','news_operator_feedback'])assert.equal((await c.s.db.prepare('SELECT COUNT(*) n FROM '+t).first()).n,0);});
test('already identity-valid candidate is unchanged and performs no official/source fetch',async()=>{const c=await recoveryCase({valid:true}),r=await c.run();assert.equal(r.outcome,'facts_already_complete');assert.equal(c.calls(),0);assert.equal((await c.s.db.prepare('SELECT product_facts FROM candidate_items WHERE id=?').bind(row.id).first()).product_facts,c.saved.product_facts);});
test('unregistered hint does not fetch and cache budget failure remains held',async()=>{const s=await setup();let calls=0;await assert.rejects(recoverOfficialIdentity(s,primary(),row,now,{fetcher:()=>{calls++;throw Error('no fetch');}}),/facts_official_identity_missing/);assert.equal(calls,0);await s.db.prepare("INSERT INTO news_facts_sources(source_id,lease_token,checked_at,outcome,items_json) VALUES(?, 'fixture',?,'failed','[]')").bind('official-identity:https://h-resolution.com',now).run();await s.db.prepare("INSERT INTO news_facts_sources(source_id,lease_token,checked_at,outcome,items_json) VALUES(?,'fixture',?,'reviewed_hint',?)").bind('official-identity-hint:'+row.id,now,JSON.stringify([{candidateId:row.id,sourceUrl,officialUrl}])).run();await assert.rejects(recoverOfficialIdentity(s,primary(),row,now,{fetcher:()=>{calls++;throw Error('no fetch');}}),/facts_official_daily_budget/);assert.equal(calls,0);});
test('official recovery fails closed on changed robots or redirects without saving publisher prose',async()=>{for(const redirect of [false,true]){const s=await setup();await s.db.prepare("INSERT INTO news_facts_sources(source_id,lease_token,checked_at,outcome,items_json) VALUES(?,'fixture',?,'reviewed_hint',?)").bind('official-identity-hint:'+row.id,now,JSON.stringify([{candidateId:row.id,sourceUrl,officialUrl}])).run();let calls=0;await assert.rejects(recoverOfficialIdentity(s,primary(),row,now,{sleep:async()=>{},fetcher:async()=>{calls++;return redirect?new Response('',{status:302,headers:{Location:'https://unregistered.example/'}}):new Response('User-agent: *\nDisallow: /product/');}}));assert.equal(calls,1);const cached=await s.db.prepare('SELECT * FROM news_facts_sources WHERE source_id=?').bind('official-identity:https://h-resolution.com').first();assert.equal(cached.lease_until,0);assert.equal(cached.items_json,'[]');assert(!JSON.stringify(cached).includes('User-agent'));}});
test('official absence/conflict diagnostics remain a genuine hold',async()=>{const {recoveryAssessment}=await import('../src/facts-readiness.js');for(const outcome of ['facts_official_identity_missing','facts_official_identity_conflict'])assert.equal(recoveryAssessment(row,{valid:false,errors:['facts_incomplete'],facts:null},{method:'explicit_shimamura_product_fields'},{outcome},null).recoveryClass,'NOT_SAFELY_RECOVERABLE');});
test('a recovered identity without source-bound provenance cannot be approved',async()=>{const c=await recoveryCase();assert((await c.run()).recovered);await c.s.db.prepare('UPDATE candidate_items SET facts_provenance=? WHERE id=?').bind('[]',row.id).run();const d=await reviewDetail(c.s,row.id,now,[c.a],pepper);assert(!d.validation.valid);assert(d.validation.errors.includes('facts_provenance_invalid'));});
