import test from 'node:test';import assert from 'node:assert/strict';
import {decisionProfile,evaluateDecisions,similarity,similarDecisions,dashboardSummary,humanDecisionHistory,policyCompatibility,MINIMUM_EVIDENCE} from '../src/operator-insights.js';
import {DECISION_POLICY_VERSION,publicationValidation} from '../src/decision-policy.js';
import {operatorDecision} from '../src/operator-review.js';
import {setup,put,approveInput,source,now} from './operator-case.js';import {pepper} from './helpers.js';
const validation={valid:true,errors:[]};
const candidate={id:'pending',source_id:'shimamura',source_url:'https://www.shimamura.co.jp/update/dtm-recording/2026/10/12345/',category:'recording_audio',event_type:'new_product',published_at:'2026-10-01T00:00:00Z',decision_reason:'label_required',review_reason:'label_required',product_facts:JSON.stringify({brand:'DO NOT RETAIN',product:'DO NOT RETAIN',category:'recording_audio',identifierBasis:'explicit_model_code'})};
const profile=decisionProfile(candidate,validation,now);
function teacher(id,extra={}){return {decision_id:'d'+id,candidate_id:'c'+id,verdict:'approve',reason:'useful_product',actor_type:'human_operator',decided_at:now-1000,created_at:now-1000,source_id:'shimamura',category:'recording_audio',success_state:'committed',policy_version:DECISION_POLICY_VERSION,decision_features_json:JSON.stringify({insightsProfile:profile}),...extra};}
const evaluate=rows=>evaluateDecisions(profile,rows,{now,candidateId:candidate.id,validation});
test('structured similarity exact, strong, weak and insufficient have explained signals; fact values never retained',()=>{assert.equal(similarity(profile,profile).level,'EXACT_PATTERN');assert.equal(similarity(profile,{...profile,freshness:'within_14_days'}).level,'STRONG_SIMILAR');assert.equal(similarity(profile,{...profile,factShape:[],factsVerified:false}).level,'WEAK_SIMILAR');assert.equal(similarity(profile,{...profile,category:'acoustic_guitar',source:'other',type:'other'}).level,'INSUFFICIENT');assert(!JSON.stringify(profile).includes('DO NOT RETAIN'));assert(!JSON.stringify(decisionProfile({...candidate,source_url:'https://www.example.com/news/PRIVATE_PRODUCT_NAME'},validation,now)).includes('PRIVATE_PRODUCT_NAME'));});
test('one or two human decisions never recommend; five independent current-policy decisions meet threshold',()=>{assert.equal(MINIMUM_EVIDENCE,5);for(const n of [0,1,2,4])assert.equal(evaluate(Array.from({length:n},(_,i)=>teacher(i))).recommendation,'NO_RECOMMENDATION');assert.equal(evaluate(Array.from({length:5},(_,i)=>teacher(i))).recommendation,'RECOMMEND_APPROVE');assert.equal(evaluate(Array.from({length:5},(_,i)=>teacher(i,{verdict:'reject'}))).recommendation,'RECOMMEND_REJECT');});
test('all nonhuman actors, failed/future/expired/self decisions are excluded; retries and revisions are not independent cases',()=>{const rows=['automatic_policy','migration','fixture','system_repair','facts_recovery'].map((actor_type,i)=>teacher(i,{actor_type}));rows.push(teacher('bad',{success_state:'failed'}),teacher('future',{decided_at:now+1}),teacher('expired',{created_at:now-366*86400000}),teacher('self',{candidate_id:'pending'}));assert.equal(evaluate(rows).matchedDecisionCount,0);assert.equal(evaluate(Array.from({length:6},(_,i)=>teacher(i,{candidate_id:'same'}))).evidenceCount,1);});
test('contradiction, even weak current-policy history, suppresses recommendation',()=>{const rows=Array.from({length:5},(_,i)=>teacher(i));rows.push(teacher('reject',{verdict:'reject',decision_features_json:JSON.stringify({insightsProfile:{...profile,factShape:[],factsVerified:false}})}));const result=evaluate(rows);assert.equal(result.contradictionCount,1);assert.equal(result.recommendation,'NO_RECOMMENDATION');assert.equal(result.reasonSummary,'contradictory_history');});
test('obsolete policy stays visible but cannot meet threshold; current policy is explicit; legacy coarse decisions never strong',()=>{assert.equal(policyCompatibility(DECISION_POLICY_VERSION),'SAME');assert.equal(policyCompatibility('unknown-old'),'OBSOLETE');const result=evaluate(Array.from({length:5},(_,i)=>teacher(i,{policy_version:'unknown-old'})));assert.equal(result.policyCounts.OBSOLETE,5);assert.equal(result.evidenceCount,0);assert.equal(result.recommendation,'NO_RECOMMENDATION');const legacy=evaluate([teacher('legacy',{decision_features_json:JSON.stringify({eventType:'new_product',factsPresent:true})})]);assert.equal(legacy.similarityLevel,'WEAK_SIMILAR');assert.equal(legacy.evidenceCount,0);});
test('merged user category matches creator raw key; validation-blocked candidate never gets approve recommendation',()=>{assert.equal(decisionProfile({...candidate,category:'creator_streaming'},validation,now).category,profile.category);const result=evaluateDecisions(profile,Array.from({length:5},(_,i)=>teacher(i)),{now,validation:{valid:false}});assert.equal(result.recommendation,'NO_RECOMMENDATION');assert.equal(result.reasonSummary,'publication_blocked');});
test('dashboard SQL counts all statuses and committed humans; history is bounded, human-only and PII/label-free; reads do not mutate',async()=>{const s=await setup(),item=await put(s);await operatorDecision(s,await approveInput(s,item),now,[source],pepper,{type:'human_operator',id:'access:fixture-human'});await put(s,'pending');const rejected=await put(s,'rejected');await operatorDecision(s,await approveInput(s,rejected,{action:'reject',reason:'not_relevant',label:undefined,category:undefined,publishedAt:undefined,checks:undefined}),now,[source],pepper,{type:'fixture',id:'fixture'});const before=JSON.stringify(s.db.raw.prepare('SELECT * FROM candidate_items').all());const summary=await dashboardSummary(s,now);assert.deepEqual([summary.published,summary.pending,summary.rejected,summary.humanDecisions],[1,1,1,1]);const history=await humanDecisionHistory(s,now);assert.equal(history.items.length,1);assert.equal(history.items[0].candidate_id,item.id);assert(!/actor_id|persisted_label|request_payload_hash/.test(JSON.stringify(history)));const row=await s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind('pending').first();await similarDecisions(s,row,validation,now);assert.equal(JSON.stringify(s.db.raw.prepare('SELECT * FROM candidate_items').all()),before);});
test('human decision stores coarse profile and shadow evaluation atomically; future comparison does not affect verdict',async()=>{const s=await setup(),item=await put(s);await operatorDecision(s,await approveInput(s,item),now,[source],pepper,{type:'human_operator',id:'access:fixture-human'});const d=await s.db.prepare('SELECT * FROM news_decision_ledger').first(),f=JSON.parse(d.decision_features_json);assert.equal(f.shadowEvaluation.recommendation,'NO_RECOMMENDATION');assert.equal(f.shadowEvaluation.operatorFinalVerdict,'approve');assert.equal(f.shadowEvaluation.candidateRevision,d.candidate_revision);assert.equal(f.insightsProfile.factsVerified,true);assert.equal(d.success_state,'committed');assert(!d.decision_features_json.includes('MV6'));});

test('different record IDs for the same article or topic are not independent evidence',()=>{
 for(const key of ['articleIdentity','topicIdentity']){const rows=Array.from({length:5},(_,i)=>teacher(i,{decision_features_json:JSON.stringify({insightsProfile:{...profile,[key]:'same-hashed-identity'}})}));const result=evaluate(rows);assert.equal(result.evidenceCount,1);assert.equal(result.recommendation,'NO_RECOMMENDATION');}
});
