import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {DatabaseSync} from 'node:sqlite';
import {store,pepper} from './helpers.js';import {fixtureActor,decisionInput} from './operator-fixtures.js';import {getSource} from '../src/registry.js';import {administer} from '../src/admin.js';import {fingerprint} from '../src/fingerprint.js';import {factualLabel} from '../src/metadata.js';import {operatorDecision,reviewDetail,purgeDecisionLedger} from '../src/operator-review.js';import {publicationValidation} from '../src/decision-policy.js';import {backfillLegacy} from '../src/legacy.js';
import {now,source,setup,put,approveInput} from './operator-case.js';
const decide=(s,i,r=[source])=>operatorDecision(s,i,now,r,pepper,fixtureActor);
const count=(s,table)=>s.db.raw.prepare(`SELECT COUNT(*) n FROM ${table}`).get().n;
const reviewCount=s=>s.db.raw.prepare("SELECT COUNT(*) n FROM news_admin_audit WHERE action LIKE 'review-%'").get().n;
async function clean(s,id){assert.equal((await s.db.prepare('SELECT review_status FROM candidate_items WHERE id=?').bind(id).first()).review_status,'pending');assert.equal(count(s,'news_decision_ledger'),0);assert.equal(count(s,'news_operator_feedback'),0);assert.equal(reviewCount(s),0);}
test('label repair persists verified factual label, coarse features and fixture attribution atomically',async()=>{const s=await setup(),item=await put(s),input=await approveInput(s,item);const result=await decide(s,input),row=(await s.candidates())[0];assert.equal(row.label,input.label);assert.equal(row.review_status,'approved');assert.equal(row.review_revision,1);assert.equal(row.article_checks,null);assert.equal(count(s,'news_decision_ledger'),1);assert.equal(count(s,'news_operator_feedback'),1);assert.equal(reviewCount(s),1);const ledger=await s.db.prepare('SELECT * FROM news_decision_ledger').first();assert.equal(ledger.actor_type,'fixture');assert(!ledger.decision_features_json.includes('MV6'));assert(!ledger.decision_features_json.includes('SHURE'));assert.equal((await reviewDetail(s,item.id,now,[source],pepper)).history[0].decision_id,result.decisionId);});
for(const action of ['approve','reject'])test(`concurrent ${action}: exactly one winner, loser cannot write audit/history/feedback`,async()=>{const s=await setup(),item=await put(s),base=action==='approve'?await approveInput(s,item):await decisionInput(s,{id:item.id,action:'reject',reason:'duplicate'});const results=await Promise.allSettled([decide(s,base),decide(s,{...base,requestId:crypto.randomUUID()})]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.match(results.find(x=>x.status==='rejected').reason.message,/stale_decision|already_decided/);assert.equal(count(s,'news_decision_ledger'),1);assert.equal(count(s,'news_operator_feedback'),1);assert.equal(reviewCount(s),1);});
test('concurrent approve versus reject shares the same CAS and yields one result',async()=>{const s=await setup(),item=await put(s),input=await approveInput(s,item);const outcomes=await Promise.allSettled([decide(s,input),decide(s,await decisionInput(s,{id:item.id,action:'reject',reason:'not_relevant'}))]);assert.equal(outcomes.filter(x=>x.status==='fulfilled').length,1);assert.equal(count(s,'news_decision_ledger'),1);assert.equal(reviewCount(s),1);});
test('doubleclick, network retry, browser-back replay: identical result, exactly one durable decision',async()=>{const s=await setup(),item=await put(s),input=await approveInput(s,item);const [a,b]=await Promise.all([decide(s,input),decide(s,input)]);assert.deepEqual(a,b);assert.deepEqual(await decide(s,input),a);assert.deepEqual(await decide(s,JSON.parse(JSON.stringify(input))),a);assert.equal(count(s,'news_decision_ledger'),1);assert.equal(reviewCount(s),1);await assert.rejects(decide(s,{...input,reason:'operator_review'}),/idempotency_payload_changed/);});
test('commit followed by uncertain transport failure is recovered from durable request ID',async()=>{const s=await setup(),item=await put(s),input=await approveInput(s,item),prepare=s.db.prepare;s.db.prepare=sql=>{const statement=prepare(sql);if(!sql.startsWith('INSERT INTO news_decision_ledger'))return statement;return {bind:(...args)=>{const bound=statement.bind(...args);return {run:async()=>{await bound.run();throw Error('synthetic_timeout_after_commit');}};}};};const result=await decide(s,input);assert.equal(result.action,'approve');assert.deepEqual(await decide(s,input),result);assert.equal(count(s,'news_decision_ledger'),1);});
test('feedback write failure rolls back candidate, ledger, audit and revision',async()=>{const s=await setup(),item=await put(s),input=await approveInput(s,item),revision=(await s.controls()).revision;s.db.raw.exec("CREATE TRIGGER feedback_failure BEFORE INSERT ON news_operator_feedback BEGIN SELECT RAISE(ABORT,'synthetic_feedback_failure'); END;");await assert.rejects(decide(s,input),/decision_transaction_failed/);await clean(s,item.id);assert.equal((await s.controls()).revision,revision);});
test('candidate changed before submit is rejected by snapshot/revision',async()=>{const s=await setup(),item=await put(s),input=await approveInput(s,item);await s.db.prepare("UPDATE candidate_items SET label='別の保留label' WHERE id=?").bind(item.id).run();await assert.rejects(decide(s,input),/candidate_changed/);await clean(s,item.id);});
test('candidate changed after validation cannot produce a false successful ledger',async()=>{const s=await setup(),item=await put(s),input=await approveInput(s,item),prepare=s.db.prepare;s.db.prepare=sql=>{const stmt=prepare(sql);if(!sql.startsWith('INSERT INTO news_decision_ledger'))return stmt;return {bind:(...args)=>{const bound=stmt.bind(...args);return {run:async()=>{s.db.raw.exec("UPDATE candidate_items SET label='変更された保留label' WHERE id='test-one'");return bound.run();}};}};};await assert.rejects(decide(s,input),/stale_decision/);await clean(s,item.id);});
test('publication gate closing after validation cannot create audit or history',async()=>{const s=await setup(),item=await put(s),input=await approveInput(s,item),prepare=s.db.prepare;s.db.prepare=sql=>{const stmt=prepare(sql);if(!sql.startsWith('INSERT INTO news_decision_ledger'))return stmt;return {bind:(...args)=>{const bound=stmt.bind(...args);return {run:async()=>{s.db.raw.exec('UPDATE news_controls SET publication_enabled=0 WHERE id=1');return bound.run();}};}};};await assert.rejects(decide(s,input),/operator_source_gate/);await clean(s,item.id);});
for(const [name,sql,error]of [
 ['publication rejected',"publication_decision='REJECT'",'publication_policy_rejected'],['no facts',"product_facts=NULL",'facts_incomplete'],['uncertain facts',"product_facts=json_set(product_facts,'$.scopeUncertain',1)",'facts_incomplete'],['other event',"event_type='other'",'facts_incomplete'],['category mismatch',"category='sale'",'facts_incomplete'],['invalid category',"category='invalid'",'facts_incomplete'],['bad fingerprint',"title_fingerprint=NULL",'label_provenance_invalid'],['future date',"published_at='2027-01-01T00:00:00.000Z'",'expired_candidate'],['old date',"published_at='2026-01-01T00:00:00.000Z'",'expired_candidate'],['expired',`expires_at=${now-1}`,'expired_candidate'],['unsafe URL',"source_url='javascript:alert(1)'",'source_url_invalid'],['bad path',"source_url='https://www.shimamura.co.jp/shops/test/'",'source_url_invalid'],['wrong source provenance',"product_facts=json_set(product_facts,'$.manufacturerSource','zoom')",'facts_provenance_invalid']])test(`publication validation rejects ${name}`,async()=>{const s=await setup(),item=await put(s);s.db.raw.exec(`UPDATE candidate_items SET ${sql}`);const input=await approveInput(s,item);await assert.rejects(decide(s,input),new RegExp(error));await clean(s,item.id);});
for(const [name,sql]of [['source stopped',"INSERT INTO source_state(source_id,disabled) VALUES('shimamura',1)"],['publication blocked',"INSERT INTO source_state(source_id,publication_blocked) VALUES('shimamura',1)"],['unhealthy',"UPDATE source_health SET status='error'"],['no publication',"UPDATE news_controls SET publication_enabled=0"],['no successful discovery',"UPDATE source_health SET last_successful_run_at=NULL"]])test(`source gate rejects ${name}`,async()=>{const s=await setup(),item=await put(s);s.db.raw.exec(sql);await assert.rejects(decide(s,await approveInput(s,item)),/operator_source_gate/);await clean(s,item.id);});
test('policy evidence expired or source disabled cannot be overridden by checks',async()=>{for(const changed of [{enabled:false},{reviewedAt:'2025-01-01'}]){const s=await setup(),item=await put(s);await assert.rejects(decide(s,await approveInput(s,item),[{...source,...changed}]),/operator_source_gate/);await clean(s,item.id);}});
test('reject cannot withdraw an approved candidate and rejects wrong verdict reason',async()=>{const s=await setup(),item=await put(s);await decide(s,await approveInput(s,item));await assert.rejects(decide(s,await decisionInput(s,{id:item.id,action:'reject',reason:'duplicate'})),/already_decided/);const x=await setup(),other=await put(x);await assert.rejects(decide(x,await approveInput(x,other,{reason:'not_relevant'})),/operator_decision_invalid/);});
test('same product different topics is blocked; update/version remains a separate story',async()=>{const s=await setup(),one=await put(s,'first'),two=await put(s,'second');await decide(s,await approveInput(s,one));await assert.rejects(decide(s,await approveInput(s,two)),/duplicate/);const updated=await put(s,'versioned',{productFacts:{...one.productFacts,version:'1.0.1'},eventType:'update'});await decide(s,await approveInput(s,updated));assert.equal(count(s,'news_decision_ledger'),2);});
test('topic duplicate blocks LAVA STUDIO even when source/facts differ',async()=>{const s=await setup(),one=await put(s,'published'),two=await put(s,'lava',{topicKey:one.topicKey});await decide(s,await approveInput(s,one));const detail=await reviewDetail(s,two.id,now,[source],pepper);assert.equal(detail.validation.duplicates[0].id,one.id);assert.equal(detail.validation.duplicates[0].source_name,source.name);await assert.rejects(decide(s,await approveInput(s,two)),/duplicate/);});
test('previous independent article remains protected through manual decision',async()=>{const s=await setup();await backfillLegacy(s,now);const facts={brand:'Fender',product:'Limited Edition Player Fusion',version:null,category:'electric_guitar_bass',identifierBasis:'reviewed_listing_model',listingSource:'ikebe'},ikebe={...getSource('ikebe'),enabled:true,productionEnabled:true};await s.recordHealth({sourceId:'ikebe',status:'healthy',reasonCode:'ok',checkedAt:now,successfulAt:now});const item=await put(s,'fender',{sourceId:'ikebe',sourceName:ikebe.name,sourceUrl:'https://www.ikebe-gakki-pb.com/new_product/199990/',normalizedUrl:'https://www.ikebe-gakki-pb.com/new_product/199990/',productFacts:facts,category:facts.category,eventType:'new_product',publishedAt:'2026-09-20T00:00:00.000Z'});const detail=await reviewDetail(s,item.id,now,[ikebe],pepper);assert(detail.validation.duplicates.some(x=>x.label.includes('Fender')));await assert.rejects(decide(s,await approveInput(s,item),[ikebe]),/duplicate/);});
test('expired/mismatched sale and unknown event dates cannot be force-approved',async()=>{const s=await setup(),item=await put(s);for(const facts of [{kind:'sale',category:'sale',seller:source.name,event:'期間限定セール',scope:'broad',nature:'sale',equipment:['ギター'],endDate:'2026-10-01'},{kind:'guitar_event',category:'live_guitar',event:'ギターリサイタル',evidence:'explicit_guitar_recital',action:'information'}]){s.db.raw.prepare('UPDATE candidate_items SET product_facts=?,category=?,event_type=? WHERE id=?').run(JSON.stringify(facts),facts.category,facts.kind==='sale'?'sale':'guitar_event',item.id);const row=(await s.candidates())[0],v=await publicationValidation(s,row,now,[source],pepper);assert.equal(v.valid,false);assert(v.errors.includes(facts.kind==='sale'?'sale_validation_failed':'event_date_missing'));}});
test('retention clears labels after 90 days, coarse ledger after 365 days',async()=>{const s=await setup(),item=await put(s);await decide(s,await approveInput(s,item));await purgeDecisionLedger(s,now+91*86400000);const row=await s.db.prepare('SELECT * FROM news_decision_ledger').first();assert.equal(row.persisted_label,null);assert.equal(row.actor_type,'fixture');await purgeDecisionLedger(s,now+366*86400000);assert.equal(count(s,'news_decision_ledger'),0);});
test('additive migration preserves all candidate columns and statuses and does not backfill a ledger',()=>{const db=new DatabaseSync(':memory:'),dir=new URL('../migrations/',import.meta.url),names=readdirSync(dir).sort();for(const n of names.filter(n=>n<'0011_operator_ledger.sql'))db.exec(readFileSync(new URL(n,dir),'utf8'));for(const [status,n]of [['approved',49],['pending',13],['rejected',19]])for(let i=0;i<n;i++)db.prepare('INSERT INTO candidate_items(id,source_id,source_name,source_url,normalized_url,category,label,topic_key,collected_at,review_status,review_reason,expires_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(status+i,'fixture','Fixture','https://fixture.test/'+status+i,'https://fixture.test/'+status+i,'dtm_software','Fixture label',status+i,'2026-10-01',status,'fixture',now+86400000);const before=db.prepare('SELECT * FROM candidate_items ORDER BY id').all();db.exec(readFileSync(new URL('0011_operator_ledger.sql',dir),'utf8'));const after=db.prepare('SELECT * FROM candidate_items ORDER BY id').all().map(({review_revision,...row})=>row);assert.deepEqual(JSON.parse(JSON.stringify(after)),JSON.parse(JSON.stringify(before)));assert.equal(db.prepare('SELECT COUNT(*) n FROM news_decision_ledger').get().n,0);db.close();});
