import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {SignJWT,generateKeyPair,exportJWK,createLocalJWKSet} from 'jose';import {handleOperatorRequest} from '../src/operator-worker.js';import {operatorClient} from '../scripts/operator-client.mjs';import {pepper} from './helpers.js';import {setup,put,approveInput,now} from './operator-case.js';
const {publicKey,privateKey}=await generateKeyPair('RS256'),jwk={...await exportJWK(publicKey),kid:'test-key'},jwks=createLocalJWKSet({keys:[jwk]}),origin='https://operator.fixture.test',issuer='https://fixture-team.cloudflareaccess.com',aud='a'.repeat(64);
async function jwt(extra={},key=privateKey){return new SignJWT({email:'human@fixture.test',type:'app',...extra}).setProtectedHeader({alg:'RS256',kid:'test-key'}).setIssuer(extra.iss||issuer).setAudience(extra.aud||aud).setSubject(extra.sub||'fixture-human').setIssuedAt(Math.floor(now/1000)).setExpirationTime(extra.exp||Math.floor(now/1000)+3600).sign(key);}
async function environment(){const s=await setup();return {s,env:{NEWS_DB:s.db,NEWS_HEADLINE_PEPPER:pepper,NEWS_OPERATOR_ORIGIN:origin,NEWS_ACCESS_ISSUER:issuer,NEWS_ACCESS_AUD:aud,NEWS_OPERATOR_EMAILS:'["human@fixture.test"]',NEWS_SOURCE_IDS:'["shimamura"]',OPERATOR_ASSETS:{fetch:async request=>new Response(await readFile(new URL('../operator-ui/'+(new URL(request.url).pathname==='/'?'index.html':new URL(request.url).pathname.slice(1)),import.meta.url)),{headers:{'Content-Type':new URL(request.url).pathname.endsWith('.js')?'application/javascript':'text/html'}})}}};}
async function call(env,path,token,options={}){return handleOperatorRequest(new Request(origin+path,{...options,headers:{...(token?{'Cf-Access-Jwt-Assertion':token}:{}),...options.headers}}),env,now,{jwks});}
for(const [name,claims]of [['wrong issuer',{iss:'https://wrong.cloudflareaccess.com'}],['wrong audience',{aud:'b'.repeat(64)}],['expired',{exp:Math.floor(now/1000)-1}],['non operator',{email:'other@fixture.test'}],['service identity',{type:'service'}]])test(`server auth denies ${name}`,async()=>{const {env}=await environment();assert([401,403].includes((await call(env,'/api/pending',await jwt(claims))).status));});
test('missing JWT, invalid signature, missing claims and unconfigured environment fail closed',async()=>{const {env}=await environment();assert.equal((await call(env,'/',null)).status,401);const other=await generateKeyPair('RS256');assert.equal((await call(env,'/api/pending',await jwt({},other.privateKey))).status,401);assert.equal((await call(env,'/api/pending',await jwt({email:undefined}))).status,401);assert.equal((await call({...env,NEWS_ACCESS_AUD:''},'/',await jwt())).status,503);});
test('every static asset is authenticated; no public bypass via direct asset URL',async()=>{const {env}=await environment(),token=await jwt();for(const path of ['/','/index.html','/review.js','/review.css']){assert.equal((await call(env,path,null)).status,401);const response=await call(env,path,token);assert.equal(response.status,200);assert.equal(response.headers.get('Cache-Control'),'no-store');assert(response.headers.get('Content-Security-Policy').includes("frame-ancestors 'none'"));}assert.equal((await call(env,'/other',token)).status,404);});
test('CSRF token and exact Origin required for mutations; token bound to authenticated session',async()=>{const {s,env}=await environment(),item=await put(s),input=await approveInput(s,item),token=await jwt(),session=await (await call(env,'/api/session',token)).json();for(const headers of [{'Content-Type':'application/json',Origin:origin},{'Content-Type':'application/json',Origin:'https://evil.fixture.test','X-News-CSRF':session.csrf},{'Content-Type':'application/json','X-News-CSRF':session.csrf},{'Content-Type':'application/json',Origin:origin,'X-News-CSRF':session.csrf,'Sec-Fetch-Site':'cross-site'},{'Content-Type':'application/json',Origin:origin,'X-News-CSRF':'1791000000000.'+'0'.repeat(64)}])assert.equal((await call(env,'/api/decision',token,{method:'POST',headers,body:JSON.stringify(input)})).status,403);const different=await jwt({jti:'other-session'});assert.equal((await call(env,'/api/decision',different,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','X-News-CSRF':session.csrf},body:JSON.stringify(input)})).status,403);for(const endpoint of ['/api/facts-recheck']){assert.equal((await call(env,endpoint,null,{method:'POST',body:'{}'})).status,401);assert.equal((await call(env,endpoint,token,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:'{}'})).status,403);}
assert.equal((await s.candidates())[0].review_status,'pending');});
test('malformed JSON, wrong media type, oversized request and unknown input cannot mutate',async()=>{const {s,env}=await environment();await put(s);const token=await jwt(),session=await (await call(env,'/api/session',token)).json();for(const [body,type]of [['{','application/json'],['[]','application/json'],['{}','text/plain'],['x'.repeat(9000),'application/json'],['{"action":"approve","sql":"DROP TABLE"}','application/json']]){const response=await call(env,'/api/decision',token,{method:'POST',headers:{Origin:origin,'Content-Type':type,'X-News-CSRF':session.csrf},body});assert.equal(response.status,422);}assert.equal((await s.candidates())[0].review_status,'pending');});
test('real signed human JWT: CLI and browser use the same decision/ledger, retries and payload conflict',async()=>{const {s,env}=await environment(),item=await put(s),input=await approveInput(s,item),token=await jwt();const fetcher=async(url,options)=>{const headers=new Headers(options.headers);assert.equal(headers.get('Cookie'),'CF_Authorization='+token);headers.set('Cf-Access-Jwt-Assertion',token);return handleOperatorRequest(new Request(url,{...options,headers}),env,now,{jwks});};const a=await operatorClient(origin,token,'/api/decision',input,{fetcher}),b=await operatorClient(origin,token,'/api/decision',input,{fetcher});assert.deepEqual(a,b);const ledger=await s.db.prepare('SELECT * FROM news_decision_ledger').first();assert.equal(ledger.actor_type,'system_repair');assert.equal(ledger.actor_id,'access:fixture-human');await assert.rejects(operatorClient(origin,token,'/api/decision',{...input,reason:'operator_review'},{fetcher}),/idempotency_payload_changed/);assert.equal((await s.db.prepare('SELECT COUNT(*) n FROM news_decision_ledger').first()).n,1);});
test('HTTP client response lost after commit can repeat exact request without extra decisions',async()=>{const {s,env}=await environment(),item=await put(s),input=await approveInput(s,item),token=await jwt();let lose=true;const fetcher=async(url,options)=>{const headers=new Headers(options.headers);headers.set('Cf-Access-Jwt-Assertion',token);const result=await handleOperatorRequest(new Request(url,{...options,headers}),env,now,{jwks});if(lose&&url.endsWith('/api/cli-decision')){lose=false;throw Error('timeout_after_committed_response');}return result;};await assert.rejects(operatorClient(origin,token,'/api/decision',input,{fetcher}),/timeout/);assert.equal((await operatorClient(origin,token,'/api/decision',input,{fetcher})).action,'approve');assert.equal((await s.db.prepare('SELECT COUNT(*) n FROM news_decision_ledger').first()).n,1);});
test('JSON detail is inert; UI uses textContent and restricts URL protocols',async()=>{const {s,env}=await environment(),item=await put(s);await s.db.prepare("UPDATE candidate_items SET label=?,source_url=? WHERE id=?").bind('<img src=x onerror=alert(1)>','javascript:alert(1)',item.id).run();const response=await call(env,'/api/candidates/'+item.id,await jwt());assert.equal(response.headers.get('Content-Type'),'application/json');assert.equal((await response.json()).validation.valid,false);const code=await readFile(new URL('../operator-ui/review.js',import.meta.url),'utf8');assert(!/innerHTML|insertAdjacentHTML|eval\(/.test(code));assert(code.includes("u.protocol!=='https:'"));assert(code.includes("a.rel='noopener noreferrer'"));});
test('operator config isolates NEWS DB and has no schedule, service, account or Sync binding',async()=>{const config=JSON.parse(await readFile(new URL('../wrangler.operator.jsonc',import.meta.url),'utf8'));assert.equal(config.workers_dev,true);assert.equal(config.vars.NEWS_ACCESS_AUD,undefined);assert.equal(config.preview_urls,false);assert.equal(config.assets.run_worker_first,true);assert.equal(config.d1_databases.length,1);assert.equal(config.d1_databases[0].binding,'NEWS_DB');assert.equal(config.triggers,undefined);assert.equal(config.services,undefined);});

test('GUI verified identity is human_operator; CLI cannot label itself human',async()=>{const {s,env}=await environment(),item=await put(s),input=await approveInput(s,item),token=await jwt(),session=await (await call(env,'/api/session',token)).json();const response=await call(env,'/api/decision',token,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','X-News-CSRF':session.csrf},body:JSON.stringify(input)});assert.equal(response.status,200);assert.equal((await s.db.prepare('SELECT actor_type FROM news_decision_ledger').first()).actor_type,'human_operator');});

test('Phase B read-only endpoints require Access, preserve Origin checks and reject stale candidate context',async()=>{
 const {s,env}=await environment(),item=await put(s),token=await jwt();
 const detail=await (await call(env,'/api/candidates/'+item.id,token)).json();
 for(const path of ['/api/summary','/api/human-decisions','/api/candidates/'+item.id+'/similar-decisions']){
  assert.equal((await call(env,path,null)).status,401);assert.equal((await call(env,path,await jwt({type:'service'}))).status,403);assert.equal((await call(env,path,token,{headers:{Origin:'https://evil.fixture.test'}})).status,403);
  const result=await call(env,path,token);assert.equal(result.status,200);assert.equal(result.headers.get('Cache-Control'),'no-store');
 }
 const insight=await (await call(env,'/api/candidates/'+item.id+'/similar-decisions',token)).json();assert.equal(insight.recommendation,'NO_RECOMMENDATION');assert.equal(insight.candidateRevision,detail.revision);assert.equal(insight.candidateSnapshot,detail.snapshot);
 assert.equal((await call(env,'/api/candidates/'+item.id+'/similar-decisions?revision=99&snapshot='+detail.snapshot,token)).status,409);
 assert.equal((await call(env,'/api/candidates/not-found/similar-decisions',token)).status,404);
 assert.equal((await call(env,'/api/human-decisions?offset=-1',token)).status,422);
 assert.equal((await call(env,'/api/summary',token,{method:'POST'})).status,404);
 assert.equal((await s.db.prepare('SELECT COUNT(*) n FROM news_decision_ledger').first()).n,0);assert.equal((await s.candidates())[0].review_status,'pending');
});
