import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const code=await readFile(new URL('../operator-ui/review.js',import.meta.url),'utf8');
class Element{
 constructor(tag='div',text=''){this.tagName=tag;this.textContent=text;this.children=[];this.value='all';this.hidden=false;this.dataset={};this.attributes={};this.events={};}
 append(...nodes){this.children.push(...nodes);} replaceChildren(...nodes){this.children=[...nodes];} add(n){this.append(n);} get options(){return this.children;}
 setAttribute(k,v){this.attributes[k]=v;} addEventListener(k,f){this.events[k]=f;} querySelectorAll(){return [];} showModal(){this.open=true;} close(){this.open=false;}
}
const row=(id,valid,errors=[],facts={product:id})=>({id,label:id,source:'Source',sourceId:'source',decision:'PUBLISH_REVIEW',sourceUrl:'https://example.com/'+id,status:'pending',facts,history:[],validation:{valid,errors,duplicates:[],quality:{labelInformationScore:1},publishableLabel:id}});
function ui(rows){const ids=Object.fromEntries(['mode','source','count','list','notice','submit','retry','checks','reload','identity','confirm','confirm-title','confirm-label','reason','dashboard','human-history','history-list','history-more','shadow-summary','shadow-evaluate','shadow-pattern-list','last-updated','refresh-status','rejected-count'].map(id=>[id,new Element()]));const requests=[];const context=vm.createContext({document:{getElementById:id=>ids[id],createElement:tag=>new Element(tag)},URL,Option:class extends Element{constructor(t,v){super('option',t);this.value=v;}},sessionStorage:{getItem:()=>null},fetch:async(path,options)=>{requests.push({path,options});return {ok:true,json:async()=>path==='/api/session'?{operator:'test',version:'0.16.0'}:path==='/api/summary'?{published:53,pending:rows.length,rejected:19,humanDecisions:2}:path==='/api/shadow-metrics'?{totalHumanDecisions:2,independentHumanDecisions:0,unmatchedHumanDecisions:2,evaluationsRecorded:0,observations:{},patterns:[],lowSample:true}:path.startsWith('/api/human-decisions')?{items:[],nextOffset:null}:{items:rows}}},crypto:{randomUUID:()=> 'test'},console});vm.runInContext(code,context);return {ids,requests,context,run:s=>vm.runInContext(s,context)};}
const settle=()=>new Promise(resolve=>setImmediate(resolve));
test('掲載可 uses server validation: missing facts, duplicate and policy blocked are excluded; source/REVIEW/all remain usable',async()=>{const u=ui([row('ready',true),row('missing',false,['facts_incomplete'],null),row('duplicate',false,['duplicate']),row('policy',false,['publication_policy_rejected'])]);await settle();assert.equal(u.ids.list.children.length,4);u.ids.mode.value='approvable';u.ids.mode.events.change();assert.equal(u.ids.list.children.length,1);assert.equal(u.ids.list.children[0].dataset.candidateId,'ready');u.ids.source.value='other';u.ids.source.events.change();assert.equal(u.ids.count.textContent,'掲載可 0件（全4件）');u.ids.source.value='all';u.ids.mode.value='PUBLISH_REVIEW';u.ids.mode.events.change();assert.equal(u.ids.list.children.length,4);u.ids.mode.value='all';u.ids.mode.events.change();assert.equal(u.ids.list.children.length,4);});
test('detail expands and collapses inside its own card without scroll/focus; decision state and HTTPS links remain intact',async()=>{const u=ui([row('ready',true),row('blocked',false,['duplicate'])]);await settle();u.run("api=async path=>items.find(x=>path.endsWith(x.id))");const first=u.ids.list.children[0],button=first.children.at(-2),detail=first.children.at(-1);await button.events.click();await settle();assert.equal(detail.hidden,false);assert.equal(button.textContent,'詳細を閉じる');assert.equal(button.attributes['aria-expanded'],'true');const controls=first.children.find(x=>x.className==='actions decision-actions');assert.equal(controls.children.find(x=>x.textContent==='掲載する').disabled,false);assert.equal(controls.children.find(x=>x.textContent==='掲載しない').disabled,false);const link=first.children.find(x=>x.tagName==='a');assert.equal(link.href,'https://example.com/ready');assert.equal(link.rel,'noopener noreferrer');button.events.click();assert.equal(detail.hidden,true);assert.equal(button.textContent,'詳細を確認');await u.ids.list.children[1].children.at(-2).events.click();await settle();const blocked=u.ids.list.children[1].children.find(x=>x.className==='actions decision-actions');assert.equal(blocked.children.find(x=>x.textContent==='掲載する').disabled,true);assert.equal(blocked.children.find(x=>x.textContent==='掲載しない').disabled,false);assert(!/scrollIntoView|location\.hash/.test(code));});
test('late detail response cannot select a different card or reopen a closed detail',async()=>{const u=ui([row('a',true),row('b',true)]);await settle();u.run('api=path=>new Promise(resolve=>{globalRequests.push({path,resolve})})');u.context.globalRequests=[];const a=u.ids.list.children[0].children.at(-2),b=u.ids.list.children[1].children.at(-2);a.events.click();b.events.click();u.context.globalRequests[1].resolve(row('b',true));await settle();u.context.globalRequests[0].resolve(row('a',true));await settle();assert.equal(u.run('selected.id'),'b');b.events.click();assert.equal(u.run('selected'),null);assert.equal(u.ids.list.children[0].children.at(-1).hidden,true);});
test('filter changes invalidate pending details and decided candidates are not reopened outside the list',async()=>{const u=ui([row('a',true)]);await settle();u.context.globalRequests=[];u.run('api=path=>new Promise(resolve=>globalRequests.push(resolve))');u.ids.list.children[0].children.at(-2).events.click();u.ids.source.value='other';u.ids.source.events.change();u.context.globalRequests[0](row('a',true));await settle();assert.equal(u.run('selected'),null);await u.run("showDetail('no-longer-pending')");assert.equal(u.context.globalRequests.length,1);});
test('untrusted facts and labels stay text, unsafe original URLs have no link',async()=>{const u=ui([row('<img onerror=alert(1)>',true)]);await settle();assert.equal(u.ids.list.children[0].children[0].textContent,'<img onerror=alert(1)>');assert.equal(u.run("originalLink('javascript:alert(1)').tagName"),'span');assert.equal(u.run("originalLink('https://user:pass@example.com').tagName"),'span');assert(!/innerHTML|insertAdjacentHTML|eval\(/.test(code));});
test('operator card and inline detail group recording/creator labels without changing raw candidate or decision category',async()=>{
 for(const category of ['recording_audio','creator_streaming','dtm_software']){
  const candidate={...row('SHURE MV6 Gen 2',true),category};const u=ui([candidate]);await settle();
  const label='DTM・録音・配信';assert(u.ids.list.children[0].children[2].children.some(n=>n.textContent===label));
  u.run('api=async()=>items[0]');await u.ids.list.children[0].children.at(-2).events.click();await settle();
  assert(u.ids.list.children[0].children.at(-1).children[1].children[2].children.some(n=>n.textContent===label));
  assert.equal(u.run('selected.category'),category);assert.equal(candidate.category,category);
 }
});
test('dashboard renders authoritative server counts, not filtered items; recommendation remains inert and text-safe',async()=>{
 const u=ui([row('one',true)]);await settle();u.run("dashboardView({published:51,pending:11,rejected:19,humanDecisions:2})");assert.deepEqual(u.ids.dashboard.children.slice(0,4).map(n=>n.children[1].textContent),['51','11','1','2']);
 u.ids.mode.value='approvable';u.ids.mode.events.change();assert.equal(u.ids.dashboard.children[1].children[1].textContent,'11');
 const section=new Element();u.context.section=section;u.run("insightsView({matchedDecisionCount:2,approveCount:2,rejectCount:0,evidenceCount:0,minimumEvidence:5,similarityLevel:'WEAK_SIMILAR',reasonSummary:'insufficient_evidence',recommendation:'NO_RECOMMENDATION',matches:[]},section)");assert(section.children.some(n=>n.textContent==='まだ判断データが足りません'));assert.equal(u.run('selected'),null);
 u.run("insightsView({matchedDecisionCount:5,approveCount:3,rejectCount:2,evidenceCount:5,minimumEvidence:5,similarityLevel:'EXACT_PATTERN',reasonSummary:'contradictory_history',recommendation:'NO_RECOMMENDATION',matches:[]},section)");assert(section.children.some(n=>n.textContent==='判断が分かれているため推薦なし'));assert(!section.children.some(n=>n.tagName==='button'));
});
test('human history loads identifiers and coarse fields using text nodes, with pagination and no raw headline or identity',async()=>{
 const u=ui([]);await settle();u.run("api=async()=>({items:[{candidate_id:'<img onerror=alert(1)>',source_id:'source',category:'creator_streaming',verdict:'approve',reason:'useful_product',decided_at:1,policy_version:'operator-publication-1'}],nextOffset:50})");await u.run('loadHistory(true)');assert.equal(u.ids['history-list'].children.length,1);assert(u.ids['history-list'].children[0].children[1].textContent.includes('<img onerror=alert(1)>'));assert(u.ids['history-list'].children[0].children[0].textContent.includes('録音・配信'));assert.equal(u.ids['history-more'].hidden,false);assert.equal(u.run('historyOffset'),50);
});
test('Shadow low-N UI hides rates; records are not mistaken for evaluated humans; no automatic decision feedback',async()=>{const u=ui([]);await settle();u.run("shadowView({totalHumanDecisions:2,independentHumanDecisions:0,unmatchedHumanDecisions:2,evaluationsRecorded:17,recommendApprove:0,recommendReject:0,noRecommendation:0,agreement:0,falsePublishDirection:0,missedPublishDirection:0,contradictions:0,lowSample:true,policyVersion:'policy',ruleVersion:'rule',patterns:[]})");assert(u.ids['shadow-summary'].children.some(n=>n.textContent.includes('判断材料不足')));assert(u.ids['shadow-summary'].children.some(n=>n.textContent.includes('比較済み（独立） 0')));assert(!u.ids['shadow-summary'].children.some(n=>n.textContent.includes('%')));assert(!code.includes('Shadow推薦と一致しました'));assert.equal(u.run('selected'),null);});

test('refresh fetches all authoritative areas, replaces counts and preserves filter; no-store GET only',async()=>{
 const u=ui([row('old',false,['facts_incomplete'])]);await settle();assert(u.ids['last-updated'].textContent.includes('（JST）'));u.ids.mode.value='approvable';u.ids.mode.events.change();assert.equal(u.ids.count.textContent,'掲載可 0件（全1件）');
 u.context.nextRows=[row('new',true),row('dup',false,['duplicate'])];u.run("api=async path=>{refreshRequests.push(path);return path==='/api/pending'?{items:nextRows}:path==='/api/summary'?{published:54,pending:2,rejected:19,humanDecisions:3}:path==='/api/shadow-metrics'?{totalHumanDecisions:3,observations:{},patterns:[],lowSample:true}:{items:[],nextOffset:null}} ");u.context.refreshRequests=[];
 assert.equal(await u.run('refresh()'),true);assert.deepEqual(u.context.refreshRequests.sort(),['/api/human-decisions?offset=0','/api/pending','/api/shadow-metrics','/api/summary']);assert.equal(u.ids.count.textContent,'掲載可 1件（全2件）');assert.equal(u.ids.list.children[0].dataset.candidateId,'new');assert.equal(u.ids.dashboard.children[0].children[1].textContent,'54');assert.equal(u.ids['refresh-status'].textContent,'更新しました');assert.equal(u.ids.reload.disabled,false);
 assert(u.requests.every(r=>r.options.cache==='no-store'&&!r.options.method));
});
test('JST timestamp advances only on a successful complete refresh; failure preserves previous data/time',async()=>{
 const u=ui([row('ready',true)]);await settle();u.context.clock=Date.parse('2026-10-03T00:01:02Z');u.run('Date.now=()=>clock');assert.equal(await u.run('refresh()'),true);assert.equal(u.ids['last-updated'].textContent,'最終更新：2026/10/03 09:01:02（JST）');
 u.context.clock+=2000;assert.equal(await u.run('refresh()'),true);assert.equal(u.ids['last-updated'].textContent,'最終更新：2026/10/03 09:01:04（JST）');const previous=u.ids['last-updated'].textContent;
 u.run("const realApi=api;api=async path=>{if(path==='/api/summary')throw Error('summary unavailable');return realApi(path)}");u.context.clock+=2000;assert.equal(await u.run('refresh()'),false);assert.equal(u.ids['last-updated'].textContent,previous);assert(u.ids['refresh-status'].textContent.startsWith('更新に失敗しました'));assert.equal(u.ids.list.children[0].dataset.candidateId,'ready');assert.equal(u.ids.reload.disabled,false);
});
test('refresh loading and overlapping requests are bounded; partial Shadow/History failures cannot report success',async()=>{
 const u=ui([]);await settle();u.context.waiting=[];u.run('api=path=>new Promise((resolve,reject)=>waiting.push({path,resolve,reject}))');const first=u.run('refresh()'),second=u.run('refresh()');assert.equal(first,second);assert.equal(u.context.waiting.length,4);assert.equal(u.ids.reload.textContent,'更新中…');assert.equal(u.ids.reload.disabled,true);
 u.context.waiting.find(r=>r.path==='/api/shadow-metrics').reject(Error('shadow unavailable'));assert.equal(await first,false);assert(u.ids['refresh-status'].textContent.includes('更新に失敗しました'));
});

const walk=node=>[node,...node.children.flatMap(walk)];
test('formal server label wins; insufficient labels and unknown categories are safe human-facing fallbacks',async()=>{
 const u=ui([{...row('temp',true),label:'Gen2の製品情報（要確認）',category:'amps_effects',validation:{...row('temp',true).validation,publishableLabel:'SHURE MV6 Gen 2 発売'}},{...row('missing',false,['facts_incomplete'],null),label:'label_required',category:'unknown',validation:{...row('missing',false,['facts_incomplete']).validation,publishableLabel:null}}]);await settle();
 assert.equal(u.ids.list.children[0].children[0].textContent,'SHURE MV6 Gen 2 発売');assert.equal(u.ids.list.children[1].children[0].textContent,'正式表題を確定できません');assert(walk(u.ids.list.children[0]).some(n=>n.textContent==='アンプ・エフェクター'));assert(walk(u.ids.list.children[1]).some(n=>n.textContent==='カテゴリ未確定'));assert(walk(u.ids.list.children[1]).some(n=>n.textContent==='facts不足'));assert(!walk(u.ids.list.children[1]).some(n=>n.textContent.includes('label_required')));
});
test('overview is default; evidence, learning and history tabs disclose separately; learning is lazy',async()=>{
 const candidate={...row('ready',true),reason:'internal_code',history:[{verdict:'approve',reason:'useful_product',decided_at:1,policy_version:'policy'}]};const u=ui([candidate]);await settle();u.context.candidate=candidate;u.context.detailReads=[];u.run('api=async path=>{detailReads.push(path);return candidate}');await u.ids.list.children[0].children.at(-2).events.click();await settle();const detail=u.ids.list.children[0].children.at(-1),tabs=detail.children[0],panels=detail.children.slice(1);assert.equal(tabs.attributes.role,'tablist');assert.deepEqual(tabs.children.map(n=>n.textContent),['概要','根拠','学習','履歴']);assert.deepEqual(panels.map(n=>n.hidden),[false,true,true,true]);assert.equal(u.context.detailReads.length,1);assert(!walk(panels[0]).some(n=>n.textContent.includes('internal_code')));tabs.children[1].events.click();assert.deepEqual(panels.map(n=>n.hidden),[true,false,true,true]);assert(walk(panels[1]).some(n=>n.textContent.includes('internal_code')));tabs.children[3].events.click();assert.deepEqual(panels.map(n=>n.hidden),[true,true,true,false]);assert(walk(panels[3]).some(n=>n.textContent.includes('有用な製品')));tabs.children[2].events.click();await settle();assert.equal(panels[2].hidden,false);assert(u.context.detailReads.some(p=>p.includes('similar-decisions')));tabs.children[0].events.click();assert.equal(panels[0].hidden,false);
});
test('review and duplicate filters preserve authoritative ready count and exclude blocked approval',async()=>{const u=ui([row('yes',true),row('missing',false,['facts_incomplete'],null),row('dup',false,['duplicate'])]);await settle();assert.equal(u.ids.dashboard.children[2].children[1].textContent,'1');u.ids.mode.value='review';u.ids.mode.events.change();assert.equal(u.ids.list.children.length,2);u.ids.mode.value='duplicate';u.ids.mode.events.change();assert.equal(u.ids.list.children.length,1);assert.equal(u.ids.list.children[0].dataset.candidateId,'dup');assert.equal(u.ids.dashboard.children[2].children[1].textContent,'1');});
test('surface decision loads fresh server snapshot, invalidates stale reads and preserves original confirmation checks',async()=>{
 const u=ui([row('a',true),row('b',true)]);await settle();u.context.reads=[];u.run('api=path=>new Promise(resolve=>reads.push({path,resolve}))');
 const controls=i=>u.ids.list.children[i].children.find(n=>n.className==='actions decision-actions');controls(0).children[0].events.click();controls(1).children[1].events.click();u.context.reads[1].resolve({...row('b',true),revision:9,snapshot:'fresh'});await settle();assert.equal(u.run('selected.id'),'b');assert.equal(u.run('selected.revision'),9);assert.equal(u.run('action'),'reject');u.context.reads[0].resolve(row('a',true));await settle();assert.equal(u.run('selected.id'),'b');assert.equal(u.ids['confirm-title'].textContent,'このニュースを掲載しませんか？');
 const fresh=ui([row('a',true)]);await settle();fresh.run("api=async()=>({...items[0],validation:{...items[0].validation,valid:false,errors:['duplicate']}})");await fresh.ids.list.children[0].children.find(n=>n.className==='actions decision-actions').children[0].events.click();await settle();assert.notEqual(fresh.ids.confirm.open,true);assert(fresh.ids.notice.textContent.includes('掲載条件が変わりました'));
});

test('card surface shows server missing facts and recovery guidance as safe text only',async()=>{
 const candidate={...row('blocked',false,['facts_incomplete'],null),factsReview:{missing:['製品名'],nextAction:'<img src=x onerror=alert(1)> 一次情報を確認してください。',recoveryClass:'NOT_SAFELY_RECOVERABLE'}};const u=ui([candidate]);await settle();const nodes=walk(u.ids.list.children[0]);assert(nodes.some(n=>n.textContent==='不足・未確認：製品名'));assert(nodes.some(n=>n.textContent===candidate.factsReview.nextAction));assert(!nodes.some(n=>n.tagName==='img'));assert.equal(nodes.find(n=>n.textContent==='掲載する').disabled,true);assert(!code.includes('scrollIntoView'));
});
test('publish interest UI is separate from decisions, cancellable, absent for ready/duplicate, history text-safe',async()=>{
 const target={...row('interest',false,['facts_incomplete']),revision:0,snapshot:'0'.repeat(64),lifecycle:{next_recheck_at:1,recheck_attempt_count:2,user_publish_interest:0,longPending:true,history:[{result:'<img onerror=alert(1)>'}]}};
 const u=ui([target,row('ready',true),row('duplicate',false,['duplicate'])]);await settle();
 assert(u.ids.list.children[0].children.some(x=>x.textContent==='長期保留'));
 const controls=u.ids.list.children[0].children.find(x=>x.className==='actions decision-actions');assert(controls.children.some(b=>b.textContent==='掲載したい'));
 for(const c of u.ids.list.children.slice(1))assert(!c.children.find(x=>x.className==='actions decision-actions').children.some(b=>b.textContent==='掲載したい'));
 u.context.capture=[];u.run("api=async(path,options)=>{capture.push({path,options});if(path==='/api/session')return {csrf:'test'};if(path==='/api/publish-interest'){items[0].lifecycle.user_publish_interest=JSON.parse(options.body).interest?1:0;return items[0].lifecycle;}return {};};refresh=async()=>{};");
 await controls.children.find(b=>b.textContent==='掲載したい').events.click();assert.equal(u.context.capture.at(-1).path,'/api/publish-interest');assert.equal(JSON.parse(u.context.capture.at(-1).options.body).interest,true);assert(!u.context.capture.some(r=>r.path==='/api/decision'));
 u.run('renderList()');const cancel=u.ids.list.children[0].children.find(x=>x.className==='actions decision-actions').children.find(b=>b.textContent==='掲載希望を取り消す');assert(cancel);await cancel.events.click();assert.equal(JSON.parse(u.context.capture.at(-1).options.body).interest,false);
});
test('published card offers explicit takedown only; minor reason is firmware-only, historical card is inert',async()=>{const u=ui([{...row('published',true),status:'approved',eventType:'firmware'}]);await settle();const actions=u.ids.list.children[0].children.find(n=>n.className==='actions decision-actions');const children=u.ids.list.children[0].children;const controls=children.find(n=>n.children.some(b=>b.textContent==='公開を取り下げる'));assert(controls);assert.equal(controls.children.find(b=>b.textContent==='掲載する').disabled,true);assert.equal(controls.children.find(b=>b.textContent==='公開を取り下げる').disabled,false);assert(!controls.children.some(b=>b.textContent==='掲載したい'));u.run('selected=items[0];confirmDecision("reject")');assert.equal(u.ids['confirm-title'].textContent,'このニュースの公開を取り下げますか？');assert(u.ids.reason.options.some(o=>o.value==='minor_update'));u.run('selected={...items[0],eventType:"new_product"};confirmDecision("reject")');assert(!u.ids.reason.options.some(o=>o.value==='minor_update'));});
test('successful decision releases busy before repaint so remaining candidate buttons are usable',async()=>{const u=ui([row('remaining',true)]);await settle();u.context.sessionStorage.removeItem=()=>{};await u.run("sendDecision({id:'completed',action:'reject'})");const controls=u.ids.list.children[0].children.find(n=>n.children.some(b=>b.textContent==='掲載しない'));assert.equal(controls.children.find(b=>b.textContent==='掲載する').disabled,false);assert.equal(controls.children.find(b=>b.textContent==='掲載しない').disabled,false);assert.equal(u.run('busy'),false);});

test('non-event article evidence guidance names subject/use/functions without an invented event',async()=>{const u=ui([]);await settle();u.context.article={factsReview:{missing:[],available:true,lastVerifiedAt:1,surfaceUrl:'https://www.ikebe-gakki-pb.com/new_product/172830/',method:'explicit_product_article_fields',provenance:[]}};u.run("factsView(article,document.getElementById('list'))");assert(walk(u.ids.list).some(n=>n.textContent==='原記事に明示された記事対象・用途・機能を確認します。 '));assert(!walk(u.ids.list).some(n=>n.textContent.includes('イベント項目')));});
