import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
const code=await readFile(new URL('../operator-ui/review.js',import.meta.url),'utf8');
class Element{
 constructor(tag='div',text=''){this.tagName=tag;this.textContent=text;this.children=[];this.value='all';this.hidden=false;this.dataset={};this.attributes={};this.events={};}
 append(...nodes){this.children.push(...nodes);} replaceChildren(...nodes){this.children=[...nodes];} add(n){this.append(n);} get options(){return this.children;}
 setAttribute(k,v){this.attributes[k]=v;} addEventListener(k,f){this.events[k]=f;} querySelectorAll(){return [];} showModal(){this.open=true;} close(){this.open=false;}
}
const row=(id,valid,errors=[],facts={product:id})=>({id,label:id,source:'Source',sourceId:'source',decision:'PUBLISH_REVIEW',sourceUrl:'https://example.com/'+id,status:'pending',facts,history:[],validation:{valid,errors,duplicates:[],quality:{labelInformationScore:1},publishableLabel:id}});
function ui(rows){const ids=Object.fromEntries(['mode','source','count','list','notice','submit','retry','checks','reload','identity','confirm','confirm-title','confirm-label','reason','dashboard','human-history','history-list','history-more','shadow-summary','shadow-evaluate','shadow-pattern-list'].map(id=>[id,new Element()]));const requests=[];const context=vm.createContext({document:{getElementById:id=>ids[id],createElement:tag=>new Element(tag)},URL,Option:class extends Element{constructor(t,v){super('option',t);this.value=v;}},sessionStorage:{getItem:()=>null},fetch:async()=>({ok:true,json:async()=>({operator:'test',items:rows})}),crypto:{randomUUID:()=> 'test'},console});vm.runInContext(code,context);return {ids,requests,context,run:s=>vm.runInContext(s,context)};}
const settle=()=>new Promise(resolve=>setImmediate(resolve));
test('掲載可 uses server validation: missing facts, duplicate and policy blocked are excluded; source/REVIEW/all remain usable',async()=>{const u=ui([row('ready',true),row('missing',false,['facts_incomplete'],null),row('duplicate',false,['duplicate']),row('policy',false,['publication_policy_rejected'])]);await settle();assert.equal(u.ids.list.children.length,4);u.ids.mode.value='approvable';u.ids.mode.events.change();assert.equal(u.ids.list.children.length,1);assert.equal(u.ids.list.children[0].dataset.candidateId,'ready');u.ids.source.value='other';u.ids.source.events.change();assert.equal(u.ids.count.textContent,'保留 0件（全4件）');u.ids.source.value='all';u.ids.mode.value='PUBLISH_REVIEW';u.ids.mode.events.change();assert.equal(u.ids.list.children.length,4);u.ids.mode.value='all';u.ids.mode.events.change();assert.equal(u.ids.list.children.length,4);});
test('detail expands and collapses inside its own card without scroll/focus; decision state and HTTPS links remain intact',async()=>{const u=ui([row('ready',true),row('blocked',false,['duplicate'])]);await settle();u.run("api=async path=>items.find(x=>path.endsWith(x.id))");const first=u.ids.list.children[0],button=first.children.at(-2),detail=first.children.at(-1);await button.events.click();await settle();assert.equal(detail.hidden,false);assert.equal(button.textContent,'詳細を閉じる');assert.equal(button.attributes['aria-expanded'],'true');const controls=detail.children.find(x=>x.className==='actions');assert.equal(controls.children.find(x=>x.textContent==='掲載する').disabled,false);assert.equal(controls.children.find(x=>x.textContent==='掲載しない').disabled,false);const link=detail.children.find(x=>x.tagName==='a');assert.equal(link.href,'https://example.com/ready');assert.equal(link.rel,'noopener noreferrer');button.events.click();assert.equal(detail.hidden,true);assert.equal(button.textContent,'詳細を確認');await u.ids.list.children[1].children.at(-2).events.click();await settle();const blocked=u.ids.list.children[1].children.at(-1).children.find(x=>x.className==='actions');assert.equal(blocked.children.find(x=>x.textContent==='掲載する').disabled,true);assert.equal(blocked.children.find(x=>x.textContent==='掲載しない').disabled,false);assert(!/scrollIntoView|\.focus\(|location\.hash/.test(code));});
test('late detail response cannot select a different card or reopen a closed detail',async()=>{const u=ui([row('a',true),row('b',true)]);await settle();u.run('api=path=>new Promise(resolve=>{globalRequests.push({path,resolve})})');u.context.globalRequests=[];const a=u.ids.list.children[0].children.at(-2),b=u.ids.list.children[1].children.at(-2);a.events.click();b.events.click();u.context.globalRequests[1].resolve(row('b',true));await settle();u.context.globalRequests[0].resolve(row('a',true));await settle();assert.equal(u.run('selected.id'),'b');b.events.click();assert.equal(u.run('selected'),null);assert.equal(u.ids.list.children[0].children.at(-1).hidden,true);});
test('filter changes invalidate pending details and decided candidates are not reopened outside the list',async()=>{const u=ui([row('a',true)]);await settle();u.context.globalRequests=[];u.run('api=path=>new Promise(resolve=>globalRequests.push(resolve))');u.ids.list.children[0].children.at(-2).events.click();u.ids.source.value='other';u.ids.source.events.change();u.context.globalRequests[0](row('a',true));await settle();assert.equal(u.run('selected'),null);await u.run("showDetail('no-longer-pending')");assert.equal(u.context.globalRequests.length,1);});
test('untrusted facts and labels stay text, unsafe original URLs have no link',async()=>{const u=ui([row('<img onerror=alert(1)>',true)]);await settle();assert.equal(u.ids.list.children[0].children[0].textContent,'<img onerror=alert(1)>');assert.equal(u.run("originalLink('javascript:alert(1)').tagName"),'span');assert.equal(u.run("originalLink('https://user:pass@example.com').tagName"),'span');assert(!/innerHTML|insertAdjacentHTML|eval\(/.test(code));});
test('operator card and inline detail group recording/creator labels without changing raw candidate or decision category',async()=>{
 for(const category of ['recording_audio','creator_streaming','dtm_software']){
  const candidate={...row('SHURE MV6 Gen 2',true),category};const u=ui([candidate]);await settle();
  const label=category==='dtm_software'?'DTM':'録音・配信';assert(u.ids.list.children[0].children[1].textContent.includes(label));
  u.run('api=async()=>items[0]');await u.ids.list.children[0].children.at(-2).events.click();await settle();
  assert(u.ids.list.children[0].children.at(-1).children.some(n=>n.className==='meta'&&n.textContent.includes(label)));
  assert.equal(u.run('selected.category'),category);assert.equal(candidate.category,category);
 }
});
test('dashboard renders authoritative server counts, not filtered items; recommendation remains inert and text-safe',async()=>{
 const u=ui([row('one',true)]);await settle();u.run("dashboardView({published:51,pending:11,rejected:19,humanDecisions:2})");assert.deepEqual(u.ids.dashboard.children.slice(0,4).map(n=>n.children[1].textContent),['51','11','19','2']);
 u.ids.mode.value='approvable';u.ids.mode.events.change();assert.equal(u.ids.dashboard.children[1].children[1].textContent,'11');
 const section=new Element();u.context.section=section;u.run("insightsView({matchedDecisionCount:2,approveCount:2,rejectCount:0,evidenceCount:0,minimumEvidence:5,similarityLevel:'WEAK_SIMILAR',reasonSummary:'insufficient_evidence',recommendation:'NO_RECOMMENDATION',matches:[]},section)");assert(section.children.some(n=>n.textContent==='まだ判断データが足りません'));assert.equal(u.run('selected'),null);
 u.run("insightsView({matchedDecisionCount:5,approveCount:3,rejectCount:2,evidenceCount:5,minimumEvidence:5,similarityLevel:'EXACT_PATTERN',reasonSummary:'contradictory_history',recommendation:'NO_RECOMMENDATION',matches:[]},section)");assert(section.children.some(n=>n.textContent==='判断が分かれているため推薦なし'));assert(!section.children.some(n=>n.tagName==='button'));
});
test('human history loads identifiers and coarse fields using text nodes, with pagination and no raw headline or identity',async()=>{
 const u=ui([]);await settle();u.run("api=async()=>({items:[{candidate_id:'<img onerror=alert(1)>',source_id:'source',category:'creator_streaming',verdict:'approve',reason:'useful_product',decided_at:1,policy_version:'operator-publication-1'}],nextOffset:50})");await u.run('loadHistory(true)');assert.equal(u.ids['history-list'].children.length,1);assert(u.ids['history-list'].children[0].children[1].textContent.includes('<img onerror=alert(1)>'));assert(u.ids['history-list'].children[0].children[0].textContent.includes('録音・配信'));assert.equal(u.ids['history-more'].hidden,false);assert.equal(u.run('historyOffset'),50);
});
test('Shadow low-N UI hides rates; records are not mistaken for evaluated humans; no automatic decision feedback',async()=>{const u=ui([]);await settle();u.run("shadowView({totalHumanDecisions:2,independentHumanDecisions:0,unmatchedHumanDecisions:2,evaluationsRecorded:17,recommendApprove:0,recommendReject:0,noRecommendation:0,agreement:0,falsePublishDirection:0,missedPublishDirection:0,contradictions:0,lowSample:true,policyVersion:'policy',ruleVersion:'rule',patterns:[]})");assert(u.ids['shadow-summary'].children.some(n=>n.textContent.includes('判断材料不足')));assert(u.ids['shadow-summary'].children.some(n=>n.textContent.includes('比較済み（独立） 0')));assert(!u.ids['shadow-summary'].children.some(n=>n.textContent.includes('%')));assert(!code.includes('Shadow推薦と一致しました'));assert.equal(u.run('selected'),null);});
