import test from 'node:test';import assert from 'node:assert/strict';
import {setup,put,approveInput,source,now} from './operator-case.js';import {pepper} from './helpers.js';
import {operatorDecision,candidateSnapshot} from '../src/operator-review.js';
import {publicationValidation,DECISION_POLICY_VERSION} from '../src/decision-policy.js';
import {INSIGHTS_VERSION,retainedDecisionProfile} from '../src/operator-insights.js';
import {comparison,prepareShadowEvaluation,saveShadowEvaluation,evaluatePending,aggregateShadowMetrics,shadowMetrics,SHADOW_RULE_VERSION} from '../src/operator-shadow.js';
const actor={type:'human_operator',id:'access:synthetic-human'};
const statuses=['RECOMMEND_APPROVE','RECOMMEND_REJECT','NO_RECOMMENDATION'];
const count=s=>s.db.raw.prepare('SELECT COUNT(*) n FROM news_shadow_evaluations').get().n;
async function row(s,id){return s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(id).first();}
async function evaluate(s,id,at=now){const r=await row(s,id);return saveShadowEvaluation(s,{id,revision:r.review_revision,snapshot:await candidateSnapshot(r)},at,[source],pepper);}
function fixture(recommendation,verdict,i=0,extra={}){const id='e'+i,candidate='c'+i,profile={source:'source',surface:'example.test/news',category:'recording_streaming',type:'new_product',factShape:['product'],articleIdentity:'a'+i,topicIdentity:'t'+i};const result={evaluationId:id,ruleVersion:SHADOW_RULE_VERSION,policyVersion:DECISION_POLICY_VERSION,recommendation,contradictionCount:0};return {ledger:{decision_id:'d'+i,candidate_id:candidate,candidate_revision:0,candidate_snapshot:'snapshot',actor_type:'human_operator',success_state:'committed',policy_version:DECISION_POLICY_VERSION,created_at:now,decided_at:now,verdict,decision_features_json:JSON.stringify({shadowEvaluation:result}),...extra},evaluation:{evaluation_id:id,candidate_id:candidate,candidate_revision:0,candidate_snapshot:'snapshot',evaluated_at:now,policy_version:DECISION_POLICY_VERSION,rule_version:SHADOW_RULE_VERSION,profile_json:JSON.stringify(profile),evaluation_json:JSON.stringify(result)}};}
test('all six human/shadow comparisons preserve asymmetric directions',()=>{assert.equal(comparison(statuses[0],'approve'),'AGREE_APPROVE');assert.equal(comparison(statuses[0],'reject'),'FALSE_PUBLISH_DIRECTION');assert.equal(comparison(statuses[1],'approve'),'MISSED_PUBLISH_DIRECTION');assert.equal(comparison(statuses[1],'reject'),'AGREE_REJECT');assert.equal(comparison(statuses[2],'approve'),'NO_RECOMMENDATION_APPROVE');assert.equal(comparison(statuses[2],'reject'),'NO_RECOMMENDATION_REJECT');});
test('NONE logged before any human decision; repeated state idempotent; revision/validation change creates new immutable observation',async()=>{const s=await setup(),item=await put(s);const before=await row(s,item.id),first=await evaluate(s,item.id);assert.equal(first.recommendation,'NO_RECOMMENDATION');assert.equal(count(s),1);assert.deepEqual(await evaluate(s,item.id,now+1000),first);assert.equal(count(s),1);assert.deepEqual(await row(s,item.id),before);await s.db.prepare('UPDATE candidate_items SET review_revision=review_revision+1 WHERE id=?').bind(item.id).run();await assert.rejects(saveShadowEvaluation(s,{id:item.id,revision:0,snapshot:first.candidateSnapshot},now,[source],pepper),/candidate_changed/);const second=await evaluate(s,item.id);assert.notEqual(second.evaluationId,first.evaluationId);assert.equal(count(s),2);assert.equal((await shadowMetrics(s,now)).evaluatedHumanDecisions,0);assert.equal((await shadowMetrics(s,now)).agreementRate,null);assert(!JSON.stringify(first.profile).includes('MV6'));});
test('actual approve/reject recommendation logging uses five independent humans without publishing the evaluated candidate',async()=>{for(const verdict of ['approve','reject']){const s=await setup(),target=await put(s,'target');const r=await row(s,target.id),validation=await publicationValidation(s,r,now,[source],pepper),base=await retainedDecisionProfile(r,validation,now);for(let i=0;i<5;i++){const teacher=await put(s,'teacher-'+i,{productFacts:{...target.productFacts,product:'MV'+(i+10)}});const input=await approveInput(s,teacher,{action:'reject',reason:'operator_review',label:undefined,category:undefined,publishedAt:undefined,checks:undefined});await operatorDecision(s,input,now,[source],pepper,actor);const d=await s.db.prepare('SELECT * FROM news_decision_ledger WHERE candidate_id=?').bind(teacher.id).first();await s.db.prepare('UPDATE news_decision_ledger SET verdict=?,decision_features_json=? WHERE decision_id=?').bind(verdict,JSON.stringify({insightsProfile:{...base,articleIdentity:'teacher-a'+i,topicIdentity:'teacher-t'+i}}),d.decision_id).run();}const before=await row(s,target.id),evaluation=await evaluate(s,target.id);assert.equal(evaluation.recommendation,verdict==='approve'?'RECOMMEND_APPROVE':'RECOMMEND_REJECT');assert.equal(evaluation.evidenceCount,5);assert.deepEqual(await row(s,target.id),before);}});
test('human decision stores fresh final-revision evaluation atomically, supports retry and NONE comparison for both verdicts',async()=>{for(const action of ['approve','reject']){const s=await setup(),item=await put(s),initial=await evaluate(s,item.id);const input=await approveInput(s,item,action==='reject'?{action,reason:'not_relevant',label:undefined,category:undefined,publishedAt:undefined,checks:undefined}:{});const result=await operatorDecision(s,input,now+2000,[source],pepper,actor);assert.deepEqual(await operatorDecision(s,input,now+3000,[source],pepper,actor),result);assert.equal(count(s),2);const d=await s.db.prepare('SELECT * FROM news_decision_ledger').first(),f=JSON.parse(d.decision_features_json);assert.notEqual(f.shadowEvaluation.evaluationId,initial.evaluationId);assert.equal(f.shadowEvaluation.generatedAt,now+2000);const metrics=await shadowMetrics(s,now+3000);assert.equal(metrics.evaluatedHumanDecisions,1);assert.equal(metrics.noRecommendation,1);assert.equal(metrics.totalHumanDecisions,1);assert.equal(metrics.lowSample,true);assert.equal(metrics.agreementRate,null);}});
test('failed human feedback transaction also rolls back the pre-decision shadow row',async()=>{const s=await setup(),item=await put(s);await s.db.prepare("CREATE TRIGGER fail_feedback BEFORE INSERT ON news_operator_feedback BEGIN SELECT RAISE(ABORT,'synthetic_failure'); END").run();await assert.rejects(operatorDecision(s,await approveInput(s,item),now,[source],pepper,actor),/decision_transaction_failed/);assert.equal(count(s),0);assert.equal((await row(s,item.id)).review_status,'pending');});
test('risk metrics, coverage and denominator distinguish no recommendation; low-N does not imply readiness',()=>{const cases=[fixture(statuses[0],'approve',0),fixture(statuses[0],'reject',1),fixture(statuses[1],'approve',2),fixture(statuses[1],'reject',3),fixture(statuses[2],'approve',4),fixture(statuses[2],'reject',5)];const m=aggregateShadowMetrics(cases.map(c=>c.ledger),cases.map(c=>c.evaluation),now);assert.equal(m.evaluatedHumanDecisions,6);assert.equal(m.agreement,2);assert.equal(m.falsePublishDirection,1);assert.equal(m.missedPublishDirection,1);assert.equal(m.recommendationCoverage,4/6);assert.equal(m.agreementRate,.5);assert.equal(m.lowSample,true);assert.equal(m.automationEnabled,false);assert.equal(m.patterns[0].evaluatedHumanDecisions,6);});
test('policy/rule versions, stale time, revision and snapshot mismatches never mix; nonhuman teachers excluded',()=>{for(const mutate of [c=>c.ledger.actor_type='automatic_policy',c=>c.evaluation.policy_version='old',c=>c.evaluation.rule_version='old',c=>c.evaluation.candidate_revision=1,c=>c.evaluation.candidate_snapshot='changed',c=>c.evaluation.evaluated_at=now-1800001,c=>c.evaluation.evaluated_at=now+1]){const c=fixture(statuses[0],'approve');mutate(c);assert.equal(aggregateShadowMetrics([c.ledger],[c.evaluation],now).evaluatedHumanDecisions,0);}});
test('duplicate topic/source sightings cannot inflate independent evaluation metrics; newest unmatched human does not reuse older result',()=>{const a=fixture(statuses[0],'approve',0),b=fixture(statuses[0],'approve',1);b.evaluation.profile_json=a.evaluation.profile_json;const m=aggregateShadowMetrics([a.ledger,b.ledger],[a.evaluation,b.evaluation],now);assert.equal(m.matchedHumanDecisions,2);assert.equal(m.independentHumanDecisions,1);const newer={...a.ledger,decision_id:'newer',decided_at:now+1,decision_features_json:'{}'};assert.equal(aggregateShadowMetrics([a.ledger,newer],[a.evaluation],now+2).independentHumanDecisions,0);});
test('batch records NONE for pending only and preserves every candidate and existing ledger row',async()=>{const s=await setup();await put(s,'one');await put(s,'two',{productFacts:null});const before=JSON.stringify(await s.candidates()),ledger=JSON.stringify(await s.db.prepare('SELECT * FROM news_decision_ledger').all());const results=await evaluatePending(s,now,[source],pepper);assert.equal(results.evaluated,2);assert(results.items.every(i=>i.recommendation==='NO_RECOMMENDATION'));assert.equal(JSON.stringify(await s.candidates()),before);assert.equal(JSON.stringify(await s.db.prepare('SELECT * FROM news_decision_ledger').all()),ledger);await evaluatePending(s,now+1000,[source],pepper);assert.equal(count(s),2);});
test('additive shadow migration preserves existing candidate, ledger and controls, and lazy retention affects shadow rows only',async()=>{const s=await setup(),item=await put(s);await operatorDecision(s,await approveInput(s,item),now,[source],pepper,actor);const before=JSON.stringify(await s.candidates()),ledger=JSON.stringify(await s.db.prepare('SELECT * FROM news_decision_ledger').all());const existing=await s.db.prepare('SELECT * FROM news_shadow_evaluations').first();await s.db.prepare('INSERT INTO news_shadow_evaluations VALUES(?,?,?,?,?,?,?,?,?,?)').bind('new-retention',existing.candidate_id,existing.candidate_revision,existing.candidate_snapshot,now+366*86400000,existing.policy_version,existing.rule_version,existing.recommendation,existing.profile_json,existing.evaluation_json).run();assert.equal(count(s),1);assert.equal(JSON.stringify(await s.candidates()),before);assert.equal(JSON.stringify(await s.db.prepare('SELECT * FROM news_decision_ledger').all()),ledger);});
