import test from 'node:test';import assert from 'node:assert/strict';
import {getSource} from '../src/registry.js';import {parseShimamuraProductEvidence,shimamuraProductSurface,SHIMAMURA_PRODUCT_PARSER} from '../src/shimamura-product-evidence.js';import {factualLabel} from '../src/metadata.js';import {recoverySurface,recoveryCacheKey} from '../src/facts-readiness.js';import {parseNamedWorkshopEvidence,namedWorkshopLabel} from '../src/named-workshop-evidence.js';
const source=getSource('shimamura'),row={id:'a'.repeat(64),source_id:'shimamura',source_url:'https://www.shimamura.co.jp/update/amp-effector/2026/10/100001/',published_at:'2026-10-01T15:00:00.000Z',review_status:'pending'};
const html=(title,intro,extra='')=>`<html><head><link rel="canonical" href="${row.source_url}"></head><body><div class="mb-80"><h1>${title}</h1></div><p>公開：<time datetime="2026-10-02">2026/10/02</time></p><p>更新：<time datetime="2026-10-09">2026/10/09</time></p><div class="p-content"><p class="wp-block-paragraph">${intro}</p>${extra}</div></body></html>`;
for(const [name,title,intro,extra,models,contains]of [
 ['Fulltone','Fulltone「Silver Limited Edition OCD V2 / OCD GE」の日本限定発売','Fulltoneより、日本限定モデル「Silver Limited Edition OCD V2」と「Silver Limited Edition OCD GE」が登場しました。各100台の限定生産ペダルです。','<table><tr><td>Silver Limited Edition OCD V2 JANコード：1</td></tr><tr><td>Silver Limited Edition OCD GE JANコード：2</td></tr></table>',['Silver Limited Edition OCD V2','Silver Limited Edition OCD GE'],'日本限定'],
 ['Fender','FenderよりJohn 5のテレキャスターが発売','シグネイチャーモデル「John 5 Ghost Telecaster」と「John 5 Phantom Telecaster」がFenderより登場しました。','<table><tr><td>John 5 Ghost Telecaster JANコード：1</td></tr><tr><td>John 5 Phantom Telecaster JANコード：2</td></tr></table><p class="wp-block-paragraph">関連商品「Pickup 2」のピックアップ</p>',['John 5 Ghost Telecaster','John 5 Phantom Telecaster'],'シグネチャーギター'],
 ['Bacchus','BacchusよりGS-HOLLOW / GS-HOLLOW-CTMが登場','既存モデル「G-STUDIO」をベースにした新シリーズとして、セミホロウの「GS-HOLLOW」と「GS-HOLLOW-CTM」が登場しました。','<h2>GS-HOLLOW</h2><h2>GS-HOLLOW-CTM</h2>',['GS-HOLLOW','GS-HOLLOW-CTM'],'ギター'],
 ['Kikuchi','Kikuchi Guitars「MF15L / MF15L 2HB」が登場','Kikuchi Guitarsよりフルアコースティックギター「MF15L」と「MF15L 2HB」が登場しました。','',['MF15L','MF15L 2HB'],'ギター'],
 ['Baggs','L.R. Baggs「HiFi DNA」が発売','Baggsよりアコースティックギター用ピックアップ「HiFi DNA」が登場します。','',['HiFi DNA'],'ギター用ピックアップ'],
 ['buddy','Limetone Audio「buddy」の限定カラーが登場','Limetone Audioよりディレイペダル「buddy」の200台限定カラーモデルが登場しました。','',['buddy'],'限定カラー'],
 ['Antares','Antares AutoTune Advanced | ピッチ補正プラグイン','Antares Audio Technologiesからプラグイン「AutoTune Advanced」が発表されました。','<h2>AutoTune Advanced</h2>',['AutoTune Advanced'],'プラグイン'],
 ['unseen manufacturer','Synthetic Audio「ZX-201」の限定カラーが登場','Synthetic Audioよりエフェクター「ZX-201」の限定カラーモデルが登場しました。','',['ZX-201'],'限定カラー']
])test('source-bound generic extraction: '+name,()=>{const out=parseShimamuraProductEvidence(html(title,intro,extra),source,row);assert.deepEqual(out.productFacts.models,models);assert.ok(factualLabel(out.productFacts,out.eventType).includes(contains));assert.equal(out.publishedAt,row.published_at);assert.ok(!JSON.stringify(out).includes(intro));assert.ok(!JSON.stringify(out).includes(title));});
for(const title of ['再入荷','セール','レビュー','比較','旧製品','在庫処分','交換用','ケース','発売しない'])test('reject unsafe primary '+title,()=>assert.throws(()=>parseShimamuraProductEvidence(html(`Synthetic Audio「ZX-201」${title}`, 'Synthetic Audioよりペダル「ZX-201」が登場しました。'),source,row)));
test('brand-only / unrelated model / no event / category-only type do not become facts',()=>{for(const [t,p]of [['Synthetic Audioのニュース','Synthetic Audioよりエフェクターが登場しました。'],['Synthetic Audio「ZX-200」が登場','Synthetic Audioよりエフェクター「ZX-201」が登場しました。'],['Synthetic Audio「ZX-201」','Synthetic Audioのエフェクター「ZX-201」を紹介します。'],['Synthetic Audio「ZX-201」が登場','Synthetic Audioより「ZX-201」が登場しました。']])assert.throws(()=>parseShimamuraProductEvidence(html(t,p),source,row));});
test('canonical, original publication date, robots, hidden content, related cards stay fail-closed',()=>{const good=html('Synthetic Audio「ZX-201」が登場','Synthetic Audioよりペダル「ZX-201」が登場しました。');for(const bad of [good.replace(row.source_url,'https://evil.example/'),good.replace('datetime="2026-10-02"','datetime="2026-10-03"'),good.replace('<head>','<head><meta name="robots" content="noindex">'),good.replace('class="wp-block-paragraph"','class="wp-block-paragraph" hidden'),html('Synthetic Audio「ZX-201」が登場','対象を確認中です。','<aside><p class="wp-block-paragraph">Synthetic Audioよりペダル「ZX-201」が登場しました。</p></aside>')])assert.throws(()=>parseShimamuraProductEvidence(bad,source,row));});
test('future recheck uses per-candidate generic parser; other sources cannot borrow its proof',()=>{const surface=recoverySurface(row,source,{primaryRecovery:true});assert.equal(surface.parser,SHIMAMURA_PRODUCT_PARSER);assert.ok(recoveryCacheKey(row,source,surface).endsWith(row.id));assert.equal(shimamuraProductSurface({...row,source_id:'ikebe'},source),null);assert.equal(shimamuraProductSurface(row,{...source,discoveryUrl:'https://evil.example/'}),null);});
const eventSource=getSource('ikebe-event'),eventRow={source_id:'ikebe-event',source_url:'https://www.ikebe-gakki.com/blog/synthetic-workshop/',published_at:row.published_at};
const eventHtml=`<link rel="canonical" href="${eventRow.source_url}"><article id="main"><h1>合成奏者 ギターワークショップ</h1><time datetime="2026-10-02">Published:2026-10-02</time><h3>開催日時</h3><p>2026年10月21日（水）</p><h3>会場</h3><p>イケシブ LIVES</p><h3>講師</h3><h2>合成奏者</h2></article><aside><time datetime="2026-01-01">Published:2026-01-01</time></aside>`;
test('named workshop uses explicit instructor, venue and event date; related article dates excluded',()=>{const out=parseNamedWorkshopEvidence(eventHtml,eventSource,eventRow);assert.equal(out.productFacts.artist,'合成奏者');assert.equal(out.productFacts.eventDate,'2026-10-21');assert.ok(factualLabel(out.productFacts,out.eventType).includes('10月21日'));for(const bad of [eventHtml.replace('2026年10月21日','不明'),eventHtml.replace('<h2>合成奏者</h2>','<h2>別人奏者</h2>'),eventHtml.replace('ギターワークショップ','ギターワークショップ中止')])assert.throws(()=>parseNamedWorkshopEvidence(bad,eventSource,eventRow));assert.equal(namedWorkshopLabel({...out.productFacts,listingSource:'other'}),null);});
test('failed listing escalates to two bounded primary requests; actual trigger keeps pending, proof and teachers safe',async()=>{const {setup,put,now}=await import('./operator-case.js'),{pepper}=await import('./helpers.js'),{hash}=await import('../src/policy.js'),{recheckFacts}=await import('../src/facts-recheck.js'),{candidateSnapshot}=await import('../src/operator-review.js'),{resolvedRecoverySurface}=await import('../src/facts-readiness.js');const s=await setup(),robot='User-agent: *\nAllow: /',a={...source,enabled:true,productionEnabled:true,robotsHash:await hash(robot)},id=await hash(row.source_url);const item=await put(s,'synthetic',{id,sourceUrl:row.source_url,normalizedUrl:row.source_url,publishedAt:row.published_at,productFacts:null,eventType:'other'});await s.db.prepare("INSERT INTO news_facts_rechecks(request_id,request_payload_hash,candidate_id,checked_at,outcome,provenance_json) VALUES(?,?,?,?,'facts_not_recovered','[]')").bind(crypto.randomUUID(),'a'.repeat(64),id,now-1000).run();const before=await s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(id).first();assert.equal((await resolvedRecoverySurface(s,before,a)).parser,SHIMAMURA_PRODUCT_PARSER);const calls=[],result=await recheckFacts(s,{id,revision:before.review_revision,snapshot:await candidateSnapshot(before),requestId:crypto.randomUUID()},now,[a],pepper,{type:'system_recheck',id:'test'},{sleep:async()=>{},fetcher:async(u,o)=>{assert.equal(o.redirect,'manual');assert.equal(o.credentials,'omit');calls.push(u);return new Response(u===a.robotsUrl?robot:html('Synthetic Audio「ZX-201」の限定カラーが登場','Synthetic Audioよりエフェクター「ZX-201」の限定カラーモデルが登場しました。'),{headers:{'Content-Type':'text/html'}});}});assert.equal(result.validation.valid,true);assert.deepEqual(calls,[a.robotsUrl,row.source_url]);const after=await s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(id).first();assert.equal(after.review_status,'pending');assert.equal(after.published_at,before.published_at);assert.ok(JSON.parse(after.facts_provenance).every(p=>p.sourceUrl===row.source_url&&p.parserVersion===SHIMAMURA_PRODUCT_PARSER));for(const table of ['news_decision_ledger','news_operator_feedback'])assert.equal((await s.db.prepare('SELECT COUNT(*) n FROM '+table).first()).n,0);const listing=after;await s.put({...item,productFacts:{brand:'Synthetic Audio',product:'ZX-201',version:null,category:'amps_effects'},category:'amps_effects'});assert.deepEqual(await s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(id).first(),listing);});
