import test from 'node:test';import assert from 'node:assert/strict';
import {setup,put,source,now} from './operator-case.js';import {pepper} from './helpers.js';
import {initializePending,runPendingRechecks,setPublishInterest,lifecycleView,objectiveBlock,nextRecheck,recheckOutcome} from '../src/pending-lifecycle.js';
import {candidateSnapshot} from '../src/operator-review.js';
const DAY=86400000,registry=[source],actor={type:'human_operator',id:'access:synthetic-human'};
const row=(s,id)=>s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(id).first();
const run=(s,extra={})=>runPendingRechecks(s,now,registry,pepper,{recover:async()=>({outcome:'facts_unchanged'}),...extra});
test('initialization is additive, due is leased/idempotent and not-due is skipped; unknown facts never reject',async()=>{const s=await setup();await put(s,'one',{productFacts:null});const before=JSON.stringify(await s.candidates());await initializePending(s,now);await initializePending(s,now);assert.equal((await run(s)).items[0].result,'NO_NEW_EVIDENCE');assert.equal((await run(s)).due,0);assert.equal(JSON.stringify(await s.candidates()),before);assert.equal(s.db.raw.prepare('SELECT COUNT(*) n FROM news_decision_ledger').get().n,0);assert.equal((await lifecycleView(s,await row(s,'one'),now)).recheck_attempt_count,1);});
test('interest priority/cancel, stale input denied and intent never creates teacher or changes candidate',async()=>{const s=await setup();await put(s,'one',{productFacts:null});await put(s,'two',{productFacts:null});const r=await row(s,'two'),input={id:r.id,revision:r.review_revision,snapshot:await candidateSnapshot(r),interest:true};const before=JSON.stringify(await s.candidates());assert.equal((await setPublishInterest(s,input,now,registry,pepper,actor)).user_publish_interest,1);const a=await run(s,{limit:1});assert.equal(a.items[0].id,'two');assert.equal((await setPublishInterest(s,{...input,interest:false},now+1,registry,pepper,actor)).user_publish_interest,0);await assert.rejects(setPublishInterest(s,{...input,revision:10},now,registry,pepper,actor),/candidate_changed/);assert.equal(JSON.stringify(await s.candidates()),before);assert.equal(s.db.raw.prepare('SELECT COUNT(*) n FROM news_decision_ledger').get().n,0);});
test('objective duplicates/policy/expiry block without fetch or human reject; ambiguous errors do not',async()=>{for(const variant of ['duplicate','policy','expiry']){const s=await setup(),a=await put(s,'a');await put(s,'b',{productFacts:null});if(variant==='duplicate'){await s.db.prepare("UPDATE candidate_items SET review_status='approved' WHERE id='a'").run();await s.db.prepare("UPDATE candidate_items SET topic_key=? WHERE id='b'").bind(a.topicKey).run();}if(variant==='policy')await s.db.prepare("UPDATE candidate_items SET publication_decision='REJECT' WHERE id='b'").run();if(variant==='expiry')await s.db.prepare("UPDATE candidate_items SET expires_at=? WHERE id='b'").bind(now-1).run();let fetched=false;const out=await run(s,{recover:async()=>{fetched=true;throw Error('must_not_fetch');}});assert(out.items.find(i=>i.id==='b').result.endsWith('CONFIRMED'));assert.equal((await row(s,'b')).review_status,'pending');assert.equal(s.db.raw.prepare('SELECT COUNT(*) n FROM news_decision_ledger').get().n,0);}
 assert.equal(objectiveBlock({expires_at:now+DAY},{errors:['facts_incomplete','operator_source_gate','event_validation_failed']},now),null);});
test('ready recovery saves only latest revision Shadow, does not approve, still-blocked recovery schedules retry',async()=>{for(const valid of [true,false]){const s=await setup();const i=await put(s,'target',{productFacts:null});const full={brand:'SHURE',product:'MV6',category:'recording_audio',identifierBasis:'explicit_model_code'};const out=await run(s,{recover:async()=>{await s.db.prepare('UPDATE candidate_items SET product_facts=?,review_revision=review_revision+1 WHERE id=?').bind(JSON.stringify(valid?full:{...full,scopeUncertain:true}),i.id).run();return {recovered:true,outcome:'facts_recovered'};}});assert.equal(out.items[0].result,valid?'RECOVERED_READY':'RECOVERED_STILL_BLOCKED');assert.equal((await row(s,i.id)).review_status,'pending');const sh=await s.db.prepare('SELECT * FROM news_shadow_evaluations WHERE candidate_id=?').bind(i.id).first();assert.equal(sh.candidate_revision,(await row(s,i.id)).review_revision);assert.equal(sh.candidate_snapshot,await candidateSnapshot(await row(s,i.id)));}});
test('temporary failures/parser errors/404 stay pending; backoff increases; long pending not rejected',async()=>{for(const error of ['facts_timeout','facts_parser_failure','facts_http_404']){const s=await setup();await put(s,'failure',{productFacts:null,collectedAt:'2026-09-01T00:00:00.000Z'});const out=await run(s,{recover:async()=>({outcome:error})});assert.equal(out.items[0].result,error==='facts_http_404'?'PERMANENT_INVALID':'TEMPORARY_FETCH_FAILURE');const state=await lifecycleView(s,await row(s,'failure'),now);assert(state.next_recheck_at>now);assert(state.longPending);assert.equal((await row(s,'failure')).review_status,'pending');}assert(nextRecheck({expires_at:now+90*DAY},4,now)>nextRecheck({expires_at:now+90*DAY},1,now));assert.equal(recheckOutcome({outcome:'facts_http_410'},{valid:false}),'PERMANENT_INVALID');});
test('concurrent claims execute recovery once; revision changes requeue state; unsupported source does not fetch',async()=>{const s=await setup();await put(s,'race',{productFacts:null});let calls=0;await Promise.all([run(s,{recover:async()=>{calls++;return {outcome:'facts_unchanged'};}}),run(s,{recover:async()=>{calls++;return {outcome:'facts_unchanged'};}})]);assert.equal(calls,1);await s.db.prepare("UPDATE candidate_items SET review_revision=review_revision+1 WHERE id='race'").run();await initializePending(s,now+1);assert.equal((await lifecycleView(s,await row(s,'race'),now+1)).next_recheck_at,now+1);});
test('source publisher budget avoids repeated original fetch; unsupported surface and gate remain pending',async()=>{const s=await setup();await put(s,'budget',{productFacts:null});await s.db.prepare('INSERT OR IGNORE INTO source_state(source_id) VALUES(?)').bind(source.id).run();await s.db.prepare('UPDATE source_state SET last_publisher_request_at=? WHERE source_id=?').bind(now,source.id).run();let requests=0;await run(s,{recover:async()=>{requests++;return {};}});assert.equal(requests,0);assert.equal((await row(s,'budget')).review_status,'pending');});
test('leased scheduler failure preserves candidates and releases for bounded retry',async()=>{const s=await setup();await put(s,'broken',{productFacts:null});const before=JSON.stringify(await s.candidates());const out=await run(s,{recover:async()=>{throw Error('facts_timeout');}});assert.equal(out.items[0].result,'TEMPORARY_FETCH_FAILURE');assert.equal(JSON.stringify(await s.candidates()),before);assert.equal((await s.db.prepare('SELECT lease_until FROM news_pending_lifecycle').first()).lease_until,0);});
test('hourly scheduler integrates bounded rechecks before existing retention, independent of collection publication',async()=>{const s=await setup();await put(s,'hourly',{productFacts:null});const {scheduledNews,RETENTION_CRON}=await import('../src/scheduled.js');let requests=0;const env={NEWS_DB:s.db,NEWS_COLLECTION_MODE:'production',NEWS_SOURCE_IDS:'["shimamura"]',NEWS_HEADLINE_PEPPER:pepper};await scheduledNews({cron:RETENTION_CRON},env,{},now,{registry:[source],fetcher:async()=>{requests++;return new Response('User-agent: *\nDisallow: /',{headers:{'content-type':'text/plain'}});},sleep:async()=>{}});const count=requests;await scheduledNews({cron:RETENTION_CRON},env,{},now+1000,{registry:[source],fetcher:async()=>{requests++;throw Error('unexpected_retry');}});assert.equal(requests,count);assert.equal((await row(s,'hourly')).review_status,'pending');assert.equal(s.db.raw.prepare('SELECT COUNT(*) n FROM news_decision_ledger').get().n,0);});
