import test from 'node:test';import assert from 'node:assert/strict';
import {parseIkebeInformationalEvidence,validatedProductArticle,productArticleLabel,productArticleSurface} from '../src/product-article-evidence.js';
import {getSource} from '../src/registry.js';import {factualLabel,factualTopicKey} from '../src/metadata.js';import {setup,put,now} from './operator-case.js';import {pepper} from './helpers.js';import {runPendingRechecks} from '../src/pending-lifecycle.js';import {hash} from '../src/policy.js';import {reviewDetail} from '../src/operator-review.js';import {publicationValidation} from '../src/decision-policy.js';
const source=getSource('ikebe'),url='https://www.ikebe-gakki-pb.com/new_product/172830/',date='2026-09-30T15:00:00.000Z';
const yamaha={brand:'YAMAHA',models:['TDM-600GY','TDM-600BE'],title:'YAMAHA、日々の練習を支えるTDM-600の機能',paragraphs:['TDM-600は、コンパクトタイプのチューナーメトロノーム。音をそろえる基礎づくりを日々の練習から支えるモデルです。','チューナーとメトロノームを使って練習し、ピッチとリズムとテンポを整えられます。音程の確認とテンポ表示を同時に行い、練習の基礎を確認できます。視覚的なテンポ表示と音程測定を組み合わせ、毎日の演奏に役立てられます。']};
const lava={brand:'LAVA MUSIC',models:['SmartAmp','LAVA STUDIO Stand','Effects Pedal'],title:'LAVA MUSIC、自宅で創る・奏でる・録る',paragraphs:['LAVA STUDIOは、ギターの音作り、練習、録音、楽曲制作を1台で行えるデスクトップ音楽ワークステーションです。アンプ、エフェクター、スピーカー、ルーパー、最大12トラックのminiDAWを搭載しています。','ギタリストが自宅で練習や録音を行うため、ヘッドフォンでの音作りとルーパー、プリセットを活用できます。ギターの演奏から楽曲制作まで幅広い用途で使える機材です。'],accessory:'LAVA STUDIO専用の高さ調整スタンドや対応ペダル。自宅での練習と操作を支える周辺機器として使用します。'};
function row(o=yamaha){return {source_id:'ikebe',source_url:url,review_status:'pending',event_type:'other',published_at:date,product_facts:JSON.stringify({identifierBasis:'explicit_article_component_fields',listingSource:'ikebe',articleUrl:url,brand:o.brand,product:o.models.length>1&&o!==lava?o.models.join(' / '):o.models[0]})};}
const html=(o=yamaha)=>`<link rel="canonical" href="${url}"><article id="main"><div class="blog_title"><h1>${o.title}</h1><time class="sub_info_date" datetime="2026-10-01">2026年10月01日公開</time><a href="${source.discoveryUrl}tag/craft/">${o.brand}</a></div><div class="main_wrap">${o.models.map((m,i)=>`<h1 class="wp-block-heading">${o.brand}<br>${m}</h1><p class="wp-block-paragraph">販売価格は税込99,000円。販売ページはこちら。</p>${(i===0?o.paragraphs:[o.accessory||o.paragraphs[0]]).map(p=>`<p class="wp-block-paragraph">${p}</p>`).join('')}`).join('')}</div><aside><p>関連記事の発売情報</p></aside></article>`;
const parse=(o=yamaha,h=html(o))=>parseIkebeInformationalEvidence(h,source,row(o));
test('Yamaha functional product information, not an invented new product event',()=>{const x=parse();assert.equal(x.eventType,'product_article');assert.equal(x.productFacts.articleType,'product_information');assert.equal(x.productFacts.theme,'practice_tools');assert.deepEqual(x.productFacts.models,yamaha.models);assert.equal(factualLabel(x.productFacts,x.eventType),'YAMAHA、チューナー・メトロノーム「TDM-600GY / TDM-600BE」を紹介');assert(!/発売|発表|新製品/.test(productArticleLabel(x.productFacts)));assert(!JSON.stringify(x).includes(yamaha.paragraphs[0]));});
test('LAVA multi-product article keeps exact sections and accessories; no unsupported alias',()=>{const x=parse(lava);assert.equal(x.productFacts.articleType,'gear_information');assert.equal(x.productFacts.product,'SmartAmp');assert.deepEqual(x.productFacts.models,lava.models);assert.deepEqual(x.productFacts.components.map(p=>p.role),['product','accessory','accessory']);assert.equal(x.productFacts.aliases,undefined);assert.match(factualLabel(x.productFacts,x.eventType),/SmartAmp.*LAVA STUDIO Stand.*Effects Pedal.*を紹介$/);});
test('unknown manufacturer/model uses identical generic pathway',()=>{const o={...yamaha,brand:'Craft Lab',models:['RX-700A','RX-700B'],title:'Craft Lab RX-700の練習ツール紹介',paragraphs:yamaha.paragraphs.map(p=>p.replaceAll('TDM-600','RX-700'))};assert.equal(parse(o).productFacts.brand,'Craft Lab');});
for(const [word,type]of [['レビュー','review'],['試奏','hands_on'],['特集','feature'],['解説','explainer']])test('explicit article type '+type+' uses non-event verb',()=>{const x=parse({...yamaha,title:yamaha.title+' '+word});assert.equal(x.productFacts.articleType,type);assert(productArticleLabel(x.productFacts).endsWith('を'+word));});
for(const title of ['YAMAHA製品が新発売','YAMAHA TDM-600を発表','YAMAHA TDM-600新色','YAMAHA TDM-600再入荷','YAMAHA TDM-600在庫情報','YAMAHA TDM-600セール','YAMAHA TDM-600広告 PR記事','YAMAHA TDM-600比較','YAMAHA旧製品の案内'])test('do not reroute launch or low-value context: '+title,()=>assert.throws(()=>parse({...yamaha,title}),/facts_scope_uncertain/));
test('bare brand, model list, commerce-only and related/hidden prose cannot prove relevance',()=>{
 for(const paragraphs of [['YAMAHAは楽器メーカーです。','TDM-600の製品ページです。'],['販売価格は税込99,000円。','ご購入はこちら。'],['TDM-600、RX700、RX701、100、200の型番一覧です。','メーカーの製品が多数あります。']])assert.throws(()=>parse({...yamaha,paragraphs}),/facts_scope_uncertain/);
 for(const h of [html().replaceAll('class="wp-block-paragraph"','class="related"'),html().replaceAll('class="wp-block-paragraph"','class="wp-block-paragraph" hidden'),html().replace('class="main_wrap"','class="main_wrap" hidden')])assert.throws(()=>parse(yamaha,h),/facts_/);
 assert.throws(()=>parse({...yamaha,title:'YAMAHA、練習ツールの機能紹介',paragraphs:yamaha.paragraphs.map(s=>s.replaceAll('TDM-600','OTHER-99'))}),/facts_identity_changed/);
});
test('no announcement fallback through body, no unbound accessories, exact date and canonical',()=>{
 assert.throws(()=>parse({...yamaha,paragraphs:[...yamaha.paragraphs,'TDM-600を新発売しました。']}),/facts_scope_uncertain/);
 assert.throws(()=>parse(lava,html(lava).replaceAll('専用','別売').replaceAll('対応','別売')),/facts_identity_changed/);
 assert.throws(()=>parse(yamaha,html().replace('datetime="2026-10-01"','datetime="2026-10-02"')),/facts_date_changed/);
 assert.throws(()=>parse(yamaha,html().replace('<link rel="canonical"','<link rel="other"')),/facts_source_invalid/);
 assert.throws(()=>parse(yamaha,'<meta name="robots" content="noarchive">'+html()),/facts_optout/);
 assert.throws(()=>parse(yamaha,'x'.repeat(512001)),/facts_response_too_large/);
});
test('article validation fails on unknown type, theme, role, scope and fabricated event',()=>{const f=parse().productFacts;for(const patch of [{articleType:'new_product'},{theme:'generic'},{relevance:'unrelated'},{scopeUncertain:true},{releaseEvent:{}},{productEvent:{}},{components:[{model:f.models[0],role:'unknown'}]},{models:['<script>']},{identifierBasis:'unverified'}])assert.equal(validatedProductArticle({...f,...patch}),false);assert.equal(factualLabel(f,'release'),null);assert.equal(factualLabel(f,'other'),null);assert.equal(productArticleLabel(null),null);assert.equal(productArticleSurface({...row(),event_type:'release'},source),null);});
async function prepare(o=yamaha){const s=await setup(),robot='User-agent: *\nAllow: /',a={...source,enabled:true,productionEnabled:true,robotsHash:await hash(robot)},item=await put(s,'non-event',{id:await hash(url),sourceId:a.id,sourceName:a.name,sourceUrl:url,normalizedUrl:url,publishedAt:date,eventType:'other',category:'amps_effects',productFacts:JSON.parse(row(o).product_facts)});await s.recordHealth({sourceId:a.id,status:'healthy',reasonCode:'ok',checkedAt:now,successfulAt:now});const before=await s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(item.id).first();return {s,a,item,before,options:{sleep:async()=>{},fetcher:async u=>new Response(u===a.robotsUrl?robot:html(o),{headers:{'Content-Type':'text/html'}})}};}
for(const [name,o]of [['YAMAHA',yamaha],['LAVA',lava]])test(name+' autonomous recovery becomes READY, pending stays pending, no teacher/public writes',async()=>{const c=await prepare(o),r=await runPendingRechecks(c.s,now,[c.a],pepper,c.options);assert.equal(r.recovered,1);assert.equal(r.newlyReady,1);const d=await reviewDetail(c.s,c.item.id,now,[c.a],pepper);assert.equal(d.factsReview.recoveryClass,'READY_FOR_HUMAN_DECISION');assert.deepEqual(d.validation.errors,[]);assert.equal(d.facts.models.length,o.models.length);const after=await c.s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(c.item.id).first();for(const k of ['published_at','expires_at','source_url','title_fingerprint','review_status','publication_decision'])assert.equal(after[k],c.before[k]);assert.equal(after.review_status,'pending');for(const t of ['news_decision_ledger','news_operator_feedback'])assert.equal((await c.s.db.prepare(`SELECT COUNT(*) n FROM ${t}`).first()).n,0);assert.equal((await c.s.db.prepare('SELECT count(*) n FROM news_shadow_evaluations').first()).n,1);});
test('duplicate information article blocked; independent launch and different theme remain separate',async()=>{const c=await prepare();await runPendingRechecks(c.s,now,[c.a],pepper,c.options);const row=await c.s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(c.item.id).first(),f=JSON.parse(row.product_facts);const other=await put(c.s,'duplicate',{productFacts:f,category:'amps_effects',eventType:'product_article'});await c.s.db.prepare("UPDATE candidate_items SET review_status='approved' WHERE id=?").bind(other.id).run();assert((await publicationValidation(c.s,row,now,[c.a],pepper)).errors.includes('duplicate'));await c.s.db.prepare("UPDATE candidate_items SET event_type='release' WHERE id=?").bind(other.id).run();assert((await publicationValidation(c.s,row,now,[c.a],pepper)).valid);await c.s.db.prepare("UPDATE candidate_items SET event_type='product_article',product_facts=? WHERE id=?").bind(JSON.stringify({...f,articleType:'review'}),other.id).run();assert((await publicationValidation(c.s,row,now,[c.a],pepper)).valid);});
test('source/date/fingerprint/health checks preserved for informational articles',async()=>{const c=await prepare();await runPendingRechecks(c.s,now,[c.a],pepper,c.options);const row=await c.s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(c.item.id).first(),f=JSON.parse(row.product_facts);for(const patch of [{source_id:'shimamura'},{source_url:'https://evil.test/x/'},{title_fingerprint:'{}'},{published_at:null},{facts_provenance:'[]'},{product_facts:JSON.stringify({...f,articleUrl:url.replace('172830','99999')})}])assert.equal((await publicationValidation(c.s,{...row,...patch},now,[c.a],pepper)).valid,false);});

test('article identity includes full model scope/type/theme, existing launch identity unchanged',()=>{const f=parse().productFacts;assert.notEqual(factualTopicKey(f,'product_article'),factualTopicKey({...f,articleType:'review'},'product_article'));assert.notEqual(factualTopicKey(f,'product_article'),factualTopicKey({...f,models:[f.models[0]]},'product_article'));assert.equal(factualTopicKey(f,'release'),factualTopicKey(f,'new_product'));});
test('weaker listing rediscovery cannot overwrite verified informational facts or publish status',async()=>{const c=await prepare();await runPendingRechecks(c.s,now,[c.a],pepper,c.options);const before=await c.s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(c.item.id).first();await c.s.put({...c.item,productFacts:null,eventType:'other',label:'listing only'});const after=await c.s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(c.item.id).first();for(const key of ['product_facts','event_type','label','published_at','review_status','review_revision','facts_provenance'])assert.equal(after[key],before[key]);});

test('new pending article without prior recovered facts uses primary extraction, never metadata-only approval',async()=>{const c=await prepare();await c.s.db.prepare('UPDATE candidate_items SET product_facts=NULL WHERE id=?').bind(c.item.id).run();const r=await runPendingRechecks(c.s,now,[c.a],pepper,c.options);assert.equal(r.newlyReady,1);assert.equal((await reviewDetail(c.s,c.item.id,now,[c.a],pepper)).factsReview.recoveryClass,'READY_FOR_HUMAN_DECISION');});
