import test from 'node:test';import assert from 'node:assert/strict';
import {parseShimamuraEventEvidence,explicitIntroEvent,shimamuraEventSurface} from '../src/shimamura-event-evidence.js';
import {getSource} from '../src/registry.js';import {setup,put,now} from './operator-case.js';import {pepper} from './helpers.js';import {hash} from '../src/policy.js';import {decisionInput,fixtureActor} from './operator-fixtures.js';import {recheckFacts} from '../src/facts-recheck.js';import {reviewDetail} from '../src/operator-review.js';
const fixtures={flpad:{url:'https://www.shimamura.co.jp/update/dtm-recording/2026/10/91045/',day:'2026-10-02',facts:{brand:'Novation',product:'FLpad',version:null,category:'recording_audio'},title:'Novation FLpad / FLpad Mini | パッドコントローラー',lead:'Novation (ノベーション) が、パッドコントローラー「FLpad」「FLpad Mini」を発売します。',event:'release'},gibson:{url:'https://www.shimamura.co.jp/update/guitar-bass/2026/10/89963/',day:'2026-10-01',facts:{brand:'Gibson',product:'SJ-200 / Hummingbird',version:null,category:'acoustic_guitar'},title:'Gibson「SJ-200」「Hummingbird」にコア材仕様がラインナップ',lead:'ギブソン・カスタムより「SJ-200 エレガント・コア」と「ハミングバード エレガント・コア」が登場しました。',event:'new_product'}};
const source={...getSource('shimamura'),enabled:true,productionEnabled:true};
const row=f=>({source_id:'shimamura',source_url:f.url,product_facts:JSON.stringify(f.facts),category:f.facts.category,published_at:new Date(f.day+'T00:00:00+09:00').toISOString(),review_status:'pending',event_type:'other'});
const html=(f,lead=f.lead)=>`<div class="mb-80"><h1>${f.title}</h1><time datetime="${f.day}">${f.day}</time></div><div class="p-content mb-100">${f===fixtures.gibson?'<h2>概要</h2>':''}<p class="wp-block-paragraph">${lead}</p><h2>特徴</h2><p class="wp-block-paragraph">以前、別の製品が登場しました。</p></div><div><h1>詳細</h1></div>`;
for(const [name,f]of Object.entries(fixtures))test(name+' explicit primary introduction preserves product/date, uses generated event',()=>{const result=parseShimamuraEventEvidence(html(f),source,row(f));assert.deepEqual(result.productFacts,f.facts);assert.equal(result.eventType,f.event);assert.equal(result.publishedAt,row(f).published_at);assert(!JSON.stringify(result).includes(f.lead));});
test('common explicit grammar accepts announcement/release only; mention, uncertain/historical/negative wording fail closed',()=>{for(const [lead,event]of [['NovationがFLpadを発売します。','release'],['メーカーが製品をリリースしました。','release'],['メーカーが製品を発表しました。','new_product'],['モデルが新たに登場しました。','new_product']])assert.equal(explicitIntroEvent(lead),event);for(const lead of ['製品があります。','製品を発売するかもしれません。','製品を発売しません。','製品を発売する予定です。','以前、製品を発売しました。','製品があります。他社製品を発売します。','製品を発売しますという噂です。','製品を再入荷しました。','1960年に製品が登場しました。'])assert.throws(()=>explicitIntroEvent(lead),/facts_scope_uncertain/);});
test('multiple products require both identities, same subject and direct introduction; related body and hidden evidence cannot supply event',()=>{const f=fixtures.gibson;for(const lead of ['ギブソンのSJ-200が登場しました。','別のメーカーからSJ-200とハミングバードが登場しました。','ギブソンSJ-200とハミングバードを紹介します。'])assert.throws(()=>parseShimamuraEventEvidence(html(f,lead),source,row(f)),/facts_/);assert.throws(()=>parseShimamuraEventEvidence(html(f).replace('class="wp-block-paragraph"','class="wp-block-paragraph" hidden'),source,row(f)),/facts_/);assert.throws(()=>parseShimamuraEventEvidence(html(f).replace(f.lead,'製品の仕様です。'),source,row(f)),/facts_/);assert.throws(()=>parseShimamuraEventEvidence(html(f).replace('<h2>特徴</h2>',`<p class="wp-block-paragraph">${f.lead}</p><h2>特徴</h2>`),source,row(f)),/facts_scope_uncertain/);});
test('date, identity, optout, unsupported URL and oversized response stay blocked',()=>{const f=fixtures.flpad;assert.throws(()=>parseShimamuraEventEvidence(html(f),source,{...row(f),published_at:'2026-10-01T00:00:00.000Z'}),/facts_date_changed/);assert.throws(()=>parseShimamuraEventEvidence('<meta name="robots" content="noarchive">'+html(f),source,row(f)),/facts_optout/);assert.throws(()=>parseShimamuraEventEvidence(html(f),source,{...row(f),product_facts:'null'}),/facts_identity_changed/);assert.throws(()=>parseShimamuraEventEvidence('x'.repeat(512001),source,row(f)),/facts_response_too_large/);assert.equal(shimamuraEventSurface({...row(f),source_url:f.url.replace('91045','99999')},source),null);});
async function liveCase(f,hook){const s=await setup(),robot='User-agent: *\nAllow: /',a={...source,robotsHash:await hash(robot)},r=row(f),id=await hash(f.url),item=await put(s,'event',{id,sourceUrl:f.url,normalizedUrl:f.url,publishedAt:r.published_at,category:f.facts.category,productFacts:f.facts,eventType:'other'}),before=await s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(id).first(),input=await decisionInput(s,{id});let calls=0;const run=()=>recheckFacts(s,{id,requestId:input.requestId,snapshot:input.snapshot,revision:input.revision},now,[a],pepper,fixtureActor,{sleep:async()=>{},fetcher:async url=>{calls++;assert([a.robotsUrl,f.url].includes(url));if(url===f.url&&hook)await hook(s,id);return new Response(url===a.robotsUrl?robot:html(f),{headers:{'Content-Type':'text/html'}});}});return {s,id,a,before,input,run,calls:()=>calls};}
for(const [name,f]of Object.entries(fixtures))test(name+' actual recovery CAS/provenance/validation: pending only, Ledger/Shadow unchanged',async()=>{const c=await liveCase(f),result=await c.run();assert(result.recovered);assert(result.validation.valid);assert.equal(result.validation.publishableLabel,`${f.facts.brand}、${f.facts.product}${f.event==='release'?'を発売':'を発表'}`);const d=await reviewDetail(c.s,c.id,now,[c.a],pepper);assert.equal(d.factsReview.recoveryClass,'READY_FOR_HUMAN_DECISION');assert.equal(d.status,'pending');assert.equal(d.revision,1);assert(d.factsReview.provenance.some(p=>p.factField==='event_type'));assert(d.factsReview.provenance.every(p=>p.sourceUrl===f.url&&p.verifiedAt===now&&p.parserVersion==='shimamura-intro-event-2'&&/^[a-f0-9]{64}$/.test(p.responseHash)));const after=await c.s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(c.id).first();assert.equal(after.product_facts,c.before.product_facts);for(const k of ['published_at','source_url','category','publication_decision','title_fingerprint'])assert.equal(after[k],c.before[k]);for(const table of ['news_decision_ledger','news_shadow_evaluations','news_operator_feedback'])assert.equal((await c.s.db.prepare(`SELECT COUNT(*) n FROM ${table}`).first()).n,0);assert((await c.run()).replayed);assert.equal(c.calls(),2);});
test('concurrent candidate edit invalidates full-row CAS and cannot be overwritten',async()=>{const c=await liveCase(fixtures.flpad,async(s,id)=>{await s.db.prepare('UPDATE candidate_items SET label=? WHERE id=?').bind('Concurrent label',id).run();});await assert.rejects(c.run(),/candidate_changed/);assert.equal((await c.s.db.prepare('SELECT COUNT(*) n FROM news_facts_rechecks').first()).n,0);assert.equal((await c.s.db.prepare('SELECT COUNT(*) n FROM news_decision_ledger').first()).n,0);});

test('assessed overview shape permits following specifications but never borrows their event',()=>{const f=fixtures.gibson,specs='<p class="wp-block-paragraph">木材とピックアップの仕様です。</p><p class="wp-block-paragraph">L.R. Baggsを搭載しています。</p>';const text=html(f).replace('<h2>特徴</h2>',specs+'<h2>特徴</h2>');assert.equal(parseShimamuraEventEvidence(text,source,row(f)).eventType,'new_product');assert.throws(()=>parseShimamuraEventEvidence(text.replace(f.lead,'ギブソンのSJ-200とハミングバードの仕様です。'),source,row(f)),/facts_scope_uncertain/);assert.throws(()=>parseShimamuraEventEvidence(text.replace('木材とピックアップの仕様です。','発売を延期しました。'),source,row(f)),/facts_scope_uncertain/);});
