import {fixtureDecision as operatorDecision} from './operator-fixtures.js';
import test from 'node:test';import assert from 'node:assert/strict';
import{database,store,pepper}from'./helpers.js';import{getSource}from'../src/registry.js';import{hash}from'../src/policy.js';
import{robotsDiagnostic,compareRobotsDiagnostics}from'../src/source-diagnostic.js';import{diagnosticRequest}from'../scripts/diagnostic-worker.js';import{candidateFrom,validatedProductFacts}from'../src/metadata.js';
const now=Date.parse('2026-10-01T00:00:00Z'),source=getSource('sleepfreaks'),clear={status:200,reason:'robots_clear',robotsAllowed:true,robotsMatchesReviewed:true,challenge:false,hash:'equal'};
for(const [name,w,t,classification,feed]of[
 ['Worker403/terminal200',{status:403},clear,'worker_network_block_likely',false],['both200',clear,clear,'temporary_failure_possible',true],['both403',{status:403},{status:403},'publisher_access_change_possible',false],['429',{status:429},clear,'unresolved_access_or_policy',false],['redirect',{reason:'redirect_blocked'},clear,'unresolved_access_or_policy',false],['changed robots',{...clear,robotsMatchesReviewed:false},clear,'unresolved_access_or_policy',false],['200 challenge',{...clear,challenge:true},clear,'unresolved_access_or_policy',false]])test('diagnostic '+name,()=>assert.deepEqual(compareRobotsDiagnostics(w,t),{classification,collectionStopped:true,feedValidationAllowed:feed}));
test('diagnostic uses one declared-UA GET, never follows redirects or retains refusal body',async()=>{let calls=0;const r=await robotsDiagnostic(source,{now,fetcher:async(url,options)=>{calls++;assert.equal(url,source.robotsUrl);assert.equal(options.method,'GET');assert.equal(options.redirect,'manual');assert.match(options.headers['User-Agent'],/^SoundCruiseNewsBot\/0.1/);return new Response('DO NOT RETAIN REFUSAL',{status:403,headers:{server:'nginx'}});}});assert.equal(calls,1);assert.equal(r.status,403);assert.equal(r.hash,null);assert.equal(r.headers.server,'nginx');assert.ok(!JSON.stringify(r).includes('RETAIN'));});
test('diagnostic parses 200 robots memory only and detects reviewed hash',async()=>{const text='User-agent: *\nAllow: /',s={...source,robotsHash:await hash(text)},r=await robotsDiagnostic(s,{now,fetcher:async()=>new Response(text)});assert.equal(r.reason,'robots_clear');assert.equal(r.robotsAllowed,true);assert.ok(!JSON.stringify(r).includes('User-agent'));});
test('diagnostic redirect/challenge remains stopped with no second GET',async()=>{for(const status of [302,429,451]){let calls=0;const r=await robotsDiagnostic(source,{now,fetcher:async()=>{calls++;return new Response('',{status,headers:{location:'https://different.invalid/'}});}});assert.equal(calls,1);assert.equal(compareRobotsDiagnostics(r,clear).feedValidationAllowed,false);}});
test('one-use Worker consumes before fetch and leaves source, candidates, controls unchanged',async()=>{const db=database();db.raw.exec("INSERT INTO source_state(source_id,disabled,publication_blocked,takedown) VALUES('sleepfreaks',1,0,0)");const before=db.raw.prepare('SELECT * FROM source_state').all();const env={NEWS_DB:db,DIAGNOSTIC_TOKEN:'synthetic-test-token',DIAGNOSTIC_RUN_ID:'existing-source-robots-aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',DIAGNOSTIC_EXPIRES_AT:String(now+60000)};const req=()=>new Request('https://diagnostic.example/robots-check',{method:'POST',headers:{Authorization:'Bearer synthetic-test-token'}});let calls=0;const fetcher=async()=>{calls++;return new Response('',{status:403});};assert.equal((await diagnosticRequest(req(),env,now,fetcher)).status,200);assert.equal((await diagnosticRequest(req(),env,now,fetcher)).status,409);assert.equal(calls,1);assert.deepEqual(db.raw.prepare('SELECT * FROM source_state').all(),before);assert.equal(db.raw.prepare('SELECT COUNT(*) n FROM candidate_items').get().n,0);});
test('one-use Worker rejects unauthenticated/expired/state-changed requests before publisher access',async()=>{const db=database();db.raw.exec("INSERT INTO source_state(source_id,disabled) VALUES('sleepfreaks',1)");const env={NEWS_DB:db,DIAGNOSTIC_TOKEN:'synthetic',DIAGNOSTIC_RUN_ID:'existing-source-robots-aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',DIAGNOSTIC_EXPIRES_AT:String(now+1)};let calls=0;const f=async()=>{calls++;return new Response('');};assert.equal((await diagnosticRequest(new Request('https://d.example/robots-check',{method:'POST'}),env,now,f)).status,401);const req=()=>new Request('https://d.example/robots-check',{method:'POST',headers:{Authorization:'Bearer synthetic'}});assert.equal((await diagnosticRequest(req(),env,now+1,f)).status,410);db.raw.exec("UPDATE source_state SET disabled=0 WHERE source_id='sleepfreaks'");assert.equal((await diagnosticRequest(req(),env,now,f)).status,409);assert.equal(calls,0);});
const ikebe={...getSource('ikebe'),enabled:true,productionEnabled:true};const entry=title=>({title,eventTitle:title,url:'https://www.ikebe-gakki-pb.com/new_product/900001/',date:'2026-09-29T00:00:00+09:00',listingSection:'product_news',listingCategory:'amps_effects'});
for(const title of ['Ibanezj.custom RG8570EM-NT ギター 新製品発表','EpiphoneJoan Jett Olympic Special ギター 新製品発表','KORGNu:Tekt NuTube HIGH GAIN OD ペダル 新製品発表','KLOWRALeap Octave ペダル 新製品発表','Fortin Amplification 「3.33」 ペダル 新製品発表'])test('explicit listing noun '+title,async()=>{const {item}=await candidateFrom(entry(title),ikebe,{isAllowed:()=>true},now,pepper);assert.equal(item.publicationDecision,'AUTO_PUBLISHABLE');assert.equal(validatedProductFacts(item.productFacts),true);assert.equal(item.productFacts.identifierBasis,'reviewed_listing_model');});
for(const title of ['Joan Jett Olympic Special ギター 新製品発表','合成 RG8570EM-NT ギター 新製品発表','KIKUTANI KTT-01 新製品発表','KORG TM-1 新製品発表'])test('missing manufacturer or type not invented '+title,async()=>{const {item}=await candidateFrom(entry(title),ikebe,{isAllowed:()=>true},now,pepper);assert.equal(item.publicationDecision,'PUBLISH_REVIEW');});
test('distinct Nu:Tekt models preserve their own nouns; absent event stays REVIEW',async()=>{const a=await candidateFrom(entry('KORGNu:Tekt NuTube HIGH GAIN OD ペダル 新製品発表'),ikebe,{isAllowed:()=>true},now,pepper),b=await candidateFrom(entry('KORGNu:Tekt NuTube OD-KIT CUSTOM CRAFT BD-S ペダル'),ikebe,{isAllowed:()=>true},now,pepper);assert.notEqual(a.item.productFacts.product,b.item.productFacts.product);assert.equal(b.item.publicationDecision,'PUBLISH_REVIEW');});

import{recoverPendingCandidates}from'../src/pending-replay.js';import{}from'../src/operator-review.js';import{administer}from'../src/admin.js';
const proof={sourceUrl:ikebe.discoveryUrl,status:200,headerOptOut:false,hash:'a'.repeat(64),at:new Date(now).toISOString()};
async function recoveryCase(){const s=await store();await administer(s,{action:'publish-on',reason:'review_complete'},now);const {item}=await candidateFrom(entry('Ibanezj.custom RG8570EM-NT ギター 新製品発表'),ikebe,{isAllowed:()=>true},now,pepper);await s.put({...item,productFacts:null,publicationDecision:'PUBLISH_REVIEW',decisionReason:'label_required'});return {s,item};}
test('bounded recovery fills existing pending facts without changing date/expiry or adding rows',async()=>{const{s,item}=await recoveryCase(),old=(await s.candidates())[0],r=await recoverPendingCandidates(s,ikebe,[ikebe],now,pepper,[item],proof),row=(await s.candidates())[0];assert.equal(r.results[0].auto,true);assert.equal(row.published_at,old.published_at);assert.equal(row.expires_at,old.expires_at);assert.equal(row.review_status,'pending');assert.equal((await s.candidates()).length,1);assert.equal(JSON.parse(row.product_facts).product,'j.custom RG8570EM-NT');});
test('bounded recovery preserves rejected decisions and rejects changed date or missing facts',async()=>{const{s,item}=await recoveryCase();await operatorDecision(s,{id:item.id,action:'reject',reason:'not_relevant'},now,[ikebe],pepper);assert.equal((await recoverPendingCandidates(s,ikebe,[ikebe],now,pepper,[item],proof)).results[0].reason,'decision_preserved');assert.equal((await s.candidates())[0].review_status,'rejected');const x=await recoveryCase();assert.equal((await recoverPendingCandidates(x.s,ikebe,[ikebe],now,pepper,[{...x.item,publishedAt:'2026-09-28T00:00:00Z'}],proof)).results[0].reason,'identity_date_or_expiry');assert.equal((await recoverPendingCandidates(x.s,ikebe,[ikebe],now,pepper,[{...x.item,productFacts:null}],proof)).results[0].reason,'facts_context_uncertain');});
test('bounded recovery refuses source stop and stale/unchecked proof',async()=>{const{s,item}=await recoveryCase();await assert.rejects(recoverPendingCandidates(s,ikebe,[ikebe],now,pepper,[item],{...proof,at:'2026-09-29T00:00:00Z'}),/recovery_proof_invalid/);await administer(s,{action:'source-collection-stop',target:'ikebe',reason:'operator_stop'},now,[ikebe]);await assert.rejects(recoverPendingCandidates(s,ikebe,[ikebe],now,pepper,[item],proof),/replay_source_gate/);});
test('review duplicate closes through existing operator path with audit, no resurrection',async()=>{const{s,item}=await recoveryCase();await operatorDecision(s,{id:item.id,action:'reject',reason:'duplicate'},now,[ikebe],pepper);assert.equal((await s.candidates())[0].review_status,'rejected');assert.equal(s.db.raw.prepare("SELECT COUNT(*) n FROM news_admin_audit WHERE action='review-reject'").get().n,1);await assert.rejects(operatorDecision(s,{id:item.id,action:'approve',reason:'useful_product'},now,[ikebe],pepper),/already_decided/);});

import{publishAutomatic}from'../src/automatic.js';import{backfillLegacy}from'../src/legacy.js';
test('recovered Player Fusion cannot duplicate the immutable published series topic',async()=>{const s=await store();await administer(s,{action:'publish-on',reason:'review_complete'},now);await backfillLegacy(s,now);const {item}=await candidateFrom(entry('Fender MEX Limited Edition Player Fusion Series ギター 新製品発表'),ikebe,{isAllowed:()=>true},now,pepper);await s.put(item);await s.recordHealth({sourceId:ikebe.id,status:'healthy',reasonCode:'ok',checkedAt:now,successfulAt:now});assert.equal(await publishAutomatic(s,ikebe,[ikebe],now,pepper),0);await operatorDecision(s,{id:item.id,action:'reject',reason:'duplicate'},now,[ikebe],pepper);assert.equal((await s.candidates()).find(r=>r.id===item.id).review_status,'rejected');});
