import test from 'node:test';import assert from 'node:assert/strict';
import {setup,put,source,now} from './operator-case.js';import {pepper} from './helpers.js';
import {getSource} from '../src/registry.js';import {administer} from '../src/admin.js';
import {initializePending,runPendingRechecks,setPublishInterest} from '../src/pending-lifecycle.js';
import {candidateSnapshot} from '../src/operator-review.js';import {publicationValidation} from '../src/decision-policy.js';
import {collectSource} from '../src/collector.js';import {handleNewsRequest} from '../src/worker.js';
const ik={...getSource('ik'),enabled:true,productionEnabled:true},registry=[source,ik];
async function fixture(){const s=await setup();await s.recordHealth({sourceId:ik.id,status:'healthy',reasonCode:'ok',checkedAt:now,successfulAt:now});await put(s,'ik-pending',{sourceId:'ik',sourceName:ik.name,sourceUrl:'https://www.ikmultimedia.com/news/?item_id=99999',normalizedUrl:'https://www.ikmultimedia.com/news/?item_id=99999',productFacts:null});await put(s,'ik-approved',{sourceId:'ik',sourceName:ik.name,sourceUrl:'https://www.ikmultimedia.com/news/?item_id=99998',normalizedUrl:'https://www.ikmultimedia.com/news/?item_id=99998',label:'IK Multimedia、TONEX Boardを発売',productFacts:{brand:'IK Multimedia',product:'TONEX Board',category:'amps_effects',identifierBasis:'explicit_model_code'},category:'amps_effects'});await s.db.prepare("UPDATE candidate_items SET review_status='approved' WHERE id='ik-approved'").run();await put(s,'other-pending',{category:'dtm_software',productFacts:{brand:'IK Multimedia',product:'SINPHONICA',category:'dtm_software',identifierBasis:'reviewed_alias'}});await initializePending(s,now);return s;}
const stop=s=>administer(s,{action:'source-collection-stop',target:'ik',reason:'policy_change'},now,registry);
const pendingState=s=>s.db.prepare("SELECT * FROM news_pending_lifecycle WHERE candidate_id='ik-pending'").first();
test('IK collection-only retirement preserves every article, ledger, Shadow, public count and other source state',async()=>{const s=await fixture(),before=JSON.stringify(await s.candidates()),controls=await s.controls();await stop(s);assert.equal(JSON.stringify(await s.candidates()),before);assert.equal((await s.controls()).api_enabled,controls.api_enabled);assert.equal((await s.controls()).collection_enabled,controls.collection_enabled);assert.equal(!!(await s.state(source.id)).disabled,false);assert.equal((await s.state('ik')).disabled,true);assert.equal((await s.state('ik')).publicationBlocked,false);const response=await handleNewsRequest(new Request('https://example.invalid/v1/news'),{NEWS_DB:s.db,NEWS_API_MODE:'production'},now,{registry});assert.equal((await response.json()).items.length,1);for(const table of ['news_decision_ledger','news_shadow_evaluations','news_operator_feedback'])assert.equal((await s.db.prepare(`SELECT COUNT(*) n FROM ${table}`).first()).n,0);});
test('IK pending source-policy termination is idempotent and cannot revive on revision/interest',async()=>{const s=await fixture();await stop(s);const state=await pendingState(s);assert.equal(state.recheck_status,'SOURCE_EXCLUDED');assert.equal(state.next_recheck_at,null);assert.equal(state.lease_until,0);assert.equal(state.lease_token,null);assert.equal(state.unresolved_reason,'source_disabled');assert.equal(JSON.parse(state.history_json).at(-1).actor,'source_policy');await stop(s);assert.equal((await pendingState(s)).history_json,state.history_json);await s.db.prepare("UPDATE candidate_items SET review_revision=review_revision+1 WHERE id='ik-pending'").run();await initializePending(s,now+1);assert.equal((await pendingState(s)).next_recheck_at,null);const row=await s.db.prepare("SELECT * FROM candidate_items WHERE id='ik-pending'").first();await assert.rejects(setPublishInterest(s,{id:row.id,revision:row.review_revision,snapshot:await candidateSnapshot(row),interest:true},now,registry,pepper,{type:'human_operator',id:'test'}),/operator_interest_not_applicable/);});
test('scheduled IK collection and recheck never fetch, claim or evaluate Shadow; other-source IK stays valid',async()=>{const s=await fixture();await stop(s);const report=await collectSource('ik',s,{mode:'production',now,clock:()=>now,registry,pepper,fetcher:async()=>{throw Error('unexpected IK fetch');},sleep:async()=>{}});assert.equal(report.requests,0);assert.equal(report.outcome,'source_disabled');let shadow=[];const result=await runPendingRechecks(s,now,registry,pepper,{recover:async()=>{throw Error('unexpected recovery');},shadow:async(_s,i)=>shadow.push(i.id)});assert.equal(result.due,1);assert.deepEqual(shadow,['other-pending']);assert.equal((await pendingState(s)).recheck_attempt_count,0);const other=await s.db.prepare("SELECT * FROM candidate_items WHERE id='other-pending'").first();assert.equal((await publicationValidation(s,other,now,registry,pepper)).valid,true);const health=(await s.sourceHealth()).find(h=>h.source_id==='ik');assert.equal(health.status,'paused');assert.equal(health.reason_code,'source_disabled');assert.equal(health.failure_count,0);});
test('collection stop during in-flight recovery prevents Shadow churn and keeps terminal lease state',async()=>{const s=await fixture();let shadows=0;await s.db.prepare("UPDATE news_pending_lifecycle SET next_recheck_at=NULL WHERE candidate_id='other-pending'").run();await runPendingRechecks(s,now,registry,pepper,{recover:async()=>{await stop(s);return {outcome:'facts_source_gate'};},shadow:async()=>{shadows++;}});assert.equal(shadows,0);assert.equal((await pendingState(s)).next_recheck_at,null);assert.equal((await pendingState(s)).recheck_status,'SOURCE_EXCLUDED');});
test('real workerd/D1 retirement batch atomically closes source lifecycle and rolls back on audit failure',async()=>{const {mkdtemp,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path'),{localDatabase}=await import('../scripts/local-db.mjs'),{store:enable}=await import('./helpers.js');const dir=await mkdtemp(join(tmpdir(),'news-retirement-d1-'));let runtime;try{runtime=await localDatabase(dir);const s=await enable(runtime.db);await put(s,'ik-pending',{sourceId:'ik',sourceName:ik.name,sourceUrl:'https://www.ikmultimedia.com/news/?item_id=99997',productFacts:null});await initializePending(s,now);await s.db.prepare("CREATE TRIGGER stop_failure BEFORE INSERT ON news_admin_audit WHEN NEW.action='source-collection-stop' BEGIN SELECT RAISE(ABORT,'test_stop_failure'); END").run();await assert.rejects(stop(s),/test_stop_failure/);assert.equal(!!(await s.state('ik')).disabled,false);assert.equal((await pendingState(s)).recheck_status,'WAITING');await s.db.prepare('DROP TRIGGER stop_failure').run();await stop(s);assert.equal((await pendingState(s)).recheck_status,'SOURCE_EXCLUDED');assert.equal((await pendingState(s)).next_recheck_at,null);assert.equal((await s.db.prepare('SELECT COUNT(*) n FROM news_decision_ledger').first()).n,0);}finally{await runtime?.mf.dispose();await rm(dir,{recursive:true,force:true});}});
