// Synthetic primary structures; no publisher article body or headline fixture.
import test from 'node:test';import assert from 'node:assert/strict';
import {getSource} from '../src/registry.js';
import {parseShimamuraProductEvidence} from '../src/shimamura-product-evidence.js';
import {parseIkebeProductEvidence} from '../src/ikebe-product-evidence.js';
import {parseShimamuraReviewEvidence,validatedShimamuraReview} from '../src/shimamura-review-evidence.js';
import {parseSourcePolicyEvidence,sourcePolicyReason,SOURCE_POLICY_PARSER} from '../src/source-policy-evidence.js';
import {parseAgmArticleEvidence} from '../src/agm-article-evidence.js';
import {factualLabel} from '../src/metadata.js';
import {setup,put,now} from './operator-case.js';import {pepper} from './helpers.js';
import {candidateSnapshot,reviewDetail} from '../src/operator-review.js';
import {resolvedRecoverySurface} from '../src/facts-readiness.js';
import {recheckFacts} from '../src/facts-recheck.js';
import {preparePendingResolution,applyPendingResolution} from '../src/pending-resolution.js';
const shima=getSource('shimamura'),ikebe=getSource('ikebe'),kikutani=getSource('kikutani'),agm=getSource('agm');
const date='2026-10-01T15:00:00.000Z';
const row=(source='shimamura',event_type='other')=>({id:'b'.repeat(64),source_id:source,source_url:source==='shimamura'?'https://www.shimamura.co.jp/update/amp-effector/2026/10/100001/':source==='ikebe'?'https://www.ikebe-gakki-pb.com/new_product/100001/':source==='kikutani'?'https://www.kikutani.co.jp/news/synthetic-campaign/':'https://acousticguitarmagazine.jp/2026-1001-synthetic-tour/',published_at:date,review_status:'pending',category:source==='kikutani'?'sale':'amps_effects',event_type});
const sh=(r,title,intro,extra='')=>`<link rel="canonical" href="${r.source_url}"><div class="mb-80"><h1>${title}</h1></div><p>公開：<time datetime="2026-10-02"></time></p><div class="p-content"><p class="wp-block-paragraph">${intro}</p>${extra}</div>`;
for(const [name,title,intro,type,event]of [
 ['unquoted model','Craft Lab AX-20に限定カラーが登場','Craft Lab AX-20に限定カラーが登場いたします。ギターです。','guitar','new_product'],
 ['polite future event','Craft Lab AX-20が登場','Craft LabよりAX-20が登場いたします。ギターです。','guitar','new_product'],
 ['scheduled subwoofers','Craft Lab「Sub8 PRO / Sub10 PRO」を発売','Craft Labがサブウーファー「Sub8 PRO」と「Sub10 PRO」を発売します。','subwoofer','release'],
 ['signature amp','Craft Lab シグネチャーモデル「Artist Tone Amp」を発表','Craft Labよりシグネチャーモデル「Artist Tone Amp」が登場しました。ギターアンプです。','guitar_amp','new_product'],
 ['audio interface','Craft Lab「AX-20」を発売','Craft LabがUSBオーディオインターフェイス「AX-20」を発売します。','audio_interface','release']
])test('generic shima recovery '+name,()=>{const r=row(),o=parseShimamuraProductEvidence(sh(r,title,intro),shima,r);assert.equal(o.productFacts.productType,type);assert.equal(o.eventType,event);assert.equal(o.publishedAt,date);assert.ok(factualLabel(o.productFacts,event));if(name.includes('scheduled')||name==='audio interface')assert.match(factualLabel(o.productFacts,event),/発売予定/);assert.ok(!JSON.stringify(o).includes(intro));});
test('primary identity disagreement is a genuine hold, never typo correction',()=>{const r=row();for(const [title,intro]of [['MOTU「OctaLight」を発売','MOTがオーディオインターフェイス「OctaLight」を発売します。'],['Craft Lab「AX-20」を発売','Craft Labがオーディオインターフェイス「AX-21」を発売します。']])assert.throws(()=>parseShimamuraProductEvidence(sh(r,title,intro),shima,r),/facts_identity_changed/);});
const ih=(r,{brand='Craft Lab',model='OctaLite',title='Craft Lab OctaLiteが登場！',lead='OctaLiteはオーディオインターフェースです。',tag='dtm',extra=''})=>`<link rel="canonical" href="${r.source_url}"><article id="main"><div class="blog_title"><h1>${title}</h1><time class="sub_info_date" datetime="2026-10-02">2026年10月02日公開</time><li class="cate-${tag}"></li><a href="https://www.ikebe-gakki-pb.com/new_product/tag/craft-lab/">${brand}</a></div><div class="main_wrap"><h1 class="wp-block-heading">${brand}<br>${model}</h1><p class="wp-block-paragraph">${lead}</p><p class="wp-block-paragraph">${model}はUSBオーディオインターフェースです。</p>${extra}</div></article>`;
test('single-product descriptive launch binds matching introduction and structured identity, not category alone',()=>{const r=row('ikebe'),description='マイク入力とDSPを小さな筐体に搭載して録音の幅を広げるオーディオデバイス';const good=ih(r,{title:description+'が登場！',lead:description+'！'}),o=parseIkebeProductEvidence(good,ikebe,r);assert.equal(o.productFacts.product,'OctaLite');assert.equal(o.eventType,'new_product');assert.equal(o.productFacts.productType,'audio_interface');for(const bad of [good.replace(description+'！','別の内容です。'),good.replace('OctaLiteはUSBオーディオインターフェースです。','仕様です。'),good.replace('が登場！','が再入荷！'),good.replace('OctaLiteはUSB','旧製品OctaLiteはUSB'),good.replace('</div></article>','<h1 class="wp-block-heading">Craft Lab<br>Other200</h1></div></article>')])assert.throws(()=>parseIkebeProductEvidence(bad,ikebe,r),/facts_/);});
test('mixed-case multi-model family, redundant SKU, and limited-color suffix preserve identity',()=>{const r=row('ikebe');const good=ih(r,{model:'Sub8 PRO – sub8pro',tag:'recording-pa',title:'Craft Lab Sub8 PRO、Sub10 PROが登場！【発売記念測定マイクプレゼント・キャンペーン開催】',lead:'Sub8 PROはサブウーファーです。'}).replace('Sub8 PRO – sub8proはUSBオーディオインターフェースです。','Sub8 PROはサブウーファーです。').replace('</div></article>','<h1 class="wp-block-heading">Craft Lab<br>Sub10 PRO – sub10pro</h1><p class="wp-block-paragraph">Sub10 PROはサブウーファーです。</p></div></article>');assert.deepEqual(parseIkebeProductEvidence(good,ikebe,r).productFacts.models,['Sub8 PRO','Sub10 PRO']);assert.throws(()=>parseIkebeProductEvidence(good.replace('sub8pro','other8'),ikebe,r));const color=ih(r,{model:'Sound Shank イケベ限定カラー エレクトリックレモン',tag:'effector',title:'Craft Lab Sound Shankが復刻！',lead:'Sound Shankはファズです。'}).replace('Sound Shank イケベ限定カラー エレクトリックレモンはUSBオーディオインターフェースです。','Sound Shankはファズです。');assert.equal(parseIkebeProductEvidence(color,ikebe,r).productFacts.productEvent.action,'reissue');assert.throws(()=>parseIkebeProductEvidence(color.replace('イケベ限定カラー','別の記事の説明'),ikebe,r));});
const review=(r=row('shimamura','review'))=>sh(r,'【実機レビュー】Craft Lab FX200｜音を試す','Craft Labのマルチエフェクター「FX200」の実機をお借りして確認しました。機材提供。','<h2>Craft Lab FX200 の概要</h2><h2>音作りのポイント</h2><h2>演奏インプレッション</h2>');
test('provided-gear review remains editorial and human-reviewable; no invented product launch',async()=>{const {hash}=await import('../src/policy.js');const s=await setup(),r=row('shimamura','review'),robot='User-agent: *\nAllow: /',a={...shima,enabled:true,productionEnabled:true,robotsHash:await hash(robot)};await put(s,'review',{id:r.id,sourceUrl:r.source_url,normalizedUrl:r.source_url,publishedAt:date,eventType:'review',productFacts:null,category:'amps_effects'});const before=await s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(r.id).first(),out=await recheckFacts(s,{id:r.id,revision:before.review_revision,snapshot:await candidateSnapshot(before),requestId:crypto.randomUUID()},now,[a],pepper,{type:'system_recheck',id:'test'},{sleep:async()=>{},fetcher:async u=>new Response(u===a.robotsUrl?robot:review(r),{headers:{'Content-Type':'text/html'}})});assert.equal(out.validation.valid,true,JSON.stringify(out));const d=await reviewDetail(s,r.id,now,[a],pepper);assert.equal(d.factsReview.reviewability,'READY_FOR_HUMAN_DECISION');assert.equal(d.facts.eventType,undefined);const after=await s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(r.id).first();assert.equal(after.event_type,'product_article');assert.equal(after.review_status,'pending');assert.equal(JSON.parse(after.product_facts).editorialNotice,'equipment_provided');for(const t of ['news_decision_ledger','news_operator_feedback'])assert.equal((await s.db.prepare('SELECT COUNT(*) n FROM '+t).first()).n,0);});
test('review cannot borrow hidden, related, unbound or unsupported-type evidence',()=>{const r=row('shimamura','review'),h=review(r),f=parseShimamuraReviewEvidence(h,shima,r).productFacts;assert(validatedShimamuraReview(f));assert(!validatedShimamuraReview({...f,models:f.product}));for(const bad of [h.replace('Craft Lab FX200 の概要','Other FX200 の概要'),h.replace('マルチエフェクター','ヘッドホン'),h.replace('class="p-content"','class="p-content" aria-hidden="true"'),h.replace('【実機レビュー】','【比較レビュー】')])assert.throws(()=>parseShimamuraReviewEvidence(bad,shima,r));});
const policy=r=>`<link rel="canonical" href="${r.source_url}"><article class="news inner"><time class="news__time-time" datetime="2026-10-02"></time><p class="wp-block-paragraph">対象のサックスをご購入の方に特典をプレゼントいたします。</p></article>`;
test('objective unrelated instrument promotion closes safely, never creates a human teacher',async()=>{const s=await setup(),r=row('kikutani','sale'),out=parseSourcePolicyEvidence(policy(r),kikutani,r),proof=['subjectType','promotionType','event_type'].map(factField=>({factField,sourceId:'kikutani',sourceUrl:r.source_url,parserVersion:SOURCE_POLICY_PARSER,extractionMethod:'explicit_source_policy_fields',verifiedAt:now,responseHash:'a'.repeat(64)}));await put(s,'policy',{id:r.id,sourceId:'kikutani',sourceName:kikutani.name,sourceUrl:r.source_url,normalizedUrl:r.source_url,publishedAt:date,productFacts:out.productFacts,eventType:'sale',category:'sale'});await s.db.prepare('UPDATE candidate_items SET facts_provenance=? WHERE id=?').bind(JSON.stringify(proof),r.id).run();const before=await s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(r.id).first();assert.equal(sourcePolicyReason(before,now),'not_relevant');assert.equal(sourcePolicyReason({...before,source_id:'shimamura'},now),null);assert.equal(sourcePolicyReason({...before,event_type:'new_product'},now),null);assert.equal(sourcePolicyReason({...before,facts_provenance:'[]'},now),null);const plan=await preparePendingResolution(s,{id:r.id,snapshot:await candidateSnapshot(before),requestId:crypto.randomUUID()},now,[kikutani],pepper);assert.equal(plan.actor,'system_policy');await applyPendingResolution(s,plan);const after=await s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(r.id).first();assert.equal(after.review_status,'rejected');assert.equal(after.reviewed_by,'system_policy');assert.equal((await s.db.prepare('SELECT * FROM news_pending_lifecycle WHERE candidate_id=?').bind(r.id).first()).next_recheck_at,null);for(const t of ['news_decision_ledger','news_operator_feedback','news_shadow_evaluations'])assert.equal((await s.db.prepare('SELECT COUNT(*) n FROM '+t).first()).n,0);});
test('instrument policy requires visible primary purchase condition and unchanged date/URL',()=>{const r=row('kikutani','sale'),h=policy(r);for(const bad of [h.replace('サックス','ギター'),h.replace('プレゼントいたします','仕様です'),h.replace('class="news inner"','class="news inner" hidden'),h.replace('サックス','<span hidden>サックス</span>'),h.replace('datetime="2026-10-02"','datetime="2026-10-03"'),h.replace(r.source_url,'https://example.test/')])assert.throws(()=>parseSourcePolicyEvidence(bad,kikutani,r));});
test('AGM tour uses explicit person, concert and acoustic relevance, never infers event dates',()=>{const r=row('agm'),title='シンガー・ソングライター、合成奏者の「ほろ酔いコンサート2026」ツアー',body='合成奏者の「ほろ酔いコンサート」が開催されることが決定。アコースティックギターを演奏します。',h=`<link rel="canonical" href="${r.source_url}"><meta property="og:title" content="${title}"><meta property="article:published_time" content="${date}"><h1>${title}</h1><main class="post-item"><article><p>${body}</p></article></main>`,out=parseAgmArticleEvidence(h,agm,r);assert.equal(out.productFacts.action,'tour');assert.equal(out.productFacts.person,'合成奏者');assert.match(factualLabel(out.productFacts,out.eventType),/ツアー.*開催情報/);assert.equal(out.publishedAt,date);assert.equal(out.productFacts.eventDate,undefined);for(const bad of [h.replace('開催されることが決定','詳細は未定'),h.replace('アコースティックギター','オーケストラ'),h.replace(body,'別の奏者についての話題です。')])assert.throws(()=>parseAgmArticleEvidence(bad,agm,r));});
test('fresh completed listing with missing facts escalates to primary; fabricated/old discovery cannot',async()=>{const s=await setup(),r=row(),collected=new Date(now-1000).toISOString();await put(s,'listing',{id:r.id,sourceUrl:r.source_url,normalizedUrl:r.source_url,publishedAt:date,productFacts:null});await s.db.prepare('UPDATE candidate_items SET collected_at=? WHERE id=?').bind(collected,r.id).run();const saved=await s.db.prepare('SELECT * FROM candidate_items WHERE id=?').bind(r.id).first();assert.equal((await resolvedRecoverySurface(s,saved,shima)).method,'existing_listing_parser');await s.db.prepare('INSERT INTO source_state(source_id,last_discovery_at) VALUES(?,?)').bind('shimamura',now).run();assert.equal((await resolvedRecoverySurface(s,saved,shima)).method,'explicit_shimamura_product_fields');assert.equal((await resolvedRecoverySurface(s,{...saved,collected_at:'invalid'},shima)).method,'existing_listing_parser');});
