'use strict';
const $=id=>document.getElementById(id),reasonLabels={facts_identifier_missing:'製品・内容の識別情報が不足',date_uncertain:'日付を確認できない',category_uncertain:'カテゴリを確認できない',not_relevant:'対象ニュースとして適さない',duplicate:'既存掲載と重複',useful_product:'有用な製品・イベント情報',policy_concern:'掲載方針上の懸念',operator_review:'運用者による確認'};
const errorLabels={facts_source_gate:'情報源の許可・取得状態を満たしていません。候補は変更していません',facts_recheck_busy:'同じ情報源の確認が進行中です。完了後に開き直してください',facts_source_unavailable:'情報源を取得できませんでした',facts_timeout:'情報源の応答が時間切れになりました',facts_parser_failure:'取得内容を安全に解析できませんでした',facts_listing_structure_changed:'公式一覧の構造が変わっているため更新していません',facts_transaction_failed:'事実の保存結果を確認できません。候補を開き直してください',publication_policy_rejected:'公開方針で掲載対象外と判定されています',facts_incomplete:'掲載に必要なfactsが不足しています',event_date_missing:'開催日が確認できません',duplicate:'既存掲載と重複しています',candidate_changed:'候補が変更されました。詳細を開き直してください',stale_decision:'他の判断・変更が先に確定しました',already_decided:'この候補は判断済みです',idempotency_payload_changed:'前回のrequest IDと内容が異なります',authentication_required:'Accessへログインしてください',authentication_invalid:'Accessの認証期限を確認してください',operator_denied:'このアカウントには管理権限がありません',operator_source_gate:'情報源・公開許可の条件を満たしていません',expired_candidate:'日付または有効期限が掲載条件を満たしていません',sale_validation_failed:'セールの掲載条件を満たしていません',event_validation_failed:'イベントの期限・内容を確認できません',facts_provenance_invalid:'factsの出典を確認できません',label_provenance_invalid:'labelの検証情報が不足しています',source_url_invalid:'原文URLが掲載条件を満たしていません'};
let items=[],selected=null,session=null,action=null,busy=false;
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n;};
const message=text=>{$('notice').textContent=text;};
const displayError=code=>errorLabels[code]||code;
async function api(path,options){const res=await fetch(path,{credentials:'same-origin',cache:'no-store',...options});const data=await res.json();if(!res.ok)throw Object.assign(Error(displayError(data.error)),{code:data.error,status:res.status});return data;}
function originalLink(url){try{const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password)return el('span','原文URLを確認できません');const a=el('a','原文を開く');a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';return a;}catch{return el('span','原文URLを確認できません');}}
const date=value=>value?new Date(value).toLocaleString('ja-JP'):'—';
function summary(row,card){card.append(el('h3',row.label),el('p',`${row.source} · ${date(row.publishedAt)} · ${row.category}`,'meta'),el('p',`理由：${reasonLabels[row.reason]||row.reason} / ${row.reviewReason||''}`),originalLink(row.sourceUrl));}
function validationView(row,card){card.append(el('p',row.validation.valid?'掲載条件を満たしています':row.validation.errors.map(displayError).join(' / '),row.validation.valid?'ready':'blocker'));for(const d of row.validation.duplicates){const p=el('p',`重複候補：${d.source_name} / ${d.label} / topic: ${d.topic_key} `,'blocker');p.append(originalLink(d.source_url));card.append(p);}card.append(el('p',`保持期限：${date(row.expiresAt)}${row.saleEndsAt?' / セール終了：'+date(row.saleEndsAt):''}${row.eventEndsAt?' / 開催期限：'+date(row.eventEndsAt):''}`,'meta'));}
function factsView(row,card){const r=row.factsReview;if(!r)return;card.append(el('h3','事実の確認状況'),el('p',r.missing.length?'不足・未確認：'+r.missing.join(' / '):'掲載に必要な事実は確認済みです。'),el('p',r.available?'再確認可能：許可済みの情報源を使用します。':'この情報源は現在、自動で再確認できません。','meta'),el('p',`最終確認：${date(r.lastVerifiedAt)}${r.outcome?' / '+recheckLabel(r.outcome):''}`,'meta'));if(r.surfaceUrl){const p=el('p',r.method==='existing_listing_parser'?'取得範囲は公式一覧のみです。原記事の本文は取得しません。 ':'原記事の明示されたイベント項目を確認します。 ','meta');p.append(originalLink(r.surfaceUrl));card.append(p);}for(const p of r.provenance)card.append(el('p',`${p.factField} · ${p.sourceId} · ${date(p.verifiedAt)} · ${p.extractionMethod} / ${p.parserVersion}`,'meta'));}
const recheckLabel=code=>({facts_recovered:'確認できた事実を保存しました。掲載条件は別途確認してください。',facts_unchanged:'事実に変更はありません。不足する条件は保留します。',facts_not_recovered:'必要な事実を確認できませんでした。保留を維持します。',facts_not_on_current_surface:'現在の許可済み一覧に該当記事がありません。',facts_date_changed:'公開日が一致しないため更新していません。',facts_identity_changed:'対象の識別情報が一致しないため更新していません。',facts_duplicate_preserved:'既存掲載との重複を維持しています。',facts_already_complete:'事実は確認済みです。',verified_surface:'許可済み情報源を確認済みです。'}[code]||displayError(code));
async function recheckSelected(button){if(busy||!selected)return;busy=true;button.disabled=true;const input={id:selected.id,snapshot:selected.snapshot,revision:selected.revision,requestId:crypto.randomUUID()};message('許可済みの情報源から事実を再確認しています…');try{session=await api('/api/session');const result=await api('/api/facts-recheck',{method:'POST',headers:{'Content-Type':'application/json','X-News-CSRF':session.csrf},body:JSON.stringify(input)});message(recheckLabel(result.outcome)+' 掲載・非掲載の判断は行っていません。');}catch(e){message(e.message+'。候補を開き直して結果を確認してください。');}finally{busy=false;await refresh();await showDetail(input.id);}}
function renderList(){const filtered=items.filter(x=>($('mode').value==='all'||x.decision===$('mode').value)&&($('source').value==='all'||x.sourceId===$('source').value));$('count').textContent=`保留 ${filtered.length}件（全${items.length}件）`;$('list').replaceChildren();for(const row of filtered){const card=el('article',undefined,'card');summary(row,card);card.append(el('p',row.facts?'factsあり（詳細で確認）':'facts不足：掲載できません','meta'));validationView(row,card);const button=el('button','詳細を確認');button.addEventListener('click',()=>showDetail(row.id));card.append(button);$('list').append(card);}if(!filtered.length)$('list').append(el('p','保留候補はありません。'));}
async function refresh(){items=(await api('/api/pending')).items;const previous=$('source').value;$('source').replaceChildren(new Option('すべての情報源','all'));for(const [id,name]of new Map(items.map(x=>[x.sourceId,x.source])))$('source').add(new Option(name,id));if([...$('source').options].some(x=>x.value===previous))$('source').value=previous;renderList();}
async function showDetail(id){try{selected=await api('/api/candidates/'+encodeURIComponent(id));const card=$('detail');card.hidden=false;card.replaceChildren();card.append(el('h2','候補詳細'));summary(selected,card);card.append(el('p',`状態：${selected.status}`),el('h3','掲載時のlabel'),el('p',selected.validation.publishableLabel||'作成できません（facts不足）'),el('h3','確認できるfacts'),el('pre',selected.facts?JSON.stringify(selected.facts,null,2):'factsがありません。原文からの推測・自動補完は行いません。'));validationView(selected,card);factsView(selected,card);card.append(el('p',`label情報量：${selected.validation.quality.labelInformationScore}（品質指標。判断の推奨ではありません）`,'meta'));if(['pending','reopened'].includes(selected.status)){const controls=el('div',undefined,'actions');const recheck=el('button','事実を再確認');recheck.id='facts-recheck';recheck.disabled=busy||!selected.factsReview?.available;recheck.addEventListener('click',()=>recheckSelected(recheck));controls.append(recheck);for(const [verdict,text]of [['approve','掲載する'],['reject','掲載しない']]){const b=el('button',text);b.disabled=verdict==='approve'&&!selected.validation.valid;b.addEventListener('click',()=>confirmDecision(verdict));controls.append(b);}card.append(controls);}card.append(el('h3','判断履歴'));if(!selected.history.length)card.append(el('p','新しい判断履歴はありません。過去の判断を人手判断として移行していません。','meta'));for(const h of selected.history)card.append(el('p',`${h.verdict==='approve'?'掲載':'非掲載'} · ${reasonLabels[h.reason]||h.reason} · ${h.actor_type} / ${h.actor_id} · ${date(h.decided_at)} · ${h.source_id} / ${h.category} · ${h.policy_version}`));card.scrollIntoView({block:'start'});}catch(e){message(e.message);}}
function confirmDecision(verdict){if(busy||!selected)return;action=verdict;$('confirm-title').textContent=verdict==='approve'?'このニュースを掲載しますか？':'このニュースを掲載しませんか？';$('confirm-label').textContent=verdict==='approve'?selected.validation.publishableLabel:selected.label;$('reason').replaceChildren();for(const reason of verdict==='approve'?['useful_product','operator_review']:['facts_identifier_missing','date_uncertain','category_uncertain','not_relevant','duplicate','policy_concern','operator_review'])$('reason').add(new Option(reasonLabels[reason],reason));$('checks').hidden=verdict!=='approve';for(const check of $('checks').querySelectorAll('input'))check.checked=false;updateSubmit();$('confirm').showModal();}
function updateSubmit(){$('submit').disabled=busy||action==='approve'&&[...$('checks').querySelectorAll('input')].some(x=>!x.checked);}
const outboxKey='news-operator-unconfirmed-decision-v1';
async function sendDecision(input){if(busy)return;busy=true;updateSubmit();try{session=await api('/api/session');const result=await api('/api/decision',{method:'POST',headers:{'Content-Type':'application/json','X-News-CSRF':session.csrf},body:JSON.stringify(input)});sessionStorage.removeItem(outboxKey);$('retry').hidden=true;$('confirm').close();message(`判断を保存しました（${result.action==='approve'?'掲載':'非掲載'}）。`);await refresh();await showDetail(input.id);}catch(e){message(e.message+(e.status===503||!e.status?'。判断が確定済みの可能性があります。「前回の判断結果を確認・再送」で同じrequest IDの結果を確認してください。':''));if(e.status&&e.status!==503){sessionStorage.removeItem(outboxKey);$('retry').hidden=true;$('confirm').close();await refresh();await showDetail(input.id);}else $('retry').hidden=false;}finally{busy=false;updateSubmit();}}
$('submit').addEventListener('click',()=>{if($('submit').disabled||busy)return;const input={id:selected.id,action,reason:$('reason').value,snapshot:selected.snapshot,revision:selected.revision,requestId:crypto.randomUUID(),...(action==='approve'?{label:selected.validation.publishableLabel,category:selected.category,publishedAt:selected.publishedAt,checks:Object.fromEntries([...$('checks').querySelectorAll('input')].map(c=>[c.name,c.checked]))}:{})};sessionStorage.setItem(outboxKey,JSON.stringify(input));sendDecision(input);});
$('retry').addEventListener('click',()=>{try{const input=JSON.parse(sessionStorage.getItem(outboxKey));if(input)sendDecision(input);}catch{message('前回の送信内容を読めません。');}});
$('checks').addEventListener('change',updateSubmit);for(const id of ['mode','source'])$(id).addEventListener('change',renderList);$('reload').addEventListener('click',()=>refresh().catch(e=>message(e.message)));
(async()=>{try{session=await api('/api/session');$('identity').textContent=`管理者：${session.operator} · NEWS ${session.version}`;$('retry').hidden=!sessionStorage.getItem(outboxKey);await refresh();}catch(e){message(e.message);$('identity').textContent='認証・設定を確認してください';}})();
