'use strict';
const $=id=>document.getElementById(id),reasonLabels={facts_identifier_missing:'製品・内容の識別情報が不足',date_uncertain:'日付を確認できない',category_uncertain:'カテゴリを確認できない',not_relevant:'対象ニュースとして適さない',duplicate:'既存掲載と重複',useful_product:'有用な製品・イベント情報',policy_concern:'掲載方針上の懸念',operator_review:'運用者による確認'};
const errorLabels={facts_source_gate:'情報源の許可・取得状態を満たしていません。候補は変更していません',facts_recheck_busy:'同じ情報源の確認が進行中です。完了後に開き直してください',facts_source_unavailable:'情報源を取得できませんでした',facts_timeout:'情報源の応答が時間切れになりました',facts_parser_failure:'取得内容を安全に解析できませんでした',facts_listing_structure_changed:'公式一覧の構造が変わっているため更新していません',facts_transaction_failed:'事実の保存結果を確認できません。候補を開き直してください',publication_policy_rejected:'公開方針で掲載対象外と判定されています',facts_incomplete:'掲載に必要なfactsが不足しています',event_date_missing:'開催日が確認できません',duplicate:'既存掲載と重複しています',candidate_changed:'候補が変更されました。詳細を開き直してください',stale_decision:'他の判断・変更が先に確定しました',already_decided:'この候補は判断済みです',idempotency_payload_changed:'前回のrequest IDと内容が異なります',authentication_required:'Accessへログインしてください',authentication_invalid:'Accessの認証期限を確認してください',operator_denied:'このアカウントには管理権限がありません',operator_source_gate:'情報源・公開許可の条件を満たしていません',expired_candidate:'日付または有効期限が掲載条件を満たしていません',sale_validation_failed:'セールの掲載条件を満たしていません',event_validation_failed:'イベントの期限・内容を確認できません',facts_provenance_invalid:'factsの出典を確認できません',label_provenance_invalid:'labelの検証情報が不足しています',source_url_invalid:'原文URLが掲載条件を満たしていません'};
const categoryLabel=key=>({acoustic_guitar:'アコギ',electric_guitar_bass:'ギター・ベース',amps_effects:'アンプ・エフェクター',dtm_software:'DTM',recording_audio:'録音・配信',creator_streaming:'録音・配信',recording_streaming:'録音・配信',artist_guitar:'アーティスト',live_guitar:'イベント',sale:'セール',media_other:'その他'}[key]||'カテゴリ未確定');
// Only the server generates a formal label and determines publication readiness.
const formalTitle=row=>row.validation?.publishableLabel||(!/要確認|審査待ち|label_required|relevance_uncertain/.test(row.label||'')?row.label:null)||'正式表題を確定できません';
function statusLabel(row){if(row.validation?.valid===true)return '掲載可';const state=row.factsReview?.reviewability;if(state==='DUPLICATE_BLOCKED'||row.validation?.errors?.includes('duplicate'))return '重複';if(state==='POLICY_BLOCKED')return '方針確認';if(state==='FACTS_RECOVERY_UNCERTAIN'||row.validation?.errors?.includes('facts_incomplete'))return 'facts不足';return '保留';}
let items=[],selected=null,session=null,action=null,busy=false,expandedId=null,detailRequest=0,actionRead=0;
const detailCards=new Map();
function closeDetail(){detailRequest++;actionRead++;selected=null;expandedId=null;for(const {detail,button}of detailCards.values()){detail.hidden=true;detail.replaceChildren();button.textContent='詳細を確認';button.setAttribute('aria-expanded','false');}}
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=String(text);if(cls)n.className=cls;return n;};
const message=text=>{$('notice').textContent=text;};
const displayError=code=>errorLabels[code]||code;
async function api(path,options){const res=await fetch(path,{credentials:'same-origin',cache:'no-store',...options});const data=await res.json();if(!res.ok)throw Object.assign(Error(displayError(data.error)),{code:data.error,status:res.status});return data;}
function originalLink(url){try{const u=new URL(url);if(u.protocol!=='https:'||u.username||u.password)return el('span','原文URLを確認できません');const a=el('a','原記事を開く');a.href=u.href;a.target='_blank';a.rel='noopener noreferrer';return a;}catch{return el('span','原文URLを確認できません');}}
const date=value=>value?new Date(value).toLocaleString('ja-JP'):'—';
function summary(row,card){card.append(el('h3',formalTitle(row)),el('p',`${row.source} · ${date(row.publishedAt)}`,'meta'));const badges=el('div',undefined,'badges');badges.append(el('span','カテゴリ候補','meta'),el('span',categoryLabel(row.category),'category-pill'),el('span',statusLabel(row),row.validation?.valid?'status-pill ready':'status-pill'));card.append(badges,originalLink(row.sourceUrl));}
function decisionControls(row){const controls=el('div',undefined,'actions decision-actions');for(const [verdict,text]of [['approve','掲載する'],['reject','掲載しない']]){const b=el('button',text);b.disabled=busy||!['pending','reopened'].includes(row.status)||(verdict==='approve'&&row.validation?.valid!==true);b.addEventListener('click',async()=>{if(busy)return;const request=detailRequest,read=++actionRead;try{const result=await api('/api/candidates/'+encodeURIComponent(row.id));if(request!==detailRequest||read!==actionRead||busy)return;if(!['pending','reopened'].includes(result.status)){message('この候補は判断済みです。');await refresh();return;}selected=result;if(verdict==='approve'&&selected.validation?.valid!==true){message('掲載条件が変わりました。更新して確認してください。');await refresh();return;}confirmDecision(verdict);}catch(e){message(e.message);}});controls.append(b);}return controls;}
function validationView(row,card){card.append(el('p',row.validation.valid?'掲載条件を満たしています':row.validation.errors.map(code=>errorLabels[code]||'確認が必要です').join(' / '),row.validation.valid?'ready':'blocker'));for(const d of row.validation.duplicates){const p=el('p',`重複候補：${d.source_name} / ${d.label} / topic: ${d.topic_key} `,'blocker');p.append(originalLink(d.source_url));card.append(p);}card.append(el('p',`保持期限：${date(row.expiresAt)}${row.saleEndsAt?' / セール終了：'+date(row.saleEndsAt):''}${row.eventEndsAt?' / 開催期限：'+date(row.eventEndsAt):''}`,'meta'));}
function factsView(row,card){const r=row.factsReview;if(!r)return;card.append(el('h3','事実の確認状況'),el('p',r.missing.length?'不足・未確認：'+r.missing.join(' / '):'掲載に必要な事実は確認済みです。'),el('p',r.available?'再確認可能：許可済みの情報源を使用します。':'この情報源は現在、自動で再確認できません。','meta'),el('p',`最終確認：${date(r.lastVerifiedAt)}${r.outcome?' / '+recheckLabel(r.outcome):''}`,'meta'));if(r.surfaceUrl){const p=el('p',r.method==='existing_listing_parser'?'取得範囲は公式一覧のみです。原記事の本文は取得しません。 ':r.method==='targeted_explicit_primary_fields'?'この候補の一次ページに明示された製品・出来事の情報を確認します。 ':'原記事の明示されたイベント項目を確認します。 ','meta');p.append(originalLink(r.surfaceUrl));card.append(p);}for(const p of r.provenance)card.append(el('p',`${p.factField} · ${p.sourceId} · ${date(p.verifiedAt)} · ${p.extractionMethod} / ${p.parserVersion}`,'meta'));}
const recheckLabel=code=>({facts_recovered:'確認できた事実を保存しました。掲載条件は別途確認してください。',facts_unchanged:'事実に変更はありません。不足する条件は保留します。',facts_not_recovered:'必要な事実を確認できませんでした。保留を維持します。',facts_not_on_current_surface:'現在の許可済み一覧に該当記事がありません。',facts_date_changed:'公開日が一致しないため更新していません。',facts_identity_changed:'対象の識別情報が一致しないため更新していません。',facts_duplicate_preserved:'既存掲載との重複を維持しています。',facts_already_complete:'事実は確認済みです。',verified_surface:'許可済み情報源を確認済みです。'}[code]||displayError(code));
async function recheckSelected(button){if(busy||!selected)return;busy=true;button.disabled=true;const input={id:selected.id,snapshot:selected.snapshot,revision:selected.revision,requestId:crypto.randomUUID()};message('許可済みの情報源から事実を再確認しています…');try{session=await api('/api/session');const result=await api('/api/facts-recheck',{method:'POST',headers:{'Content-Type':'application/json','X-News-CSRF':session.csrf},body:JSON.stringify(input)});message(recheckLabel(result.outcome)+' 掲載・非掲載の判断は行っていません。');}catch(e){message(e.message+'。候補を開き直して結果を確認してください。');}finally{busy=false;await refresh();await showDetail(input.id);}}
function matchesFilter(row,mode){return mode==='all'||(mode==='approvable'?row.validation?.valid===true:mode==='review'?row.validation?.valid!==true:mode==='duplicate'?statusLabel(row)==='重複':row.decision===mode);}
function renderList(){closeDetail();detailCards.clear();const mode=$('mode').value,filtered=items.filter(x=>matchesFilter(x,mode)&&($('source').value==='all'||x.sourceId===$('source').value));$('count').textContent=`${{approvable:'掲載可',review:'要確認',duplicate:'重複',PUBLISH_REVIEW:'REVIEW'}[mode]||'保留'} ${filtered.length}件（全${items.length}件）`;$('list').replaceChildren();for(const row of filtered){const card=el('article',undefined,'card');card.dataset.candidateId=row.id;summary(row,card);card.append(decisionControls(row));const button=el('button','詳細を確認'),detail=el('section',undefined,'inline-detail');detail.id='detail-'+row.id;detail.hidden=true;detail.setAttribute('aria-label','候補詳細');button.setAttribute('aria-controls',detail.id);button.setAttribute('aria-expanded','false');button.addEventListener('click',()=>{if(busy)return;if(expandedId===row.id)closeDetail();else showDetail(row.id);});detailCards.set(row.id,{detail,button});card.append(button,detail);$('list').append(card);}if(!filtered.length)$('list').append(el('p','該当する保留候補はありません。'));}
const similarityLabels={EXACT_PATTERN:'同じ判断パターン',STRONG_SIMILAR:'強い共通点',WEAK_SIMILAR:'一部の共通点',INSUFFICIENT:'共通点が不足'};
const signalLabels={source:'同じ情報源',surface:'同じ掲載面',type:'同じ記事・出来事の種類',category:'同じ表示カテゴリ',factStructure:'同じ確認済みfacts構造',reviewReason:'同じ確認理由・未確認条件',freshness:'同じ鮮度区分'};
function insightsView(result,section){
 section.replaceChildren(el('h3','過去の似た判断'));
 if(!result||!Number.isSafeInteger(result.matchedDecisionCount)){section.append(el('p','判断データを確認できません。ご自身で原文と掲載条件をご確認ください。','meta'));return;}
 section.append(el('p',`過去${result.matchedDecisionCount}件 · 掲載 ${result.approveCount} · 非掲載 ${result.rejectCount}`,'meta'));
 const text=result.recommendation==='RECOMMEND_APPROVE'?'掲載寄り':result.recommendation==='RECOMMEND_REJECT'?'非掲載寄り':result.reasonSummary==='contradictory_history'?'判断が分かれているため推薦なし':result.reasonSummary==='publication_blocked'?'現在の掲載条件を満たさないため推薦なし':'まだ判断データが足りません';
 section.append(el('p',text),el('p',`強い根拠 ${result.evidenceCount}件 / 必要 ${result.minimumEvidence}件 · ${similarityLabels[result.similarityLevel]||result.similarityLevel}`,'meta'),el('p','参考情報です。掲載・非掲載は自動で実行されません。','meta'));
 for(const m of result.matches){section.append(el('p',`${m.verdict==='approve'?'掲載':'非掲載'} · ${m.source} / ${categoryLabel(m.category)} / ${m.type} · ${date(m.decidedAt)} · ${reasonLabels[m.reason]||m.reason}`,'meta'),el('p',`共通点：${Object.keys(signalLabels).filter(k=>m.signals[k]).map(k=>signalLabels[k]).join('、')||'不足'} · 方針：${m.policyCompatibility==='SAME'?'同一':m.policyCompatibility==='COMPATIBLE'?'互換':'旧方針（推薦根拠から除外）'} / ${m.policyVersion}`,'meta'));}
 if(result.truncated)section.append(el('p','共通点の一覧は最新50件を表示しています。','meta'));
}
async function loadInsights(row,section,request){
 try{const result=await api('/api/candidates/'+encodeURIComponent(row.id)+'/similar-decisions?revision='+encodeURIComponent(row.revision)+'&snapshot='+encodeURIComponent(row.snapshot));if(request!==detailRequest||expandedId!==row.id)return;insightsView(result,section);
  if(!session?.csrf)return;
  await api('/api/shadow-evaluate',{method:'POST',headers:{'Content-Type':'application/json','X-News-CSRF':session.csrf},body:JSON.stringify({id:row.id,revision:row.revision,snapshot:row.snapshot})});if(request===detailRequest&&expandedId===row.id)await refreshShadow();
 }catch(e){if(request!==detailRequest||expandedId!==row.id)return;section.replaceChildren(el('h3','過去の似た判断'),el('p',e.message,'meta'));}
}

function dashboardView(data){
 if(!data||!Number.isSafeInteger(data.published))return;
 $('dashboard').replaceChildren();for(const [key,label]of [['published','公開'],['pending','保留'],['approvable','掲載可'],['humanDecisions','人間判断']]){const block=el('div',undefined,'summary-count');block.append(el('span',label),el('strong',key==='approvable'?items.filter(row=>row.validation?.valid===true).length:data[key]));$('dashboard').append(block);}
 $('rejected-count').textContent='却下 '+data.rejected+'件';
 $('dashboard').append(el('p','公開は掲載承認済みの件数。人間判断は直近365日の確定履歴です。','meta summary-note'));
}
function shadowView(data){
 if(!data||!Number.isSafeInteger(data.totalHumanDecisions))return;
 const section=$('shadow-summary');section.replaceChildren();
 section.append(el('p',`人間判断 ${data.totalHumanDecisions}件 · 比較済み（独立） ${data.independentHumanDecisions}件 · 未比較 ${data.unmatchedHumanDecisions}件`),el('p',`保存評価 ${data.evaluationsRecorded}件 · 掲載推薦 ${data.observations?.recommendApprove||0} · 非掲載推薦 ${data.observations?.recommendReject||0} · 推薦なし ${data.observations?.noRecommendation||0}`),el('p',`一致 ${data.agreement} · 誤掲載方向 ${data.falsePublishDirection} · 見逃し方向 ${data.missedPublishDirection} · 判断矛盾 ${data.contradictions}`));
 section.append(el('p',data.lowSample?'まだ評価データが不足しています。参考値・判断材料不足です。':'評価値は参考情報です。自動化可能とは判定しません。','meta'));
 if(!data.lowSample){const percent=n=>n===null?'—':(n*100).toFixed(1)+'%';section.append(el('p',`推薦coverage ${percent(data.recommendationCoverage)} · 推薦の一致率 ${percent(data.agreementRate)} · 矛盾率 ${percent(data.contradictionRate)}`,'meta'));}
 section.append(el('p',`方針：${data.policyVersion} · 推薦ルール：${data.ruleVersion} · 自動化は無効です。`,'meta'));
 $('shadow-pattern-list').replaceChildren();if(!data.patterns.length)$('shadow-pattern-list').append(el('p','比較できるパターンはまだありません。','meta'));
 for(const p of data.patterns){const card=el('article',undefined,'history-entry');card.append(el('p',`${p.source} / ${p.surface} / ${categoryLabel(p.category)} / ${p.articleType}`),el('p',`独立判断 ${p.evaluatedHumanDecisions} · 掲載推薦 ${p.recommendApprove} · 非掲載推薦 ${p.recommendReject} · 推薦なし ${p.noRecommendation}`,'meta'),el('p',`誤掲載方向 ${p.falsePublishDirection} · 見逃し方向 ${p.missedPublishDirection} · 矛盾 ${p.contradictions}`,'meta'),el('p',`facts構造：${p.factShape.join(' / ')}${p.lowSample?' · 判断材料不足':''}`,'meta'));$('shadow-pattern-list').append(card);}
}
async function refreshShadow(){try{shadowView(await api('/api/shadow-metrics'));}catch(e){$('shadow-summary').textContent=e.message;}}
let shadowBusy=false;
$('shadow-evaluate').addEventListener('click',async()=>{if(shadowBusy||busy)return;shadowBusy=true;$('shadow-evaluate').disabled=true;try{session=await api('/api/session');const result=await api('/api/shadow-evaluate',{method:'POST',headers:{'Content-Type':'application/json','X-News-CSRF':session.csrf},body:JSON.stringify({scope:'pending'})});message(`Shadow評価 ${result.evaluated}件を保存しました。掲載・非掲載は変更していません。`);await refreshShadow();}catch(e){message(e.message);}finally{shadowBusy=false;$('shadow-evaluate').disabled=false;}});
let historyOffset=0,historyBusy=false,historyRequest=0,refreshInFlight=null;
function historyView(data,reset=false){
 if(reset)$('history-list').replaceChildren();for(const h of data.items){const card=el('article',undefined,'history-entry');card.append(el('p',`${h.verdict==='approve'?'掲載':'非掲載'} · ${h.source_id} / ${categoryLabel(h.category)}`),el('p',`記事ID：${h.candidate_id}`,'meta'),el('p',`${reasonLabels[h.reason]||h.reason} · ${date(h.decided_at)} · ${h.policy_version}`,'meta'));$('history-list').append(card);}if(reset&&!data.items.length)$('history-list').append(el('p','人間の判断履歴はまだありません。','meta'));historyOffset=data.nextOffset;$('history-more').hidden=historyOffset===null;
}
function updatedAt(now){const parts=new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(now);const part=key=>parts.find(p=>p.type===key).value;return `${part('year')}/${part('month')}/${part('day')} ${part('hour')}:${part('minute')}:${part('second')}`;}
async function loadHistory(reset=false){
 if(historyBusy||refreshInFlight)return;historyBusy=true;$('history-more').disabled=true;const request=++historyRequest;
 try{const data=await api('/api/human-decisions?offset='+(reset?0:historyOffset));if(request===historyRequest)historyView(data,reset);}catch(e){if(request===historyRequest)$('history-list').replaceChildren(el('p',e.message,'blocker'));}finally{historyBusy=false;$('history-more').disabled=false;}
}
$('human-history').addEventListener('toggle',()=>{if($('human-history').open)loadHistory(true);});$('history-more').addEventListener('click',()=>loadHistory());
function refresh(){
 if(refreshInFlight)return refreshInFlight;
 $('reload').disabled=true;$('reload').textContent='更新中…';$('refresh-status').textContent='更新中…';historyRequest++;
 refreshInFlight=(async()=>{try{
  const [pending,summary,shadow,history]=await Promise.all([api('/api/pending'),api('/api/summary'),api('/api/shadow-metrics'),api('/api/human-decisions?offset=0')]);
  if(!Array.isArray(pending.items)||!Number.isSafeInteger(summary.published)||!Number.isSafeInteger(shadow.totalHumanDecisions)||!Array.isArray(history.items))throw Error('管理データの形式を確認できません');
  items=pending.items;dashboardView(summary);shadowView(shadow);historyView(history,true);
  const previous=$('source').value;$('source').replaceChildren(new Option('すべての情報源','all'));for(const [id,name]of new Map(items.map(x=>[x.sourceId,x.source])))$('source').add(new Option(name,id));if([...$('source').options].some(x=>x.value===previous))$('source').value=previous;renderList();
  $('last-updated').textContent='最終更新：'+updatedAt(Date.now())+'（JST）';$('refresh-status').textContent='更新しました';return true;
 }catch(e){$('refresh-status').textContent='更新に失敗しました。'+e.message;return false;}finally{$('reload').disabled=false;$('reload').textContent='更新';refreshInFlight=null;}})();
 return refreshInFlight;
}
function renderDetail(row,card,request){
 const tabs=el('div',undefined,'detail-tabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','詳細情報');const panels=[],buttons=[];
 for(const [key,label]of [['summary','概要'],['evidence','根拠'],['learning','学習'],['history','履歴']]){const button=el('button',label),panel=el('section',undefined,'detail-panel');button.id=`tab-${row.id}-${key}`;panel.id=`panel-${row.id}-${key}`;button.setAttribute('role','tab');button.setAttribute('aria-controls',panel.id);panel.setAttribute('role','tabpanel');panel.setAttribute('aria-labelledby',button.id);panel.hidden=key!=='summary';button.setAttribute('aria-selected',String(key==='summary'));button.tabIndex=key==='summary'?0:-1;buttons.push(button);panels.push(panel);tabs.append(button);let loaded=false;
  button.addEventListener('click',()=>{panels.forEach((p,i)=>{p.hidden=p!==panel;buttons[i].setAttribute('aria-selected',String(p===panel));buttons[i].tabIndex=p===panel?0:-1;});if(key==='learning'&&!loaded){loaded=true;loadInsights(row,insights,request);}});
  button.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const i=event.key==='Home'?0:event.key==='End'?buttons.length-1:(buttons.indexOf(button)+(event.key==='ArrowRight'?1:-1)+buttons.length)%buttons.length;buttons[i].click();buttons[i].focus();});
  if(key==='summary'){summary(row,panel);panel.append(el('p',row.validation.valid?'原記事と内容を確認して掲載判断できます。':row.validation.errors.map(code=>errorLabels[code]||'確認が必要です').join(' / ')||'内容の確認をお願いします。','meta'));for(const duplicate of row.validation.duplicates){const p=el('p','重複候補：'+duplicate.source_name+' / '+duplicate.label,'meta');p.append(originalLink(duplicate.source_url));panel.append(p);}}
  if(key==='evidence'){panel.append(el('h3','保存された事実'),el('pre',row.facts?JSON.stringify(row.facts,null,2):'確認済みのfactsはありません。推測・自動補完は行いません。'));factsView(row,panel);validationView(row,panel);panel.append(el('h3','検証情報'),el('pre',JSON.stringify({status:row.status,reason:row.reason,reviewReason:row.reviewReason,validation:row.validation},null,2)));const recheck=el('button','事実を再確認');recheck.id='facts-recheck';recheck.disabled=busy||!row.factsReview?.available;recheck.addEventListener('click',()=>{selected=row;recheckSelected(recheck);});panel.append(recheck);}
  const insights=el('section',undefined,'similar-decisions');
  if(key==='learning'){insights.append(el('h3','過去の似た判断'),el('p','学習情報を読み込んでいます…','meta'));panel.append(insights);const shadow=el('details');shadow.append(el('summary','Shadow評価（全体）'),el('p',$('shadow-summary').textContent,'meta'));panel.append(shadow);}
  if(key==='history'){panel.append(el('h3','この候補の判断履歴'));if(!row.history.length)panel.append(el('p','判断履歴はありません。','meta'));for(const h of row.history)panel.append(el('p',`${h.verdict==='approve'?'掲載':'非掲載'} · ${reasonLabels[h.reason]||h.reason} · ${date(h.decided_at)} · ${h.policy_version}`));}
 }
 card.append(tabs,...panels);
}
async function showDetail(id){const entry=detailCards.get(id);if(!entry)return;closeDetail();expandedId=id;entry.button.textContent='詳細を閉じる';entry.button.setAttribute('aria-expanded','true');const card=entry.detail;card.hidden=false;card.replaceChildren(el('p','詳細を読み込んでいます…'));const request=++detailRequest;try{const result=await api('/api/candidates/'+encodeURIComponent(id));if(request!==detailRequest||expandedId!==id)return;selected=result;card.replaceChildren();renderDetail(result,card,request);}catch(e){if(request!==detailRequest)return;card.replaceChildren(el('p',e.message,'blocker'));message(e.message);}}
function confirmDecision(verdict){if(busy||!selected)return;action=verdict;$('confirm-title').textContent=verdict==='approve'?'このニュースを掲載しますか？':'このニュースを掲載しませんか？';$('confirm-label').textContent=verdict==='approve'?selected.validation.publishableLabel:selected.label;$('reason').replaceChildren();for(const reason of verdict==='approve'?['useful_product','operator_review']:['facts_identifier_missing','date_uncertain','category_uncertain','not_relevant','duplicate','policy_concern','operator_review'])$('reason').add(new Option(reasonLabels[reason],reason));$('checks').hidden=verdict!=='approve';for(const check of $('checks').querySelectorAll('input'))check.checked=false;updateSubmit();$('confirm').showModal();}
function updateSubmit(){$('submit').disabled=busy||action==='approve'&&[...$('checks').querySelectorAll('input')].some(x=>!x.checked);}
const outboxKey='news-operator-unconfirmed-decision-v1';
async function sendDecision(input){if(busy)return;busy=true;updateSubmit();try{session=await api('/api/session');const result=await api('/api/decision',{method:'POST',headers:{'Content-Type':'application/json','X-News-CSRF':session.csrf},body:JSON.stringify(input)});sessionStorage.removeItem(outboxKey);$('retry').hidden=true;$('confirm').close();message(`判断を保存しました（${result.action==='approve'?'掲載':'非掲載'}）。`);await refresh();await showDetail(input.id);}catch(e){message(e.message+(e.status===503||!e.status?'。判断が確定済みの可能性があります。「前回の判断結果を確認・再送」で同じrequest IDの結果を確認してください。':''));if(e.status&&e.status!==503){sessionStorage.removeItem(outboxKey);$('retry').hidden=true;$('confirm').close();await refresh();await showDetail(input.id);}else $('retry').hidden=false;}finally{busy=false;updateSubmit();}}
$('submit').addEventListener('click',()=>{if($('submit').disabled||busy)return;const input={id:selected.id,action,reason:$('reason').value,snapshot:selected.snapshot,revision:selected.revision,requestId:crypto.randomUUID(),...(action==='approve'?{label:selected.validation.publishableLabel,category:selected.category,publishedAt:selected.publishedAt,checks:Object.fromEntries([...$('checks').querySelectorAll('input')].map(c=>[c.name,c.checked]))}:{})};sessionStorage.setItem(outboxKey,JSON.stringify(input));sendDecision(input);});
$('retry').addEventListener('click',()=>{try{const input=JSON.parse(sessionStorage.getItem(outboxKey));if(input)sendDecision(input);}catch{message('前回の送信内容を読めません。');}});
$('checks').addEventListener('change',updateSubmit);for(const id of ['mode','source'])$(id).addEventListener('change',renderList);$('reload').addEventListener('click',()=>refresh());
(async()=>{try{session=await api('/api/session');$('identity').textContent=`管理者：${session.operator} · NEWS ${session.version}`;$('retry').hidden=!sessionStorage.getItem(outboxKey);await refresh();}catch(e){message(e.message);$('identity').textContent='認証・設定を確認してください';}})();
