import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const markup = readFileSync(new URL('./index.html', import.meta.url), 'utf8');
const source = readFileSync(new URL('./practice-menu-app.js', import.meta.url), 'utf8');
const styles = readFileSync(new URL('./style.css', import.meta.url), 'utf8');
const store = readFileSync(new URL('./gear-list-store.js', import.meta.url), 'utf8');
const categoryStore = readFileSync(new URL('./gear-category-store.js', import.meta.url), 'utf8');
const gearFormMarkup = markup.match(/<form id="gear-list-form"[\s\S]*?<\/form>/)?.[0] || '';
const gearSource = source.match(/function findGearItem[\s\S]*?function renderRoute/)?.[0] || '';

assert.match(markup, /id="wishlist-card" href="#wishlist"/);
assert.match(markup, /id="gear-all-tab"[\s\S]*?role="tab"[\s\S]*?全て/);
assert.match(markup, /id="gear-owned-tab"[\s\S]*?role="tab"[\s\S]*?自分の機材/);
assert.match(markup, /id="gear-wishlist-tab"[\s\S]*?role="tab"[\s\S]*?ほしい機材/);
assert.match(markup, /id="gear-category-filter"/);
assert.match(markup, /class="gear-category-toolbar"[\s\S]*?id="gear-category-filter"[\s\S]*?id="gear-category-menu-toggle"[\s\S]*?id="gear-category-menu"[\s\S]*?id="gear-category-add"[\s\S]*?id="gear-category-rename"[\s\S]*?id="gear-category-delete"/);
assert.match(markup, /id="gear-category-menu-toggle"[^>]+aria-label="カテゴリメニューを開く"[^>]+title="カテゴリメニュー"[^>]+aria-haspopup="menu"/);
assert.match(markup, /id="gear-category-menu"[^>]+role="menu"[^>]+hidden/);
assert.match(markup, /id="gear-category-menu"[\s\S]*?role="menuitem"[\s\S]*?カテゴリを追加[\s\S]*?role="menuitem"[\s\S]*?カテゴリ名を変更[\s\S]*?role="menuitem"[\s\S]*?カテゴリを削除/);
assert.doesNotMatch(markup, /class="gear-category-actions"/);
assert.match(markup, /id="gear-category-add"[^>]+aria-label="カテゴリを追加"[^>]+title="カテゴリを追加"/);
assert.match(markup, /id="gear-category-rename"[^>]+aria-label="カテゴリ名を変更"[^>]+title="カテゴリ名を変更"/);
assert.match(markup, /id="gear-category-delete"[^>]+aria-label="カテゴリを削除"[^>]+title="カテゴリを削除"/);
assert.doesNotMatch(markup, />選択中のカテゴリ名を変更</);
assert.match(markup, /id="gear-category-dialog"[^>]+aria-modal="true"/);
assert.match(markup, /id="gear-category-name"[^>]+maxlength="40"/);
assert.match(markup, /id="gear-list-sections"/);
assert.doesNotMatch(markup, /gear-owned-preview/);
assert.match(markup, /id="gear-list-form"[\s\S]*?id="gear-name"[\s\S]*?id="gear-category"[\s\S]*?id="gear-price"[\s\S]*?id="gear-status"[\s\S]*?id="gear-priority"[\s\S]*?id="gear-memo"/);
assert.doesNotMatch(gearFormMarkup, /id="gear-manufacturer"|name="manufacturer"|>メーカー</);
assert.doesNotMatch(gearFormMarkup, /id="gear-url"|name="url"|>URL</);
assert.match(markup, /maxlength="100"/);
assert.match(markup, /id="gear-memo"[\s\S]*?maxlength="1000"/);
assert.match(markup, /id="gear-memo"[\s\S]*?rows="4"/);
assert.match(markup, /id="gear-category"[\s\S]*?<option value="">選択してください<\/option>/);
assert.match(markup, /id="gear-price" name="priceText" type="text" maxlength="100"/);
assert.match(markup, /placeholder="例：198,000円、約20万円、未定"/);
assert.doesNotMatch(gearFormMarkup, /id="gear-price"[^>]*type="number"|name="priceYen"|inputmode="numeric"/);
assert.match(markup, /option value="owned">自分の機材/);
assert.match(markup, /option value="wishlist">ほしい機材/);
assert.match(markup, /option value="sold">手放した機材/);
assert.match(gearFormMarkup, /id="gear-photo-input" type="file" accept="image\/\*"/);
assert.match(gearFormMarkup, /id="gear-photo-preview"/);
assert.match(gearFormMarkup, /id="gear-photo-readjust"/);
assert.match(gearFormMarkup, /id="gear-photo-remove"/);
assert.match(markup, /id="gear-photo-crop-dialog"[\s\S]*?aria-modal="true"/);
assert.match(markup, /id="gear-photo-lightbox"[\s\S]*?aria-modal="true"/);

for (const category of ['guitar', 'effects', 'amp', 'dtm', 'recording', 'accessories', 'other']) {
    assert.match(store, new RegExp(`key: '${category}'`));
}
assert.match(categoryStore, /GEAR_CATEGORY_STORAGE_KEY = 'cruisePort\.gearCategories'/);
assert.match(categoryStore, /GEAR_CATEGORY_SCHEMA_VERSION = 1/);
assert.match(categoryStore, /id: 'guitar', name: 'ギター'/);
assert.match(categoryStore, /id: 'sound', name: '音作り'/);
assert.match(categoryStore, /id: 'accessories', name: 'アクセサリー'/);
assert.match(categoryStore, /export function deleteGearCategory/);
assert.match(store, /GEAR_LIST_STORAGE_KEY = 'cruisePort\.gearList'/);
assert.match(store, /GEAR_LIST_SCHEMA_VERSION = 4/);
assert.doesNotMatch(store, /localStorage\.clear/);

assert.match(source, /parseGearRoute\(hash\)/);
assert.match(source, /#wishlist\/new/);
assert.match(source, /#wishlist\/\$\{encodeURIComponent\(item\.id\)\}\/edit/);
assert.match(source, /replaceGearListRoute\(\)/);
assert.match(source, /saveGearList\(candidateItems\)/);
assert.match(source, /gearState\.items = candidateItems/);
assert.match(source, /populateGearCategoryOptions\(item\?\.category \|\| getInitialGearCategory\(gearState\.activeCategory\)\)/);
assert.match(source, /getGearCategoryName\(gearState\.categories, item\.category\)/);
assert.match(source, /elements\.gearCategoryMenuToggle\.addEventListener\('click', toggleGearCategoryMenu\)/);
assert.match(source, /closeGearCategoryMenu\(\{ restoreFocus: false \}\)/);
assert.match(source, /event\.key === 'Escape'/);
assert.match(source, /gearCategoryMenuWrap\?\.contains\(event\.target\)/);
assert.match(source, /elements\.gearCategoryAdd\.addEventListener\('click'/);
assert.match(source, /openGearCategoryDialog\('rename'\)/);
assert.match(source, /saveGearCategories\(result\.categories\)/);
assert.match(source, /deleteGearCategory\(gearState\.categories, category\.id\)/);
assert.match(source, /loadGearList\(\)/);
assert.match(source, /latestItems\.some\(\(item\) => item\.category === category\.id\)/);
assert.match(source, /gearState\.activeCategory = 'all'/);
assert.match(source, /このカテゴリには機材が登録されています。/);
assert.match(source, /markGearPurchased\(gearState\.items, item\.id\)/);
assert.match(source, /markGearSold\(gearState\.items, item\.id\)/);
assert.match(source, /restoreGearOwned\(gearState\.items, item\.id\)/);
assert.match(source, /moveGearItem\(gearState\.reorderItems, id, direction\)/);
assert.match(source, /\$\{item\.name\}を自分の機材に追加しますか？/);
assert.match(source, /\$\{item\.name\}を手放した機材へ移しますか？/);
assert.match(source, /\$\{item\.name\}を所有中の機材へ戻しますか？/);
assert.match(source, /\$\{item\.name\}を機材リストから削除しますか？/);
assert.match(source, /\$\{item\.name\}をほしい機材から削除しますか？/);
assert.match(source, /price\.textContent = item\.priceText/);
assert.match(source, /heading\.append\(name\);/);
assert.match(source, /card\.append\(createGearMetadata\(item\)\);/);
assert.match(source, /getGearSections\(\)/);
assert.match(source, /activeStatus: 'all'/);
assert.match(source, /button\.disabled = gearState\.reorderMode/);
assert.match(source, /if \(!chip \|\| gearState\.reorderMode\) return;/);
assert.doesNotMatch(source, /gearManufacturerInput|gearUrlInput|formatGearPrice/);
assert.doesNotMatch(gearSource, /item\.manufacturer|item\.url|item\.priceYen/);
assert.doesNotMatch(gearSource, /商品ページを開く/);
assert.doesNotMatch(source, /innerHTML/);
assert.doesNotMatch(source, /localStorage\.clear/);
assert.match(source, /createGearPhotoStore\(\)/);
assert.match(source, /commitGearPhotoChange/);
assert.match(source, /commitGearPhotoRemoval/);
assert.match(source, /commitGearItemDeletion/);
assert.match(store, /photoId: null/);
assert.match(source, /URL\.createObjectURL\(blob\)/);
assert.match(source, /URL\.revokeObjectURL\(url\)/);
assert.match(source, /if \(!result\.ok \|\| !result\.record\?\.blob \|\| !button\.isConnected\) return/);
assert.match(source, /写真を読み込めませんでした。機材情報はそのまま利用できます。/);
assert.doesNotMatch(source, /cruisePortMyApps.*photos|myAppsIconStore\.saveIcon\([^)]*gear/i);

assert.match(styles, /\.gear-category-filter[\s\S]*?overflow-x: auto/);
assert.match(styles, /\.gear-category-toolbar[\s\S]*?display: flex/);
assert.match(styles, /\.gear-category-filter[\s\S]*?flex: 1 1 auto[\s\S]*?min-width: 0/);
assert.match(styles, /\.gear-category-chip[\s\S]*?min-height: 44px/);
assert.match(styles, /\.gear-category-filter[\s\S]*?scroll-snap-type: x proximity/);
assert.match(styles, /\.gear-category-actions[\s\S]*?gap: 8px/);
assert.match(styles, /\.gear-category-actions[\s\S]*?flex: 0 0 auto/);
assert.match(styles, /\.gear-category-action[\s\S]*?width: 44px[\s\S]*?height: 44px/);
assert.match(styles, /\.gear-category-menu-toggle[\s\S]*?width: 44px[\s\S]*?height: 44px/);
assert.match(styles, /\.gear-category-menu[\s\S]*?position: absolute/);
assert.match(styles, /\.gear-category-menu-item[\s\S]*?min-height: 44px/);
assert.match(styles, /\.gear-category-action:disabled/);
assert.match(styles, /\.gear-category-dialog[\s\S]*?position: fixed/);
assert.match(styles, /\.gear-category-chip:disabled/);
assert.match(styles, /\.gear-card-memo[\s\S]*?-webkit-line-clamp: 2/);
assert.match(styles, /\.gear-card-actions/);
assert.match(styles, /\.gear-card-actions[\s\S]*?grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/);
assert.match(styles, /\.gear-purchase-action/);
assert.match(styles, /\.gear-card--reorder/);
assert.match(styles, /\.gear-form-view textarea[\s\S]*?min-height: 104px/);
assert.match(styles, /\.gear-card-photo[\s\S]*?width: 84px[\s\S]*?height: 84px/);
assert.match(styles, /\.gear-photo-preview[\s\S]*?aspect-ratio: 1/);
assert.match(styles, /\.gear-photo-lightbox[\s\S]*?position: fixed/);

console.log('gear-list-ui: core UI, safe rendering, routing, and mobile layout checks passed');
