import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import {getCapabilities,isProAccessReady} from './cruise-port-capabilities.js';
import {PRO_ENTRY_PATH} from './cruise-port-edition.js';import {proAccessMarkup,PRO_VALUES,MEMBERSHIP_URL,MEMBER_POST_URL} from './pro-access-content.js';
import {createGearPhotoStore} from './gear-photo-store.js';import {createMyAppsIconStore} from './my-apps-icon-store.js';import {createPracticeAttachmentStore} from './practice-menu-attachment-store.js';
const read=p=>readFileSync(new URL(p,import.meta.url),'utf8');
function gate(locked=true){return {__SOUNDCRUISE_PRO_GATE__:{},__soundCruiseClearGate(){},document:{body:{classList:{contains:()=>locked}},getElementById:()=>locked?{}:null}};}
test('gate readiness is fail closed for missing script/body/overlay and permits shared gate unlock',()=>{assert.equal(isProAccessReady({}),false);assert.equal(isProAccessReady({...gate(false),__soundCruiseClearGate:undefined}),false);assert.equal(isProAccessReady(gate()),false);assert.equal(isProAccessReady(gate(false)),true);});
test('default Pro write APIs deny before unlock and after reset, without opening IndexedDB',async()=>{const keys=['location','document','__SOUNDCRUISE_PRO_GATE__','__soundCruiseClearGate'],old=keys.map(k=>Object.getOwnPropertyDescriptor(globalThis,k));let locked=true;try{const g=gate(false);g.document.body.classList.contains=()=>locked;g.document.getElementById=()=>locked?{}:null;for(const k of keys)Object.defineProperty(globalThis,k,{configurable:true,value:k==='location'?{pathname:PRO_ENTRY_PATH}:g[k]});const live=getCapabilities();assert.equal(live.gearPhotoWrite,false);for(const s of [createGearPhotoStore().savePhoto(new Blob()),createMyAppsIconStore().saveIcon(new Blob()),createPracticeAttachmentStore().addAttachment('test',new Blob())])assert.equal((await s).reason,'pro-required');locked=false;assert.equal(live.gearPhotoWrite,true);assert.equal(live.practiceMenuCreateLimit,Infinity);locked=true;assert.equal(live.practiceFileWrite,false);assert.equal(live.practiceMenuCreateLimit,5);globalThis.location.pathname='/apps/cruise-port/';locked=false;assert.equal(getCapabilities().gearPhotoWrite,false);}finally{keys.forEach((k,i)=>old[i]?Object.defineProperty(globalThis,k,old[i]):delete globalThis[k]);}});
test('access copy has exactly five factual values and explicitly keeps basic tools Standard and sync operations Pro',()=>{assert.equal(PRO_VALUES.length,5);const markup=proAccessMarkup();assert.match(markup,/通常版でも利用/);assert.match(markup,/最大100件/);assert.match(markup,/AIへ相談/);assert.doesNotMatch(markup,/保存数を気にせず|クラウド同期はPro|今すぐ購入/);});
test('official Forte links match all four apps; shared member post matches current Port gate',()=>{for(const app of ['pitch-cruise','fretboard_cruise','rhythm-cruise','chord-cruise'])assert(read(`../${app}/pro-access.html`).includes(MEMBERSHIP_URL));assert(read('../shared/pro-gate-help.js').includes(MEMBER_POST_URL));assert.match(read('../shared/pro-gate.js'),/SoundCruiseProPostHelp\?\.primaryLinkMarkup/);const markup=proAccessMarkup();assert(markup.includes(`href="${PRO_ENTRY_PATH}"`));assert.equal((markup.match(/target="_blank" rel="noopener noreferrer"/g)||[]).length,2);assert.match(markup,/4桁のパスワード/);assert.match(markup,/同じ端末・同じブラウザ/);assert.doesNotMatch(markup,/javascript:/);});
test('Port access design reuses all app card/step dimensions, does not load Account or Pro auth',()=>{const css=read('./pro-access.css');for(const app of ['pitch-cruise','fretboard_cruise','rhythm-cruise','chord-cruise']){const source=read(`../${app}/pro-access.html`);for(const rule of ['max-width: 420px','padding: 32px 24px','border-radius: 16px','width: 40px','height: 40px']){assert(source.includes(rule));assert(css.includes(rule));}}assert.match(css,/focus-visible/);assert.match(css,/box-sizing: border-box/);assert.doesNotMatch(read('./pro-access.html')+read('./pro-access-page.js'),/sync-account|pro-gate\.js|fetch\(|localStorage|indexedDB/);});
test('Pro entry boot waits for shared gate, while Standard and Pro use same storage/tool modules',()=>{const pro=read('./pro_9a3943176561/index.html'),standard=read('./index.html'),boot=read('./pro-app-boot.js');assert.match(pro,/pro-app-boot\.js\?v=1\.19\.1/);assert.doesNotMatch(pro,/<script type="module" src="[^"\n]*practice-menu-app/);assert.match(standard,/practice-menu-app\.js\?v=1\.19\.1/);assert.match(boot,/if \(started \|\| !isProAccessReady\(\)\) return/);assert.match(boot,/import\('\.\/practice-menu-app\.js\?v=1\.19\.1'\)/);assert.doesNotMatch(boot,/localStorage|indexedDB|passwordHash|fetch\(/);});
